import type {
  ComponentOverrideAnalysis,
  NormalizedOverride,
  OverrideFramework,
} from "../core/component-overrides.ts";
import type { IslandSpec } from "./islands.ts";

/**
 * Turn the project's MDX/layout overrides into the generated `components.ts`
 * module plus per-override hydration wrappers.
 *
 * Every override is imported statically so Vite can see it: a static override
 * imports its file directly, while a hydrated one gets a wrapper `.astro` that
 * applies the `client:*` directive (Astro directives must be written
 * statically). The `islands/` folder convention feeds the same plan — each
 * discovered island is an `mdx` entry with its client mode — so a
 * `components.ts` `mdx` entry of the same name replaces the convention island.
 */

export interface ComponentSlotWrapper {
  content: string;
  /** File name (no extension) under `.blume/src/generated/component-slots/`. */
  name: string;
}

export interface ComponentSlotPlan {
  /** Frameworks used by resolved overrides; enable the matching Astro renderer. */
  frameworks: Set<OverrideFramework>;
  /** Contents of `.blume/src/generated/components.ts`. */
  module: string;
  wrappers: ComponentSlotWrapper[];
}

// A user-supplied attribute value interpolated into a generated .astro tag: a
// stray quote or newline would produce a malformed component and an opaque
// Astro parse error pointing at the generated file, not the user's config.
const attributeValue = (value: string): string =>
  value.replaceAll(/["\n\r]/gu, " ").trim();

const CLIENT_LOAD = "client:load";

/** Astro client directive for a hydrated override. */
const directiveFor = (override: NormalizedOverride): string => {
  const { framework } = override.source;
  switch (override.client) {
    case "idle": {
      return "client:idle";
    }
    case "visible": {
      return "client:visible";
    }
    case "media": {
      return override.media
        ? `client:media="${attributeValue(override.media)}"`
        : CLIENT_LOAD;
    }
    case "only": {
      return framework
        ? `client:only="${attributeValue(framework)}"`
        : CLIENT_LOAD;
    }
    default: {
      return CLIENT_LOAD;
    }
  }
};

const importClause = (variable: string, name: string, path: string): string =>
  name === "default"
    ? `import ${variable} from ${JSON.stringify(path)};`
    : `import { ${name} as ${variable} } from ${JSON.stringify(path)};`;

/**
 * Frontmatter `Props` alias mirroring the wrapped component's own props, so
 * `{...Astro.props}` satisfies required props under `astro check` (the spread
 * of an untyped `Astro.props` contributes nothing to the JSX props type).
 * `infer P extends object` rather than `Record<string, unknown>` because
 * interfaces have no implicit index signature and would miss the narrower
 * constraint. Non-function component types (Vue/Svelte ambient modules) fall
 * back to an open record, keeping the untyped permissiveness they had.
 */
export const wrapperPropsType = (name: string): string =>
  `type Props = typeof ${name} extends (
  props: infer P extends object,
  ...rest: never[]
) => unknown
  ? P
  : Record<string, unknown>;`;

/** A wrapper `.astro` that statically imports a component and hydrates it. */
const wrapperContent = (override: NormalizedOverride): string => `---
// Generated by Blume. Do not edit.
${importClause("Component", override.source.name, override.source.path)}
${wrapperPropsType("Component")}
---
<Component ${directiveFor(override)} {...Astro.props}><slot /></Component>
`;

/**
 * A filesystem-safe, injective token for an override key. Distinct keys must
 * never share a wrapper file ("Foo.Bar" vs "Foo_Bar" used to collide, racing
 * the same temp file and silently rendering the wrong component), so every
 * non-alphanumeric character is hex-escaped rather than collapsed — the same
 * hardening as `exampleSlug` in templates.ts.
 */
const sanitize = (value: string): string =>
  value.replaceAll(
    /[^A-Za-z0-9]/gu,
    (char) => `_${(char.codePointAt(0) ?? 0).toString(16)}_`
  );

/** A convention island as the `mdx` override it is equivalent to. */
const islandOverride = (island: IslandSpec): NormalizedOverride => ({
  client: island.client,
  key: island.name,
  source: { framework: island.framework, name: "default", path: island.file },
});

/** An object-literal source for a group's `key: variable` entries. */
const record = (entries: string[]): string =>
  entries.length ? `{ ${entries.join(", ")} }` : "{}";

/**
 * Plan the generated components module for the `islands/` convention plus the
 * analyzed `components.ts` (empty when the project has none). Within a group
 * the last entry for a key wins, so `components.ts` overrides a convention
 * island.
 */
export const planComponentSlots = (
  islands: IslandSpec[],
  analysis: ComponentOverrideAnalysis
): ComponentSlotPlan => {
  const frameworks = new Set<OverrideFramework>();
  const wrappers: ComponentSlotWrapper[] = [];
  const importLines: string[] = [];
  let counter = 0;

  const plan = (
    overrides: NormalizedOverride[],
    group: "mdx" | "layout"
  ): string[] => {
    const byKey = new Map<string, NormalizedOverride>();
    for (const override of overrides) {
      byKey.set(override.key, override);
    }
    const entries: string[] = [];
    for (const override of byKey.values()) {
      const { source } = override;
      if (source.framework) {
        frameworks.add(source.framework);
      }
      const variable = `__blumeSlot${counter}`;
      counter += 1;
      if (override.client) {
        const name = `${group}-${sanitize(override.key)}`;
        wrappers.push({ content: wrapperContent(override), name });
        importLines.push(
          importClause(variable, "default", `./component-slots/${name}.astro`)
        );
      } else {
        importLines.push(importClause(variable, source.name, source.path));
      }
      entries.push(`${JSON.stringify(override.key)}: ${variable}`);
    }
    return entries;
  };

  const mdxEntries = plan(
    [...islands.map(islandOverride), ...analysis.mdx],
    "mdx"
  );
  const layoutEntries = plan(analysis.layout, "layout");

  const module = `// Generated by Blume. Do not edit.
import type { ComponentOverride } from "blume/core/define-components.ts";
${importLines.join("\n")}${importLines.length ? "\n" : ""}export const mdxComponents: Record<string, ComponentOverride> = ${record(mdxEntries)};
export const layoutOverrides: Record<string, ComponentOverride> = ${record(layoutEntries)};
`;

  return { frameworks, module, wrappers };
};
