import type { ResolvedConfig } from "../core/schema.ts";
import type { ProjectContext } from "../core/types.ts";
import type { BlumePageRoute } from "./integration.ts";

const ADAPTER_IMPORTS: Record<string, string> = {
  cloudflare: "@astrojs/cloudflare",
  netlify: "@astrojs/netlify",
  node: "@astrojs/node",
  vercel: "@astrojs/vercel",
};

const ADAPTER_OPTIONS: Record<string, string> = {
  node: '{ mode: "standalone" }',
};

/**
 * Integration packages the generated runtime imports. Declaring them in
 * `.blume/package.json` lets Astro's framework-package crawl discover and bundle
 * them — notably the React renderer's server entry, which imports the
 * `astro:react:opts` virtual module and must not be externalized (this applies
 * across the `ssr`, `prerender`, and `client` Vite environments).
 */
export const runtimeDependencies = (options: {
  config: ResolvedConfig;
  needsReact: boolean;
}): string[] => {
  const { config, needsReact } = options;
  const deps = ["@astrojs/mdx"];
  if (needsReact) {
    deps.push("@astrojs/react");
  }
  const { deployment } = config;
  if (deployment.output === "server" && deployment.adapter) {
    const adapter = ADAPTER_IMPORTS[deployment.adapter];
    if (adapter) {
      deps.push(adapter);
    }
  }
  return deps;
};

/** Generate `.blume/astro.config.mjs`. */
export const astroConfigTemplate = (options: {
  context: ProjectContext;
  config: ResolvedConfig;
  needsReact: boolean;
  pages: BlumePageRoute[];
  dataPath: string;
  themePath: string;
}): string => {
  const { context, config, needsReact, pages, dataPath, themePath } = options;
  const { deployment } = config;
  const server = deployment.output === "server";

  const adapterImport =
    server && deployment.adapter
      ? `import adapter from "${ADAPTER_IMPORTS[deployment.adapter]}";\n`
      : "";
  const adapterArgs =
    server && deployment.adapter
      ? (ADAPTER_OPTIONS[deployment.adapter] ?? "")
      : "";
  const adapterOption =
    server && deployment.adapter ? `\n  adapter: adapter(${adapterArgs}),` : "";

  const siteOption = deployment.site
    ? `\n  site: ${JSON.stringify(deployment.site)},`
    : "";
  const baseOption = deployment.base
    ? `\n  base: ${JSON.stringify(deployment.base)},`
    : "";

  const redirectsOption =
    config.redirects.length > 0
      ? `\n  redirects: ${JSON.stringify(
          Object.fromEntries(
            config.redirects.map((redirect) => [
              redirect.from,
              { destination: redirect.to, status: redirect.status },
            ])
          )
        )},`
      : "";

  // React is only wired in when the project actually uses React islands. The
  // core theme is Astro-first and ships no client JS.
  const reactImport = needsReact ? `import react from "@astrojs/react";\n` : "";
  const blumeImport = pages.length
    ? `import { blumeIntegration } from "blume/astro";\n`
    : "";

  const integrations = [
    `mdx({ processor: blumeMdxProcessor(${JSON.stringify({
      math: config.markdown.math,
    })}) })`,
  ];
  if (needsReact) {
    integrations.push("react()");
  }
  if (pages.length) {
    integrations.push(`blumeIntegration(${JSON.stringify({ pages })})`);
  }

  return `// Generated by Blume. Do not edit; this file is recreated on each run.
import { defineConfig } from "astro/config";
import mdx from "@astrojs/mdx";
import tailwindcss from "@tailwindcss/vite";
import { blumeMarkdownProcessor, blumeMdxProcessor, codeTitleTransformer } from "blume/markdown";
${reactImport}${blumeImport}${adapterImport}
export default defineConfig({
  root: ${JSON.stringify(context.outDir)},
  srcDir: ${JSON.stringify(`${context.outDir}/src`)},
  outDir: ${JSON.stringify(`${context.root}/dist`)},
  publicDir: ${JSON.stringify(`${context.root}/public`)},
  output: ${JSON.stringify(deployment.output)},${adapterOption}${siteOption}${baseOption}${redirectsOption}
  integrations: [${integrations.join(", ")}],
  markdown: {
    processor: blumeMarkdownProcessor(),
    shikiConfig: {
      themes: {
        light: "github-light",
        dark: "github-dark",
      },
      defaultColor: false,
      transformers: [codeTitleTransformer()],
    },
  },
  devToolbar: { enabled: false },
  vite: {
    plugins: [tailwindcss()],
    resolve: {
      alias: {
        "blume:data": ${JSON.stringify(dataPath)},
        "blume:theme": ${JSON.stringify(themePath)},
      },
    },
    server: {
      fs: {
        allow: [${JSON.stringify(context.root)}],
      },
    },
  },
});
`;
};

/** Generate `.blume/src/content.config.ts`. */
export const contentConfigTemplate = (options: {
  context: ProjectContext;
  config: ResolvedConfig;
}): string => {
  const { context, config } = options;
  return `// Generated by Blume. Do not edit.
import { defineCollection } from "astro:content";
import { glob } from "astro/loaders";

const docs = defineCollection({
  loader: glob({
    pattern: ${JSON.stringify(config.content.include)},
    base: ${JSON.stringify(context.contentRoot)},
    generateId: ({ entry }) => entry,
  }),
});

export const collections = { docs };
`;
};

/** Generate `.blume/src/pages/[...slug].astro`, the docs catch-all route. */
/** Generate the Ask AI server endpoint (`.blume/src/pages/api/ask.ts`). */
export const askEndpointTemplate = (model: string): string =>
  `// Generated by Blume. Do not edit.
import type { APIRoute } from "astro";
import { streamText } from "ai";

export const prerender = false;

export const POST: APIRoute = async ({ request }) => {
  const { messages } = await request.json();
  const result = streamText({
    model: ${JSON.stringify(model)},
    system:
      "You are a helpful documentation assistant. Answer using the project's documentation.",
    messages,
  });
  return result.toTextStreamResponse();
};
`;

/** Generate the Orama search index endpoint (`/blume-search.json`). */
export const searchEndpointTemplate = (): string =>
  `// Generated by Blume. Do not edit.
import documents from "../generated/search.json";

export const prerender = true;

export function GET() {
  return new Response(JSON.stringify(documents), {
    headers: { "Content-Type": "application/json" },
  });
}
`;

/** Generate the OG image endpoint (`.blume/src/pages/_og/[...slug].png.ts`). */
export const ogEndpointTemplate = (): string =>
  `// Generated by Blume. Do not edit.
import { renderOgImage } from "blume/og";
import data from "../../generated/data.json";

export const prerender = true;

export function getStaticPaths() {
  return data.routes.map((route) => ({
    params: { slug: route.path === "/" ? "index" : route.path.slice(1) },
    props: { title: route.title },
  }));
}

export async function GET({ props }) {
  const png = await renderOgImage({
    title: props.title,
    eyebrow: data.config.title,
    accent: data.config.theme.accent,
  });
  return new Response(png, {
    headers: {
      "Cache-Control": "public, max-age=31536000, immutable",
      "Content-Type": "image/png",
    },
  });
}
`;

export const catchAllPageTemplate = (options: {
  askEnabled: boolean;
  mathEnabled: boolean;
}): string => {
  const askImport = options.askEnabled
    ? 'import AskAI from "blume/components/islands/AskAI.astro";\n'
    : "";
  const askSlot = options.askEnabled ? '\n  <AskAI slot="ask" />' : "";
  const mathImport = options.mathEnabled
    ? 'import Math from "blume/components/content/Math.astro";\n'
    : "";
  const mathEntry = options.mathEnabled ? "Math,\n  " : "";

  return `---
// Generated by Blume. Do not edit.
import { getEntry, render } from "astro:content";
import RootLayout from "blume/components/layout/RootLayout.astro";
${askImport}
import Accordion from "blume/components/content/Accordion.astro";
import Badge from "blume/components/content/Badge.astro";
import Callout from "blume/components/content/Callout.astro";
import Card from "blume/components/content/Card.astro";
import CardGroup from "blume/components/content/CardGroup.astro";
import FileTree from "blume/components/content/FileTree.astro";
import Step from "blume/components/content/Step.astro";
import Steps from "blume/components/content/Steps.astro";
import Tab from "blume/components/content/Tab.astro";
import Tabs from "blume/components/content/Tabs.astro";
import AuthMethod from "blume/components/api/AuthMethod.astro";
import Endpoint from "blume/components/api/Endpoint.astro";
import ParameterTable from "blume/components/api/ParameterTable.astro";
import RequestExample from "blume/components/api/RequestExample.astro";
import ResponseExample from "blume/components/api/ResponseExample.astro";
import Icon from "blume/components/Icon.astro";
${mathImport}import { mdxComponents as userMdx } from "../generated/components.ts";
import data from "../generated/data.json";

// Docs content is file-based and always prerendered, even in server output
// (where only endpoints like /api/ask render on demand). Without this, server
// builds would render this route on demand and ignore getStaticPaths, leaving
// the entry id undefined.
export const prerender = true;

const components = {
  Accordion,
  AuthMethod,
  Badge,
  Callout,
  Card,
  CardGroup,
  Endpoint,
  FileTree,
  Icon,
  ParameterTable,
  RequestExample,
  ResponseExample,
  Step,
  Steps,
  Tab,
  Tabs,
  ${mathEntry}...userMdx,
};

export function getStaticPaths() {
  return data.routes.map((route) => ({
    params: { slug: route.path === "/" ? undefined : route.path.slice(1) },
    props: {
      entryId: route.id,
      indexable: route.indexable,
      route: route.path,
      title: route.title,
    },
  }));
}

const { entryId, route, title, indexable } = Astro.props;
const entry = await getEntry("docs", entryId);
if (!entry) {
  return new Response(null, { status: 404 });
}
const { Content, headings } = await render(entry);
const frontmatter = entry.data ?? {};

const ogPath = data.config.og.enabled
  ? \`/og/\${route === "/" ? "index" : route.slice(1)}.png\`
  : null;
const ogRel = frontmatter.seo?.image ?? ogPath;
const ogImage =
  ogRel && data.config.site
    ? \`\${data.config.site.replace(/\\/$/, "")}\${ogRel}\`
    : ogRel;
---

<RootLayout
  site={{ title: data.config.title, description: data.config.description }}
  navigation={data.navigation}
  page={{ title, description: frontmatter.description, route }}
  headings={headings}
  themeMode={data.config.theme.mode}
  searchEnabled={data.config.search.enabled}
  searchProvider={data.config.search.provider}
  indexable={indexable}
  ogImage={ogImage}
>${askSlot}
  <Content components={components} />
</RootLayout>
`;
};

/**
 * Generate `.blume/src/generated/components.ts`, which re-exports the user's
 * component overrides (or empty maps when no `components.ts` exists). Importing
 * the user file here lets Astro/Vite compile any `.astro`/`.tsx` it references.
 */
export const userComponentsTemplate = (
  componentsFile: string | null
): string => {
  if (!componentsFile) {
    return `// Generated by Blume. Do not edit.
export const mdxComponents = {};
export const layoutOverrides = {};
`;
  }
  return `// Generated by Blume. Do not edit.
import overrides from ${JSON.stringify(componentsFile)};
export const mdxComponents = overrides.mdx ?? {};
export const layoutOverrides = overrides.layout ?? {};
`;
};

/** Generate `.blume/src/env.d.ts`. */
export const envTemplate =
  (): string => `/// <reference path="../.astro/types.d.ts" />
/// <reference types="astro/client" />
`;

/** Generate `.blume/package.json`. */
export const runtimePackageTemplate = (dependencies: string[] = []): string =>
  `${JSON.stringify(
    {
      dependencies: Object.fromEntries(
        [...dependencies].toSorted().map((name) => [name, "*"])
      ),
      name: "blume-runtime",
      private: true,
      type: "module",
      version: "0.0.0",
    },
    null,
    2
  )}\n`;

/** Generate `.blume/tsconfig.json`. */
export const runtimeTsconfigTemplate = (): string =>
  `${JSON.stringify(
    {
      exclude: ["dist"],
      extends: "astro/tsconfigs/strict",
      include: [".astro/types.d.ts", "**/*"],
    },
    null,
    2
  )}\n`;
