import type { ResolvedConfig } from "../core/schema.ts";
import type { ProjectContext } from "../core/types.ts";

const ADAPTER_IMPORTS: Record<string, string> = {
  cloudflare: "@astrojs/cloudflare",
  netlify: "@astrojs/netlify",
  node: "@astrojs/node",
  vercel: "@astrojs/vercel",
};

/** Generate `.blume/astro.config.mjs`. */
export const astroConfigTemplate = (options: {
  context: ProjectContext;
  config: ResolvedConfig;
  needsReact: boolean;
}): string => {
  const { context, config } = options;
  const { deployment } = config;
  const server = deployment.output === "server";

  const adapterImport =
    server && deployment.adapter
      ? `import adapter from "${ADAPTER_IMPORTS[deployment.adapter]}";\n`
      : "";
  const adapterOption =
    server && deployment.adapter ? "\n  adapter: adapter()," : "";

  const siteOption = deployment.site
    ? `\n  site: ${JSON.stringify(deployment.site)},`
    : "";
  const baseOption = deployment.base
    ? `\n  base: ${JSON.stringify(deployment.base)},`
    : "";

  // React is only wired in when interactive islands are present (added in the
  // customization milestone). The core theme is Astro-first and ships no JS.
  const reactImport = options.needsReact
    ? `import react from "@astrojs/react";\n`
    : "";
  const integrations = options.needsReact ? "mdx(), react()" : "mdx()";

  return `// Generated by Blume. Do not edit; this file is recreated on each run.
import { defineConfig } from "astro/config";
import mdx from "@astrojs/mdx";
${reactImport}${adapterImport}
export default defineConfig({
  root: ${JSON.stringify(context.outDir)},
  srcDir: ${JSON.stringify(`${context.outDir}/src`)},
  outDir: ${JSON.stringify(`${context.root}/dist`)},
  publicDir: ${JSON.stringify(`${context.root}/public`)},
  output: ${JSON.stringify(deployment.output)},${adapterOption}${siteOption}${baseOption}
  integrations: [${integrations}],
  devToolbar: { enabled: false },
  vite: {
    server: {
      fs: {
        allow: [${JSON.stringify(context.root)}],
      },
    },
  },
});
`;
};

/** Generate `.blume/src/content.config.ts`. */
export const contentConfigTemplate = (options: {
  context: ProjectContext;
  config: ResolvedConfig;
}): string => {
  const { context, config } = options;
  return `// Generated by Blume. Do not edit.
import { defineCollection } from "astro:content";
import { glob } from "astro/loaders";

const docs = defineCollection({
  loader: glob({
    pattern: ${JSON.stringify(config.content.include)},
    base: ${JSON.stringify(context.contentRoot)},
    generateId: ({ entry }) => entry,
  }),
});

export const collections = { docs };
`;
};

/** Generate `.blume/src/pages/[...slug].astro`, the docs catch-all route. */
export const catchAllPageTemplate = (): string => `---
// Generated by Blume. Do not edit.
import { getEntry, render } from "astro:content";
import RootLayout from "blume/components/layout/RootLayout.astro";
import data from "../generated/data.json";

export function getStaticPaths() {
  return data.routes
    .filter((route) => !route.draft)
    .map((route) => ({
      params: { slug: route.path === "/" ? undefined : route.path.slice(1) },
      props: { entryId: route.id, route: route.path, title: route.title },
    }));
}

const { entryId, route, title } = Astro.props;
const entry = await getEntry("docs", entryId);
if (!entry) {
  return new Response(null, { status: 404 });
}
const { Content, headings } = await render(entry);
const frontmatter = entry.data ?? {};
---

<RootLayout
  site={{ title: data.config.title, description: data.config.description }}
  navigation={data.navigation}
  page={{ title, description: frontmatter.description, route }}
  headings={headings}
  themeMode={data.config.theme.mode}
>
  <Content />
</RootLayout>
`;

/** Generate `.blume/src/env.d.ts`. */
export const envTemplate =
  (): string => `/// <reference path="../.astro/types.d.ts" />
/// <reference types="astro/client" />
`;

/** Generate `.blume/package.json`. */
export const runtimePackageTemplate = (): string =>
  `${JSON.stringify(
    {
      name: "blume-runtime",
      private: true,
      type: "module",
      version: "0.0.0",
    },
    null,
    2
  )}\n`;

/** Generate `.blume/tsconfig.json`. */
export const runtimeTsconfigTemplate = (): string =>
  `${JSON.stringify(
    {
      exclude: ["dist"],
      extends: "astro/tsconfigs/strict",
      include: [".astro/types.d.ts", "**/*"],
    },
    null,
    2
  )}\n`;
