import type { ResolvedConfig } from "../core/schema.ts";
import type { ProjectContext } from "../core/types.ts";
import type { BlumePageRoute } from "./integration.ts";

const ADAPTER_IMPORTS: Record<string, string> = {
  cloudflare: "@astrojs/cloudflare",
  netlify: "@astrojs/netlify",
  node: "@astrojs/node",
  vercel: "@astrojs/vercel",
};

/** Generate `.blume/astro.config.mjs`. */
export const astroConfigTemplate = (options: {
  context: ProjectContext;
  config: ResolvedConfig;
  needsReact: boolean;
  pages: BlumePageRoute[];
  dataPath: string;
}): string => {
  const { context, config, needsReact, pages, dataPath } = options;
  const { deployment } = config;
  const server = deployment.output === "server";

  const adapterImport =
    server && deployment.adapter
      ? `import adapter from "${ADAPTER_IMPORTS[deployment.adapter]}";\n`
      : "";
  const adapterOption =
    server && deployment.adapter ? "\n  adapter: adapter()," : "";

  const siteOption = deployment.site
    ? `\n  site: ${JSON.stringify(deployment.site)},`
    : "";
  const baseOption = deployment.base
    ? `\n  base: ${JSON.stringify(deployment.base)},`
    : "";

  // React is only wired in when the project actually uses React islands. The
  // core theme is Astro-first and ships no client JS.
  const reactImport = needsReact ? `import react from "@astrojs/react";\n` : "";
  const blumeImport = pages.length
    ? `import { blumeIntegration } from "blume/astro";\n`
    : "";

  const integrations = ["mdx()"];
  if (needsReact) {
    integrations.push("react()");
  }
  if (pages.length) {
    integrations.push(`blumeIntegration(${JSON.stringify({ pages })})`);
  }

  // The React renderer's server entrypoint imports a Vite virtual module
  // (`astro:react:opts`); it must be bundled, not externalized, during SSR.
  const ssrConfig = needsReact
    ? '\n    ssr: {\n      noExternal: ["@astrojs/react"],\n    },'
    : "";

  return `// Generated by Blume. Do not edit; this file is recreated on each run.
import { defineConfig } from "astro/config";
import mdx from "@astrojs/mdx";
${reactImport}${blumeImport}${adapterImport}
export default defineConfig({
  root: ${JSON.stringify(context.outDir)},
  srcDir: ${JSON.stringify(`${context.outDir}/src`)},
  outDir: ${JSON.stringify(`${context.root}/dist`)},
  publicDir: ${JSON.stringify(`${context.root}/public`)},
  output: ${JSON.stringify(deployment.output)},${adapterOption}${siteOption}${baseOption}
  integrations: [${integrations.join(", ")}],
  devToolbar: { enabled: false },
  vite: {
    resolve: {
      alias: {
        "blume:data": ${JSON.stringify(dataPath)},
      },
    },${ssrConfig}
    server: {
      fs: {
        allow: [${JSON.stringify(context.root)}],
      },
    },
  },
});
`;
};

/** Generate `.blume/src/content.config.ts`. */
export const contentConfigTemplate = (options: {
  context: ProjectContext;
  config: ResolvedConfig;
}): string => {
  const { context, config } = options;
  return `// Generated by Blume. Do not edit.
import { defineCollection } from "astro:content";
import { glob } from "astro/loaders";

const docs = defineCollection({
  loader: glob({
    pattern: ${JSON.stringify(config.content.include)},
    base: ${JSON.stringify(context.contentRoot)},
    generateId: ({ entry }) => entry,
  }),
});

export const collections = { docs };
`;
};

/** Generate `.blume/src/pages/[...slug].astro`, the docs catch-all route. */
export const catchAllPageTemplate = (options: {
  themeFile: string | null;
}): string => {
  const userTheme = options.themeFile
    ? `import ${JSON.stringify(options.themeFile)};\n`
    : "";

  return `---
// Generated by Blume. Do not edit.
import { getEntry, render } from "astro:content";
import RootLayout from "blume/components/layout/RootLayout.astro";
import Accordion from "blume/components/content/Accordion.astro";
import Badge from "blume/components/content/Badge.astro";
import Callout from "blume/components/content/Callout.astro";
import Card from "blume/components/content/Card.astro";
import CardGroup from "blume/components/content/CardGroup.astro";
import FileTree from "blume/components/content/FileTree.astro";
import Step from "blume/components/content/Step.astro";
import Steps from "blume/components/content/Steps.astro";
import Tab from "blume/components/content/Tab.astro";
import Tabs from "blume/components/content/Tabs.astro";
import AuthMethod from "blume/components/api/AuthMethod.astro";
import Endpoint from "blume/components/api/Endpoint.astro";
import ParameterTable from "blume/components/api/ParameterTable.astro";
import RequestExample from "blume/components/api/RequestExample.astro";
import ResponseExample from "blume/components/api/ResponseExample.astro";
import Icon from "blume/components/Icon.astro";
import { mdxComponents as userMdx } from "../generated/components.ts";
import data from "../generated/data.json";
import "../generated/theme.css";
${userTheme}
const components = {
  Accordion,
  AuthMethod,
  Badge,
  Callout,
  Card,
  CardGroup,
  Endpoint,
  FileTree,
  Icon,
  ParameterTable,
  RequestExample,
  ResponseExample,
  Step,
  Steps,
  Tab,
  Tabs,
  ...userMdx,
};

export function getStaticPaths() {
  return data.routes.map((route) => ({
    params: { slug: route.path === "/" ? undefined : route.path.slice(1) },
    props: {
      entryId: route.id,
      indexable: route.indexable,
      route: route.path,
      title: route.title,
    },
  }));
}

const { entryId, route, title, indexable } = Astro.props;
const entry = await getEntry("docs", entryId);
if (!entry) {
  return new Response(null, { status: 404 });
}
const { Content, headings } = await render(entry);
const frontmatter = entry.data ?? {};
---

<RootLayout
  site={{ title: data.config.title, description: data.config.description }}
  navigation={data.navigation}
  page={{ title, description: frontmatter.description, route }}
  headings={headings}
  themeMode={data.config.theme.mode}
  searchEnabled={data.config.search.enabled}
  indexable={indexable}
>
  <Content components={components} />
</RootLayout>
`;
};

/**
 * Generate `.blume/src/generated/components.ts`, which re-exports the user's
 * component overrides (or empty maps when no `components.ts` exists). Importing
 * the user file here lets Astro/Vite compile any `.astro`/`.tsx` it references.
 */
export const userComponentsTemplate = (
  componentsFile: string | null
): string => {
  if (!componentsFile) {
    return `// Generated by Blume. Do not edit.
export const mdxComponents = {};
export const layoutOverrides = {};
`;
  }
  return `// Generated by Blume. Do not edit.
import overrides from ${JSON.stringify(componentsFile)};
export const mdxComponents = overrides.mdx ?? {};
export const layoutOverrides = overrides.layout ?? {};
`;
};

/** Generate `.blume/src/env.d.ts`. */
export const envTemplate =
  (): string => `/// <reference path="../.astro/types.d.ts" />
/// <reference types="astro/client" />
`;

/** Generate `.blume/package.json`. */
export const runtimePackageTemplate = (): string =>
  `${JSON.stringify(
    {
      name: "blume-runtime",
      private: true,
      type: "module",
      version: "0.0.0",
    },
    null,
    2
  )}\n`;

/** Generate `.blume/tsconfig.json`. */
export const runtimeTsconfigTemplate = (): string =>
  `${JSON.stringify(
    {
      exclude: ["dist"],
      extends: "astro/tsconfigs/strict",
      include: [".astro/types.d.ts", "**/*"],
    },
    null,
    2
  )}\n`;
