import type { UIStringsOverride } from "../i18n-ui.ts";

/** Arabic (ar) UI strings. */
export const ar: UIStringsOverride = {
  actions: {
    addToCursor: "إضافة إلى Cursor",
    addToVscode: "إضافة إلى VS Code",
    askAboutCode: "اسأل عن هذه الشيفرة",
    connectMcp: "الاتصال بـ MCP",
    copied: "تم النسخ!",
    copyClaudeCode: "نسخ أمر Claude Code",
    copyCode: "نسخ الكود",
    copyCodex: "نسخ أمر Codex",
    copyFailed: "فشل النسخ",
    copyMarkdown: "نسخ بصيغة Markdown",
    copyServerUrl: "نسخ عنوان URL للخادم",
    edit: "التعديل على GitHub",
    export: "تصدير",
    exportEpub: "التصدير إلى EPUB",
    exportPdf: "التصدير إلى PDF",
    generating: "جارٍ الإنشاء…",
    openIn: "فتح في {name}",
    openInChat: "فتح في المحادثة",
    openInChatPrompt: "اقرأ {url} حتى أتمكن من طرح أسئلة حول هذه الصفحة.",
    scrollToTop: "العودة إلى الأعلى",
  },
  assistant: {
    ai: "الذكاء الاصطناعي",
    clear: "مسح المحادثة",
    close: "إغلاق",
    copy: "نسخ المحادثة",
    empty: "اطرح سؤالاً حول الوثائق.",
    error: "عذراً، حدث خطأ ما.",
    explainCode: "اشرح هذه الشيفرة.",
    label: "اطرح سؤالاً",
    placeholder: "اطرح سؤالاً…",
    rateLimited: "لقد طرحت الكثير من الأسئلة. حاول مرة أخرى بعد بضع دقائق.",
    removeCode: "إزالة الشيفرة",
    send: "إرسال",
    support: "تواصل مع الدعم",
    supportSubject: "سؤال من التوثيق",
    tip: "نصيحة: يمكنك فتح المحادثة وإغلاقها باستخدام",
    title: "المساعد",
    verifyFailed: "تعذّر التحقق من أنك إنسان. حاول مرة أخرى.",
    you: "أنت",
  },
  banner: { dismiss: "إغلاق الإعلان" },
  changelog: {
    description: "تحديثات المنتج وملاحظات الإصدارات.",
    title: "سجل التغييرات",
  },
  consent: {
    accept: "قبول",
    decline: "رفض",
    label: "الموافقة على ملفات تعريف الارتباط",
    message: "نودّ استخدام ملفات تعريف الارتباط لفهم كيفية استخدام هذا التوثيق.",
    policy: "سياسة الخصوصية",
    settings: "إعدادات ملفات تعريف الارتباط",
  },
  content: {
    code: "الكود",
    copyColor: "نسخ اللون {name} {value}",
    copyPrompt: "نسخ الموجّه",
    default: "الافتراضي",
    diagramError: "تعذّر عرض هذا المخطط.",
    forks: "التفرعات",
    preview: "معاينة",
    prop: "الخاصية",
    selectTab: "اختيار علامة تبويب",
    selectView: "اختيار طريقة العرض",
    showLess: "عرض أقل",
    showMore: "عرض المزيد",
    stars: "النجوم",
    tab: "علامة التبويب {n}",
    type: "النوع",
    update: "تحديث",
  },
  feedback: {
    comment: "أخبرنا بالمزيد (اختياري)",
    no: "لا",
    question: "هل كانت هذه الصفحة مفيدة؟",
    send: "إرسال",
    thanks: "شكراً على ملاحظاتك!",
    yes: "نعم",
  },
  languageSwitcher: { label: "اللغة", untranslated: "غير مترجم" },
  narration: {
    cueDanger: "خطر.",
    cueInfo: "معلومة.",
    cueNote: "ملاحظة.",
    cueSection: "قسم قابل للتوسيع.",
    cueStep: "الخطوة {n}.",
    cueSuccess: "نجاح.",
    cueTab: "علامة التبويب {title}.",
    cueTip: "نصيحة.",
    cueWarning: "تحذير.",
    error: "تعذّر تحميل القراءة الصوتية.",
    follow: "متابعة القراءة",
    label: "استمع إلى هذه الصفحة",
    minutes: "{n} دقيقة",
    next: "الجملة التالية",
    pause: "إيقاف مؤقت",
    play: "تشغيل",
    previous: "الجملة السابقة",
    progress: "تقدّم القراءة",
    speed: "سرعة التشغيل",
    stop: "إيقاف الاستماع",
  },
  nav: {
    back: "رجوع",
    breadcrumb: "مسار التنقل",
    closeNavigation: "إغلاق التنقل",
    deprecated: "مهمل",
    featured: "مميز",
    githubRepository: "مستودع GitHub",
    navigation: "التنقل",
    opensInNewTab: "يفتح في علامة تبويب جديدة",
    primary: "رئيسي",
    sections: "الأقسام",
    toggleNavigation: "تبديل التنقل",
    toggleTheme: "تبديل سمة الألوان",
  },
  notFound: {
    description: "لم نتمكن من العثور على الصفحة التي تبحث عنها.",
    home: "العودة إلى الصفحة الرئيسية",
    title: "الصفحة غير موجودة",
  },
  page: {
    lastUpdated: "آخر تحديث في",
    next: "التالي",
    pagination: "ترقيم الصفحات",
    previous: "السابق",
    related: "صفحات ذات صلة",
    skipToContent: "الانتقال إلى المحتوى",
  },
  search: {
    all: "الكل",
    allLanguages: "جميع اللغات",
    assistant: "المساعد",
    assistantHint: "احصل على إجابة فورية من الذكاء الاصطناعي",
    button: "بحث",
    devOnly: "البحث متاح في إصدار الإنتاج.",
    docs: "الوثائق",
    error: "حدث خطأ ما. يرجى المحاولة مرة أخرى.",
    label: "البحث في الوثائق",
    latest: "الأحدث",
    navigate: "تنقل",
    noResults: "لم يتم العثور على نتائج.",
    open: "فتح",
    placeholder: "البحث في الوثائق…",
    popular: "شائع",
    preview: "معاينة",
    results: "النتائج",
  },
  toc: { title: "في هذه الصفحة" },
};
