import type { UIStringsOverride } from "../i18n-ui.ts";

/** Bulgarian (bg) UI strings. */
export const bg: UIStringsOverride = {
  actions: {
    addToCursor: "Добави в Cursor",
    addToVscode: "Добави във VS Code",
    askAboutCode: "Попитай за този код",
    connectMcp: "Свържи се с MCP",
    copied: "Копирано!",
    copyClaudeCode: "Копирай командата на Claude Code",
    copyCode: "Копирай кода",
    copyCodex: "Копирай командата на Codex",
    copyFailed: "Копирането не бе успешно",
    copyMarkdown: "Копирай като Markdown",
    copyServerUrl: "Копирай URL на сървъра",
    edit: "Редактирай в GitHub",
    export: "Експортирай",
    exportEpub: "Експортирай в EPUB",
    exportPdf: "Експортирай в PDF",
    generating: "Генериране…",
    openIn: "Отвори в {name}",
    openInChat: "Отвори в чата",
    openInChatPrompt:
      "Прочетете {url}, за да мога да задавам въпроси за тази страница.",
    scrollToTop: "Нагоре",
  },
  assistant: {
    ai: "ИИ",
    clear: "Изчисти разговора",
    close: "Затвори",
    copy: "Копирай разговора",
    empty: "Задайте въпрос за документацията.",
    error: "Съжаляваме, нещо се обърка.",
    explainCode: "Обясни този код.",
    label: "Задайте въпрос",
    open: "Отваряне на асистента",
    placeholder: "Задайте въпрос…",
    rateLimited:
      "Зададохте много въпроси. Опитайте отново след няколко минути.",
    removeCode: "Премахни кода",
    send: "Изпрати",
    support: "Свържете се с поддръжката",
    supportSubject: "Въпрос от документацията",
    tip: "Съвет: Можете да отваряте и затваряте чата с",
    title: "Асистент",
    verifyFailed: "Не успяхме да потвърдим, че сте човек. Опитайте отново.",
    you: "Вие",
  },
  banner: { dismiss: "Затваряне на съобщението" },
  changelog: {
    description: "Актуализации на продукта и бележки към изданията.",
    title: "Дневник на промените",
  },
  consent: {
    accept: "Приемам",
    decline: "Отказвам",
    label: "Съгласие за бисквитки",
    message:
      "Бихме искали да използваме бисквитки, за да разберем как се използва тази документация.",
    policy: "Политика за поверителност",
    settings: "Настройки за бисквитки",
  },
  content: {
    code: "Код",
    copyColor: "Копирай цвета {name} {value}",
    copyPrompt: "Копирай подканата",
    default: "По подразбиране",
    diagramError: "Тази диаграма не можа да бъде показана.",
    forks: "Разклонения",
    preview: "Преглед",
    prop: "Свойство",
    selectTab: "Избери раздел",
    selectView: "Избери изглед",
    showLess: "Покажи по-малко",
    showMore: "Покажи още",
    stars: "Звезди",
    tab: "Раздел {n}",
    type: "Тип",
    update: "Актуализация",
  },
  feedback: {
    comment: "Разкажете ни повече (по избор)",
    no: "Не",
    question: "Беше ли полезна тази страница?",
    send: "Изпрати",
    thanks: "Благодарим за обратната връзка!",
    yes: "Да",
  },
  languageSwitcher: { label: "Език", untranslated: "Непреведено" },
  narration: {
    cueDanger: "Опасност.",
    cueInfo: "Информация.",
    cueNote: "Бележка.",
    cueSection: "Разгъваем раздел.",
    cueStep: "Стъпка {n}.",
    cueSuccess: "Успех.",
    cueTab: "Раздел {title}.",
    cueTip: "Съвет.",
    cueWarning: "Предупреждение.",
    error: "Аудиоверсията не можа да бъде заредена.",
    follow: "Следи четенето",
    label: "Слушай тази страница",
    minutes: "{n} мин",
    next: "Следващо изречение",
    pause: "Пауза",
    play: "Пусни",
    previous: "Предишно изречение",
    progress: "Напредък на четенето",
    speed: "Скорост на възпроизвеждане",
    stop: "Спри слушането",
  },
  nav: {
    back: "Назад",
    breadcrumb: "Навигационна пътека",
    closeNavigation: "Затвори навигацията",
    deprecated: "остаряло",
    featured: "Препоръчано",
    githubRepository: "Хранилище в GitHub",
    navigation: "Навигация",
    opensInNewTab: "Отваря се в нов раздел",
    primary: "Основно",
    sections: "Раздели",
    toggleNavigation: "Превключи навигацията",
    toggleTheme: "Превключи цветовата тема",
  },
  notFound: {
    description: "Не успяхме да намерим страницата, която търсите.",
    home: "Обратно към началната страница",
    title: "Страницата не е намерена",
  },
  page: {
    lastUpdated: "Последна актуализация",
    next: "Напред",
    pagination: "Пагинация",
    previous: "Назад",
    related: "Свързани страници",
    skipToContent: "Към съдържанието",
  },
  search: {
    all: "Всички",
    allLanguages: "Всички езици",
    assistant: "Асистент",
    assistantHint: "Получете незабавен отговор от ИИ",
    button: "Търсене",
    devOnly: "Търсенето е достъпно в производствената компилация.",
    docs: "Документация",
    error: "Нещо се обърка. Моля, опитайте отново.",
    label: "Търсене в документацията",
    latest: "най-нова",
    navigate: "навигация",
    noResults: "Няма намерени резултати.",
    open: "отвори",
    placeholder: "Търсене в документацията…",
    popular: "Популярни",
    preview: "преглед",
    results: "Резултати",
  },
  toc: { title: "На тази страница" },
};
