import type { UIStringsOverride } from "../i18n-ui.ts";

/** Bengali (bn) UI strings. */
export const bn: UIStringsOverride = {
  actions: {
    addToCursor: "Cursor-এ যোগ করুন",
    addToVscode: "VS Code-এ যোগ করুন",
    askAboutCode: "এই কোড সম্পর্কে জিজ্ঞাসা করুন",
    connectMcp: "MCP-তে সংযোগ করুন",
    copied: "অনুলিপি করা হয়েছে!",
    copyClaudeCode: "Claude Code কমান্ড অনুলিপি করুন",
    copyCode: "কোড অনুলিপি করুন",
    copyCodex: "Codex কমান্ড অনুলিপি করুন",
    copyFailed: "অনুলিপি ব্যর্থ হয়েছে",
    copyMarkdown: "Markdown হিসেবে অনুলিপি করুন",
    copyServerUrl: "সার্ভার URL অনুলিপি করুন",
    edit: "GitHub-এ সম্পাদনা করুন",
    export: "এক্সপোর্ট করুন",
    exportEpub: "EPUB-এ এক্সপোর্ট করুন",
    exportPdf: "PDF-এ এক্সপোর্ট করুন",
    generating: "তৈরি হচ্ছে…",
    openIn: "{name}-এ খুলুন",
    openInChat: "চ্যাটে খুলুন",
    openInChatPrompt: "{url} পড়ুন, যাতে আমি এই পৃষ্ঠা সম্পর্কে প্রশ্ন করতে পারি।",
    scrollToTop: "উপরে যান",
  },
  assistant: {
    ai: "AI",
    clear: "কথোপকথন মুছুন",
    close: "বন্ধ করুন",
    copy: "কথোপকথন অনুলিপি করুন",
    empty: "ডকুমেন্টেশন সম্পর্কে একটি প্রশ্ন করুন।",
    error: "দুঃখিত, কিছু একটা ভুল হয়েছে।",
    explainCode: "এই কোডটি ব্যাখ্যা করুন।",
    label: "একটি প্রশ্ন করুন",
    open: "সহকারী খুলুন",
    placeholder: "একটি প্রশ্ন করুন…",
    rateLimited: "আপনি অনেক প্রশ্ন করেছেন। কয়েক মিনিট পরে আবার চেষ্টা করুন।",
    removeCode: "কোড সরান",
    send: "পাঠান",
    support: "সহায়তার সঙ্গে যোগাযোগ করুন",
    supportSubject: "ডকুমেন্টেশন থেকে প্রশ্ন",
    tip: "টিপ: চ্যাট খুলতে ও বন্ধ করতে চাপুন",
    title: "সহকারী",
    verifyFailed: "আপনি মানুষ কি না তা যাচাই করা যায়নি। আবার চেষ্টা করুন।",
    you: "আপনি",
  },
  banner: { dismiss: "ঘোষণা বন্ধ করুন" },
  changelog: {
    description: "পণ্য আপডেট এবং রিলিজ নোট।",
    title: "পরিবর্তন লগ",
  },
  consent: {
    accept: "গ্রহণ করুন",
    decline: "প্রত্যাখ্যান করুন",
    label: "কুকি সম্মতি",
    message: "এই ডকুমেন্টেশন কীভাবে ব্যবহার হয় তা বুঝতে আমরা কুকি ব্যবহার করতে চাই।",
    policy: "গোপনীয়তা নীতি",
    settings: "কুকি সেটিংস",
  },
  content: {
    code: "কোড",
    copyColor: "{name} রং {value} অনুলিপি করুন",
    copyPrompt: "প্রম্পট অনুলিপি করুন",
    default: "ডিফল্ট",
    diagramError: "এই ডায়াগ্রামটি রেন্ডার করা যায়নি।",
    forks: "ফর্ক",
    preview: "প্রিভিউ",
    prop: "প্রপ",
    selectTab: "ট্যাব নির্বাচন করুন",
    selectView: "ভিউ নির্বাচন করুন",
    showLess: "কম দেখান",
    showMore: "আরও দেখান",
    stars: "স্টার",
    tab: "ট্যাব {n}",
    type: "টাইপ",
    update: "আপডেট",
  },
  feedback: {
    comment: "আরও বলুন (ঐচ্ছিক)",
    no: "না",
    question: "এই পৃষ্ঠাটি কি সহায়ক ছিল?",
    send: "পাঠান",
    thanks: "আপনার মতামতের জন্য ধন্যবাদ!",
    yes: "হ্যাঁ",
  },
  languageSwitcher: { label: "ভাষা", untranslated: "অনূদিত নয়" },
  narration: {
    cueDanger: "বিপদ।",
    cueInfo: "তথ্য।",
    cueNote: "নোট।",
    cueSection: "প্রসারণযোগ্য অংশ।",
    cueStep: "ধাপ {n}।",
    cueSuccess: "সফল।",
    cueTab: "{title} ট্যাব।",
    cueTip: "টিপ।",
    cueWarning: "সতর্কতা।",
    error: "অডিও লোড করা যায়নি।",
    follow: "পাঠের সাথে থাকুন",
    label: "এই পৃষ্ঠাটি শুনুন",
    minutes: "{n} মিনিট",
    next: "পরবর্তী বাক্য",
    pause: "বিরতি",
    play: "চালান",
    previous: "পূর্ববর্তী বাক্য",
    progress: "পাঠের অগ্রগতি",
    speed: "প্লেব্যাকের গতি",
    stop: "শোনা বন্ধ করুন",
  },
  nav: {
    back: "ফিরে যান",
    breadcrumb: "ব্রেডক্রাম্ব",
    closeNavigation: "নেভিগেশন বন্ধ করুন",
    deprecated: "অপ্রচলিত",
    featured: "ফিচার্ড",
    githubRepository: "GitHub রিপোজিটরি",
    navigation: "নেভিগেশন",
    opensInNewTab: "নতুন ট্যাবে খোলে",
    primary: "প্রধান",
    sections: "বিভাগসমূহ",
    toggleNavigation: "নেভিগেশন টগল করুন",
    toggleTheme: "রঙের থিম টগল করুন",
  },
  notFound: {
    description: "আপনি যে পৃষ্ঠাটি খুঁজছেন তা আমরা খুঁজে পাইনি।",
    home: "হোমে ফিরে যান",
    title: "পৃষ্ঠা পাওয়া যায়নি",
  },
  page: {
    lastUpdated: "সর্বশেষ আপডেট",
    next: "পরবর্তী",
    pagination: "পেজিনেশন",
    previous: "পূর্ববর্তী",
    related: "সম্পর্কিত পৃষ্ঠা",
    skipToContent: "বিষয়বস্তুতে যান",
  },
  search: {
    all: "সব",
    allLanguages: "সব ভাষা",
    assistant: "সহকারী",
    assistantHint: "AI থেকে তাৎক্ষণিক উত্তর পান",
    button: "অনুসন্ধান",
    devOnly: "অনুসন্ধান প্রোডাকশন বিল্ডে উপলব্ধ।",
    docs: "ডকুমেন্টেশন",
    error: "কিছু একটা ভুল হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।",
    label: "ডকুমেন্টেশন অনুসন্ধান করুন",
    latest: "সর্বশেষ",
    navigate: "নেভিগেট",
    noResults: "কোনো ফলাফল পাওয়া যায়নি।",
    open: "খুলুন",
    placeholder: "ডকুমেন্টেশন অনুসন্ধান করুন…",
    popular: "জনপ্রিয়",
    preview: "প্রিভিউ",
    results: "ফলাফল",
  },
  toc: { title: "এই পৃষ্ঠায়" },
};
