import type { UIStringsOverride } from "../i18n-ui.ts";

/** Catalan (ca) UI strings. */
export const ca: UIStringsOverride = {
  actions: {
    addToCursor: "Afegeix a Cursor",
    addToVscode: "Afegeix a VS Code",
    askAboutCode: "Pregunta sobre aquest codi",
    connectMcp: "Connecta a MCP",
    copied: "Copiat!",
    copyClaudeCode: "Copia l'ordre de Claude Code",
    copyCode: "Copia el codi",
    copyCodex: "Copia l'ordre de Codex",
    copyFailed: "No s'ha pogut copiar",
    copyMarkdown: "Copia com a Markdown",
    copyServerUrl: "Copia l'URL del servidor",
    edit: "Edita a GitHub",
    export: "Exporta",
    exportEpub: "Exporta a EPUB",
    exportPdf: "Exporta a PDF",
    generating: "S'està generant…",
    openIn: "Obre a {name}",
    openInChat: "Obre al xat",
    openInChatPrompt:
      "Llegeix {url} perquè pugui fer-te preguntes sobre aquesta pàgina.",
    scrollToTop: "Torna a dalt",
  },
  assistant: {
    ai: "IA",
    clear: "Esborra la conversa",
    close: "Tanca",
    copy: "Copia la conversa",
    empty: "Fes una pregunta sobre la documentació.",
    error: "Ho sentim, alguna cosa ha anat malament.",
    explainCode: "Explica aquest codi.",
    label: "Fes una pregunta",
    open: "Obre l'assistent",
    placeholder: "Fes una pregunta…",
    rateLimited:
      "Has fet moltes preguntes. Torna-ho a provar d'aquí a uns minuts.",
    removeCode: "Treu el codi",
    send: "Envia",
    support: "Contacta amb el suport",
    supportSubject: "Pregunta des de la documentació",
    tip: "Consell: pots obrir i tancar el xat amb",
    title: "Assistent",
    verifyFailed:
      "No hem pogut comprovar que ets una persona. Torna-ho a provar.",
    you: "Tu",
  },
  banner: { dismiss: "Tanca l'anunci" },
  changelog: {
    description: "Actualitzacions del producte i notes de la versió.",
    title: "Registre de canvis",
  },
  consent: {
    accept: "Accepta",
    decline: "Rebutja",
    label: "Consentiment de galetes",
    message:
      "Ens agradaria utilitzar galetes per entendre com s'utilitza aquesta documentació.",
    policy: "Política de privadesa",
    settings: "Configuració de galetes",
  },
  content: {
    code: "Codi",
    copyColor: "Copia el color {name} {value}",
    copyPrompt: "Copia la indicació",
    default: "Per defecte",
    diagramError: "No s'ha pogut mostrar aquest diagrama.",
    forks: "Forks",
    preview: "Previsualització",
    prop: "Propietat",
    selectTab: "Selecciona una pestanya",
    selectView: "Selecciona una vista",
    showLess: "Mostra'n menys",
    showMore: "Mostra'n més",
    stars: "Estrelles",
    tab: "Pestanya {n}",
    type: "Tipus",
    update: "Actualització",
  },
  feedback: {
    comment: "Explica'ns-en més (opcional)",
    no: "No",
    question: "Aquesta pàgina t'ha estat útil?",
    send: "Envia",
    thanks: "Gràcies pels teus comentaris!",
    yes: "Sí",
  },
  languageSwitcher: { label: "Idioma", untranslated: "Sense traduir" },
  narration: {
    cueDanger: "Perill.",
    cueInfo: "Informació.",
    cueNote: "Nota.",
    cueSection: "Secció desplegable.",
    cueStep: "Pas {n}.",
    cueSuccess: "Èxit.",
    cueTab: "Pestanya {title}.",
    cueTip: "Consell.",
    cueWarning: "Advertència.",
    error: "No s'ha pogut carregar l'àudio.",
    follow: "Segueix la lectura",
    label: "Escolta aquesta pàgina",
    minutes: "{n} min",
    next: "Frase següent",
    pause: "Pausa",
    play: "Reprodueix",
    previous: "Frase anterior",
    progress: "Progrés de la narració",
    speed: "Velocitat de reproducció",
    stop: "Deixa d'escoltar",
  },
  nav: {
    back: "Enrere",
    breadcrumb: "Ruta de navegació",
    closeNavigation: "Tanca la navegació",
    deprecated: "obsolet",
    featured: "Destacat",
    githubRepository: "Repositori de GitHub",
    navigation: "Navegació",
    opensInNewTab: "S'obre en una pestanya nova",
    primary: "Principal",
    sections: "Seccions",
    toggleNavigation: "Mostra o amaga la navegació",
    toggleTheme: "Canvia el tema de color",
  },
  notFound: {
    description: "No hem pogut trobar la pàgina que cerques.",
    home: "Torna a l'inici",
    title: "Pàgina no trobada",
  },
  page: {
    lastUpdated: "Última actualització el",
    next: "Següent",
    pagination: "Paginació",
    previous: "Anterior",
    related: "Pàgines relacionades",
    skipToContent: "Vés al contingut",
  },
  search: {
    all: "Tots",
    allLanguages: "Tots els idiomes",
    assistant: "Assistent",
    assistantHint: "Obtén una resposta instantània de la IA",
    button: "Cerca",
    devOnly: "La cerca està disponible a la compilació de producció.",
    docs: "Documentació",
    error: "Alguna cosa ha anat malament. Torna-ho a provar.",
    label: "Cerca a la documentació",
    latest: "darrera",
    navigate: "navega",
    noResults: "No s'ha trobat cap resultat.",
    open: "obre",
    placeholder: "Cerca a la documentació…",
    popular: "Populars",
    preview: "previsualitza",
    results: "Resultats",
  },
  toc: { title: "En aquesta pàgina" },
};
