import type { UIStringsOverride } from "../i18n-ui.ts";

/** Czech (cs) UI strings. */
export const cs: UIStringsOverride = {
  actions: {
    addToCursor: "Přidat do Cursoru",
    addToVscode: "Přidat do VS Code",
    askAboutCode: "Zeptat se na tento kód",
    connectMcp: "Připojit k MCP",
    copied: "Zkopírováno!",
    copyClaudeCode: "Kopírovat příkaz Claude Code",
    copyCode: "Kopírovat kód",
    copyCodex: "Kopírovat příkaz Codex",
    copyFailed: "Kopírování se nezdařilo",
    copyMarkdown: "Kopírovat jako Markdown",
    copyServerUrl: "Kopírovat URL serveru",
    edit: "Upravit na GitHubu",
    export: "Exportovat",
    exportEpub: "Exportovat do EPUB",
    exportPdf: "Exportovat do PDF",
    generating: "Generování…",
    openIn: "Otevřít v {name}",
    openInChat: "Otevřít v chatu",
    openInChatPrompt: "Přečtěte si {url}, ať se mohu ptát na tuto stránku.",
    scrollToTop: "Zpět nahoru",
  },
  assistant: {
    ai: "AI",
    clear: "Vymazat konverzaci",
    close: "Zavřít",
    copy: "Kopírovat konverzaci",
    empty: "Zeptejte se na dokumentaci.",
    error: "Omlouváme se, něco se pokazilo.",
    explainCode: "Vysvětli tento kód.",
    label: "Položit otázku",
    placeholder: "Položit otázku…",
    rateLimited: "Položili jste hodně otázek. Zkuste to znovu za pár minut.",
    removeCode: "Odebrat kód",
    send: "Odeslat",
    support: "Kontaktovat podporu",
    supportSubject: "Dotaz z dokumentace",
    tip: "Tip: Chat můžete otevřít a zavřít pomocí",
    title: "Asistent",
    verifyFailed: "Nepodařilo se ověřit, že jste člověk. Zkuste to znovu.",
    you: "Vy",
  },
  banner: { dismiss: "Zavřít oznámení" },
  changelog: {
    description: "Novinky produktu a poznámky k vydání.",
    title: "Seznam změn",
  },
  consent: {
    accept: "Přijmout",
    decline: "Odmítnout",
    label: "Souhlas s cookies",
    message:
      "Rádi bychom používali soubory cookie, abychom pochopili, jak se tato dokumentace používá.",
    policy: "Zásady ochrany osobních údajů",
    settings: "Nastavení cookies",
  },
  content: {
    code: "Kód",
    copyColor: "Kopírovat barvu {name} {value}",
    copyPrompt: "Kopírovat prompt",
    default: "Výchozí",
    diagramError: "Tento diagram se nepodařilo vykreslit.",
    forks: "Forky",
    preview: "Náhled",
    prop: "Vlastnost",
    selectTab: "Vybrat kartu",
    selectView: "Vybrat zobrazení",
    showLess: "Zobrazit méně",
    showMore: "Zobrazit více",
    stars: "Hvězdy",
    tab: "Karta {n}",
    type: "Typ",
    update: "Aktualizace",
  },
  feedback: {
    comment: "Řekněte nám víc (nepovinné)",
    no: "Ne",
    question: "Byla tato stránka užitečná?",
    send: "Odeslat",
    thanks: "Děkujeme za zpětnou vazbu!",
    yes: "Ano",
  },
  languageSwitcher: { label: "Jazyk", untranslated: "Nepřeloženo" },
  narration: {
    cueDanger: "Nebezpečí.",
    cueInfo: "Informace.",
    cueNote: "Poznámka.",
    cueSection: "Rozbalovací sekce.",
    cueStep: "Krok {n}.",
    cueSuccess: "Úspěch.",
    cueTab: "Karta {title}.",
    cueTip: "Tip.",
    cueWarning: "Varování.",
    error: "Namluvenou verzi se nepodařilo načíst.",
    follow: "Sledovat čtení",
    label: "Poslechnout si tuto stránku",
    minutes: "{n} min",
    next: "Další věta",
    pause: "Pozastavit",
    play: "Přehrát",
    previous: "Předchozí věta",
    progress: "Průběh přehrávání",
    speed: "Rychlost přehrávání",
    stop: "Ukončit poslech",
  },
  nav: {
    back: "Zpět",
    breadcrumb: "Drobečková navigace",
    closeNavigation: "Zavřít navigaci",
    deprecated: "zastaralé",
    featured: "Doporučené",
    githubRepository: "Repozitář na GitHubu",
    navigation: "Navigace",
    opensInNewTab: "Otevře se na nové kartě",
    primary: "Hlavní",
    sections: "Sekce",
    toggleNavigation: "Přepnout navigaci",
    toggleTheme: "Přepnout barevný motiv",
  },
  notFound: {
    description: "Stránku, kterou hledáte, se nepodařilo najít.",
    home: "Zpět na úvodní stránku",
    title: "Stránka nenalezena",
  },
  page: {
    lastUpdated: "Naposledy aktualizováno",
    next: "Další",
    pagination: "Stránkování",
    previous: "Předchozí",
    related: "Související stránky",
    skipToContent: "Přejít k obsahu",
  },
  search: {
    all: "Vše",
    allLanguages: "Všechny jazyky",
    assistant: "Asistent",
    assistantHint: "Získejte okamžitou odpověď od AI",
    button: "Hledat",
    devOnly: "Vyhledávání je dostupné v produkčním buildu.",
    docs: "Dokumentace",
    error: "Něco se pokazilo. Zkuste to prosím znovu.",
    label: "Prohledat dokumentaci",
    latest: "nejnovější",
    navigate: "navigace",
    noResults: "Nebyly nalezeny žádné výsledky.",
    open: "otevřít",
    placeholder: "Prohledat dokumentaci…",
    popular: "Populární",
    preview: "náhled",
    results: "Výsledky",
  },
  toc: { title: "Na této stránce" },
};
