import type { UIStringsOverride } from "../i18n-ui.ts";

/** Danish (da) UI strings. */
export const da: UIStringsOverride = {
  actions: {
    addToCursor: "Føj til Cursor",
    addToVscode: "Føj til VS Code",
    askAboutCode: "Spørg om denne kode",
    connectMcp: "Opret forbindelse til MCP",
    copied: "Kopieret!",
    copyClaudeCode: "Kopiér Claude Code-kommando",
    copyCode: "Kopiér kode",
    copyCodex: "Kopiér Codex-kommando",
    copyFailed: "Kopiering mislykkedes",
    copyMarkdown: "Kopiér som Markdown",
    copyServerUrl: "Kopiér server-URL",
    edit: "Rediger på GitHub",
    export: "Eksportér",
    exportEpub: "Eksportér til EPUB",
    exportPdf: "Eksportér til PDF",
    generating: "Genererer…",
    openIn: "Åbn i {name}",
    openInChat: "Åbn i chat",
    openInChatPrompt: "Læs {url}, så jeg kan stille spørgsmål om denne side.",
    scrollToTop: "Tilbage til toppen",
  },
  assistant: {
    ai: "AI",
    clear: "Ryd samtalen",
    close: "Luk",
    copy: "Kopiér samtalen",
    empty: "Stil et spørgsmål om dokumentationen.",
    error: "Beklager, noget gik galt.",
    explainCode: "Forklar denne kode.",
    label: "Stil et spørgsmål",
    placeholder: "Stil et spørgsmål…",
    rateLimited:
      "Du har stillet mange spørgsmål. Prøv igen om et par minutter.",
    removeCode: "Fjern kode",
    send: "Send",
    support: "Kontakt support",
    supportSubject: "Spørgsmål fra dokumentationen",
    tip: "Tip: Du kan åbne og lukke chatten med",
    title: "Assistent",
    verifyFailed: "Vi kunne ikke bekræfte, at du er et menneske. Prøv igen.",
    you: "Du",
  },
  banner: { dismiss: "Luk meddelelsen" },
  changelog: {
    description: "Produktopdateringer og udgivelsesnoter.",
    title: "Ændringslog",
  },
  consent: {
    accept: "Accepter",
    decline: "Afvis",
    label: "Cookiesamtykke",
    message:
      "Vi vil gerne bruge cookies til at forstå, hvordan denne dokumentation bruges.",
    policy: "Privatlivspolitik",
    settings: "Cookieindstillinger",
  },
  content: {
    code: "Kode",
    copyColor: "Kopiér farven {name} {value}",
    copyPrompt: "Kopiér prompt",
    default: "Standard",
    diagramError: "Dette diagram kunne ikke vises.",
    forks: "Forks",
    preview: "Forhåndsvisning",
    prop: "Egenskab",
    selectTab: "Vælg fane",
    selectView: "Vælg visning",
    showLess: "Vis mindre",
    showMore: "Vis mere",
    stars: "Stjerner",
    tab: "Fane {n}",
    type: "Type",
    update: "Opdatering",
  },
  feedback: {
    comment: "Fortæl os mere (valgfrit)",
    no: "Nej",
    question: "Var denne side nyttig?",
    send: "Send",
    thanks: "Tak for din feedback!",
    yes: "Ja",
  },
  languageSwitcher: { label: "Sprog", untranslated: "Ikke oversat" },
  narration: {
    cueDanger: "Fare.",
    cueInfo: "Info.",
    cueNote: "Bemærk.",
    cueSection: "Udvidelig sektion.",
    cueStep: "Trin {n}.",
    cueSuccess: "Fuldført.",
    cueTab: "Fanen {title}.",
    cueTip: "Tip.",
    cueWarning: "Advarsel.",
    error: "Oplæsningen kunne ikke indlæses.",
    follow: "Følg med",
    label: "Lyt til denne side",
    minutes: "{n} min.",
    next: "Næste sætning",
    pause: "Pause",
    play: "Afspil",
    previous: "Forrige sætning",
    progress: "Fremdrift i oplæsningen",
    speed: "Afspilningshastighed",
    stop: "Stop oplæsningen",
  },
  nav: {
    back: "Tilbage",
    breadcrumb: "Brødkrummesti",
    closeNavigation: "Luk navigationen",
    deprecated: "forældet",
    featured: "Udvalgt",
    githubRepository: "GitHub-repositorium",
    navigation: "Navigation",
    opensInNewTab: "Åbner i en ny fane",
    primary: "Primær",
    sections: "Sektioner",
    toggleNavigation: "Vis eller skjul navigationen",
    toggleTheme: "Skift farvetema",
  },
  notFound: {
    description: "Vi kunne ikke finde den side, du leder efter.",
    home: "Tilbage til forsiden",
    title: "Siden blev ikke fundet",
  },
  page: {
    lastUpdated: "Senest opdateret den",
    next: "Næste",
    pagination: "Paginering",
    previous: "Forrige",
    related: "Relaterede sider",
    skipToContent: "Spring til indhold",
  },
  search: {
    all: "Alle",
    allLanguages: "Alle sprog",
    assistant: "Assistent",
    assistantHint: "Få et øjeblikkeligt svar fra AI",
    button: "Søg",
    devOnly: "Søgning er tilgængelig i produktionsbygningen.",
    docs: "Dokumentation",
    error: "Noget gik galt. Prøv igen.",
    label: "Søg i dokumentationen",
    latest: "nyeste",
    navigate: "navigér",
    noResults: "Ingen resultater fundet.",
    open: "åbn",
    placeholder: "Søg i dokumentationen…",
    popular: "Populært",
    preview: "forhåndsvis",
    results: "Resultater",
  },
  toc: { title: "På denne side" },
};
