import type { UIStringsOverride } from "../i18n-ui.ts";

/** German (de) UI strings. */
export const de: UIStringsOverride = {
  actions: {
    addToCursor: "Zu Cursor hinzufügen",
    addToVscode: "Zu VS Code hinzufügen",
    askAboutCode: "Zu diesem Code fragen",
    connectMcp: "Mit MCP verbinden",
    copied: "Kopiert!",
    copyClaudeCode: "Claude-Code-Befehl kopieren",
    copyCode: "Code kopieren",
    copyCodex: "Codex-Befehl kopieren",
    copyFailed: "Kopieren fehlgeschlagen",
    copyMarkdown: "Als Markdown kopieren",
    copyServerUrl: "Server-URL kopieren",
    edit: "Auf GitHub bearbeiten",
    export: "Exportieren",
    exportEpub: "Als EPUB exportieren",
    exportPdf: "Als PDF exportieren",
    generating: "Wird generiert…",
    openIn: "In {name} öffnen",
    openInChat: "Im Chat öffnen",
    openInChatPrompt:
      "Lies {url}, damit ich dir Fragen zu dieser Seite stellen kann.",
    scrollToTop: "Nach oben scrollen",
  },
  assistant: {
    ai: "KI",
    clear: "Unterhaltung löschen",
    close: "Schließen",
    copy: "Unterhaltung kopieren",
    empty: "Stelle eine Frage zur Dokumentation.",
    error: "Entschuldigung, etwas ist schiefgelaufen.",
    explainCode: "Erkläre diesen Code.",
    label: "Eine Frage stellen",
    open: "Assistenten öffnen",
    placeholder: "Eine Frage stellen…",
    rateLimited:
      "Du hast viele Fragen gestellt. Versuch es in ein paar Minuten noch einmal.",
    removeCode: "Code entfernen",
    send: "Senden",
    support: "Support kontaktieren",
    supportSubject: "Frage aus der Dokumentation",
    tip: "Tipp: Du kannst den Chat öffnen und schließen mit",
    title: "Assistent",
    verifyFailed:
      "Wir konnten nicht bestätigen, dass du ein Mensch bist. Versuch es noch einmal.",
    you: "Du",
  },
  banner: { dismiss: "Ankündigung schließen" },
  changelog: {
    description: "Produkt-Updates und Versionshinweise.",
    title: "Änderungsprotokoll",
  },
  consent: {
    accept: "Akzeptieren",
    decline: "Ablehnen",
    label: "Cookie-Einwilligung",
    message:
      "Wir würden gern Cookies verwenden, um zu verstehen, wie diese Dokumentation genutzt wird.",
    policy: "Datenschutzerklärung",
    settings: "Cookie-Einstellungen",
  },
  content: {
    code: "Code",
    copyColor: "Farbe {name} {value} kopieren",
    copyPrompt: "Prompt kopieren",
    default: "Standard",
    diagramError: "Dieses Diagramm konnte nicht dargestellt werden.",
    forks: "Forks",
    preview: "Vorschau",
    prop: "Eigenschaft",
    selectTab: "Tab auswählen",
    selectView: "Ansicht auswählen",
    showLess: "Weniger anzeigen",
    showMore: "Mehr anzeigen",
    stars: "Sterne",
    tab: "Tab {n}",
    type: "Typ",
    update: "Update",
  },
  feedback: {
    comment: "Erzähl uns mehr (optional)",
    no: "Nein",
    question: "War diese Seite hilfreich?",
    send: "Senden",
    thanks: "Danke für dein Feedback!",
    yes: "Ja",
  },
  languageSwitcher: { label: "Sprache", untranslated: "Nicht übersetzt" },
  narration: {
    cueDanger: "Gefahr.",
    cueInfo: "Info.",
    cueNote: "Hinweis.",
    cueSection: "Ausklappbarer Abschnitt.",
    cueStep: "Schritt {n}.",
    cueSuccess: "Erfolg.",
    cueTab: "Tab {title}.",
    cueTip: "Tipp.",
    cueWarning: "Warnung.",
    error: "Die Vorlesefunktion konnte nicht geladen werden.",
    follow: "Mitlesen",
    label: "Diese Seite anhören",
    minutes: "{n} Min.",
    next: "Nächster Satz",
    pause: "Pausieren",
    play: "Abspielen",
    previous: "Vorheriger Satz",
    progress: "Vorlesefortschritt",
    speed: "Wiedergabegeschwindigkeit",
    stop: "Vorlesen beenden",
  },
  nav: {
    back: "Zurück",
    breadcrumb: "Brotkrümelnavigation",
    closeNavigation: "Navigation schließen",
    deprecated: "veraltet",
    featured: "Empfohlen",
    githubRepository: "GitHub-Repository",
    navigation: "Navigation",
    opensInNewTab: "Öffnet sich in einem neuen Tab",
    primary: "Primär",
    sections: "Abschnitte",
    toggleNavigation: "Navigation umschalten",
    toggleTheme: "Farbschema umschalten",
  },
  notFound: {
    description: "Wir konnten die gesuchte Seite nicht finden.",
    home: "Zurück zur Startseite",
    title: "Seite nicht gefunden",
  },
  page: {
    lastUpdated: "Zuletzt aktualisiert am",
    next: "Weiter",
    pagination: "Seitennummerierung",
    previous: "Zurück",
    related: "Verwandte Seiten",
    skipToContent: "Zum Inhalt springen",
  },
  search: {
    all: "Alle",
    allLanguages: "Alle Sprachen",
    assistant: "Assistent",
    assistantHint: "Erhalte sofort eine Antwort von der KI",
    button: "Suchen",
    devOnly: "Die Suche ist im Produktions-Build verfügbar.",
    docs: "Dokumentation",
    error: "Etwas ist schiefgelaufen. Bitte versuche es erneut.",
    label: "Dokumentation durchsuchen",
    latest: "neueste",
    navigate: "navigieren",
    noResults: "Keine Ergebnisse gefunden.",
    open: "öffnen",
    placeholder: "Dokumentation durchsuchen…",
    popular: "Beliebt",
    preview: "vorschau",
    results: "Ergebnisse",
  },
  toc: { title: "Auf dieser Seite" },
};
