import type { UIStringsOverride } from "../i18n-ui.ts";

/** Greek (el) UI strings. */
export const el: UIStringsOverride = {
  actions: {
    addToCursor: "Προσθήκη στο Cursor",
    addToVscode: "Προσθήκη στο VS Code",
    askAboutCode: "Ρωτήστε για αυτόν τον κώδικα",
    connectMcp: "Σύνδεση με MCP",
    copied: "Αντιγράφηκε!",
    copyClaudeCode: "Αντιγραφή εντολής Claude Code",
    copyCode: "Αντιγραφή κώδικα",
    copyCodex: "Αντιγραφή εντολής Codex",
    copyFailed: "Η αντιγραφή απέτυχε",
    copyMarkdown: "Αντιγραφή ως Markdown",
    copyServerUrl: "Αντιγραφή URL διακομιστή",
    edit: "Επεξεργασία στο GitHub",
    export: "Εξαγωγή",
    exportEpub: "Εξαγωγή σε EPUB",
    exportPdf: "Εξαγωγή σε PDF",
    generating: "Δημιουργία…",
    openIn: "Άνοιγμα στο {name}",
    openInChat: "Άνοιγμα στη συνομιλία",
    openInChatPrompt:
      "Διαβάστε το {url} για να μπορώ να κάνω ερωτήσεις για αυτή τη σελίδα.",
    scrollToTop: "Επιστροφή στην κορυφή",
  },
  assistant: {
    ai: "AI",
    clear: "Εκκαθάριση συνομιλίας",
    close: "Κλείσιμο",
    copy: "Αντιγραφή συνομιλίας",
    empty: "Κάντε μια ερώτηση σχετικά με την τεκμηρίωση.",
    error: "Λυπούμαστε, κάτι πήγε στραβά.",
    explainCode: "Εξήγησε αυτόν τον κώδικα.",
    label: "Κάντε μια ερώτηση",
    placeholder: "Κάντε μια ερώτηση…",
    rateLimited: "Κάνατε πολλές ερωτήσεις. Δοκιμάστε ξανά σε λίγα λεπτά.",
    removeCode: "Αφαίρεση κώδικα",
    send: "Αποστολή",
    support: "Επικοινωνία με την υποστήριξη",
    supportSubject: "Ερώτηση από την τεκμηρίωση",
    tip: "Συμβουλή: Μπορείτε να ανοίγετε και να κλείνετε τη συνομιλία με",
    title: "Βοηθός",
    verifyFailed:
      "Δεν ήταν δυνατό να επιβεβαιωθεί ότι είστε άνθρωπος. Δοκιμάστε ξανά.",
    you: "Εσείς",
  },
  banner: { dismiss: "Κλείσιμο ανακοίνωσης" },
  changelog: {
    description: "Ενημερώσεις προϊόντος και σημειώσεις έκδοσης.",
    title: "Ιστορικό αλλαγών",
  },
  consent: {
    accept: "Αποδοχή",
    decline: "Απόρριψη",
    label: "Συναίνεση για cookies",
    message:
      "Θα θέλαμε να χρησιμοποιούμε cookies για να κατανοήσουμε πώς χρησιμοποιείται αυτή η τεκμηρίωση.",
    policy: "Πολιτική απορρήτου",
    settings: "Ρυθμίσεις cookies",
  },
  content: {
    code: "Κώδικας",
    copyColor: "Αντιγραφή χρώματος {name} {value}",
    copyPrompt: "Αντιγραφή προτροπής",
    default: "Προεπιλογή",
    diagramError: "Δεν ήταν δυνατή η απόδοση αυτού του διαγράμματος.",
    forks: "Forks",
    preview: "Προεπισκόπηση",
    prop: "Ιδιότητα",
    selectTab: "Επιλογή καρτέλας",
    selectView: "Επιλογή προβολής",
    showLess: "Εμφάνιση λιγότερων",
    showMore: "Εμφάνιση περισσότερων",
    stars: "Αστέρια",
    tab: "Καρτέλα {n}",
    type: "Τύπος",
    update: "Ενημέρωση",
  },
  feedback: {
    comment: "Πείτε μας περισσότερα (προαιρετικό)",
    no: "Όχι",
    question: "Σας φάνηκε χρήσιμη αυτή η σελίδα;",
    send: "Αποστολή",
    thanks: "Ευχαριστούμε για τα σχόλιά σας!",
    yes: "Ναι",
  },
  languageSwitcher: { label: "Γλώσσα", untranslated: "Δεν έχει μεταφραστεί" },
  narration: {
    cueDanger: "Κίνδυνος.",
    cueInfo: "Πληροφορία.",
    cueNote: "Σημείωση.",
    cueSection: "Αναπτυσσόμενη ενότητα.",
    cueStep: "Βήμα {n}.",
    cueSuccess: "Επιτυχία.",
    cueTab: "Καρτέλα {title}.",
    cueTip: "Συμβουλή.",
    cueWarning: "Προειδοποίηση.",
    error: "Δεν ήταν δυνατή η φόρτωση της αφήγησης.",
    follow: "Παρακολούθηση ανάγνωσης",
    label: "Ακρόαση αυτής της σελίδας",
    minutes: "{n} λεπ.",
    next: "Επόμενη πρόταση",
    pause: "Παύση",
    play: "Αναπαραγωγή",
    previous: "Προηγούμενη πρόταση",
    progress: "Πρόοδος αφήγησης",
    speed: "Ταχύτητα αναπαραγωγής",
    stop: "Διακοπή ακρόασης",
  },
  nav: {
    back: "Πίσω",
    breadcrumb: "Διαδρομή πλοήγησης",
    closeNavigation: "Κλείσιμο πλοήγησης",
    deprecated: "παρωχημένο",
    featured: "Προτεινόμενα",
    githubRepository: "Αποθετήριο GitHub",
    navigation: "Πλοήγηση",
    opensInNewTab: "Ανοίγει σε νέα καρτέλα",
    primary: "Κύρια",
    sections: "Ενότητες",
    toggleNavigation: "Εναλλαγή πλοήγησης",
    toggleTheme: "Εναλλαγή χρωματικού θέματος",
  },
  notFound: {
    description: "Δεν μπορέσαμε να βρούμε τη σελίδα που ψάχνετε.",
    home: "Επιστροφή στην αρχική",
    title: "Η σελίδα δεν βρέθηκε",
  },
  page: {
    lastUpdated: "Τελευταία ενημέρωση",
    next: "Επόμενο",
    pagination: "Σελιδοποίηση",
    previous: "Προηγούμενο",
    related: "Σχετικές σελίδες",
    skipToContent: "Μετάβαση στο περιεχόμενο",
  },
  search: {
    all: "Όλα",
    allLanguages: "Όλες οι γλώσσες",
    assistant: "Βοηθός",
    assistantHint: "Λάβετε άμεση απάντηση από την AI",
    button: "Αναζήτηση",
    devOnly: "Η αναζήτηση είναι διαθέσιμη στην έκδοση παραγωγής.",
    docs: "Τεκμηρίωση",
    error: "Κάτι πήγε στραβά. Δοκιμάστε ξανά.",
    label: "Αναζήτηση στην τεκμηρίωση",
    latest: "τελευταία",
    navigate: "πλοήγηση",
    noResults: "Δεν βρέθηκαν αποτελέσματα.",
    open: "άνοιγμα",
    placeholder: "Αναζήτηση στην τεκμηρίωση…",
    popular: "Δημοφιλή",
    preview: "προεπισκόπηση",
    results: "Αποτελέσματα",
  },
  toc: { title: "Σε αυτή τη σελίδα" },
};
