import type { UIStringsOverride } from "../i18n-ui.ts";

/** Spanish (es) UI strings. */
export const es: UIStringsOverride = {
  actions: {
    addToCursor: "Añadir a Cursor",
    addToVscode: "Añadir a VS Code",
    askAboutCode: "Preguntar sobre este código",
    connectMcp: "Conectar a MCP",
    copied: "¡Copiado!",
    copyClaudeCode: "Copiar comando de Claude Code",
    copyCode: "Copiar código",
    copyCodex: "Copiar comando de Codex",
    copyFailed: "Error al copiar",
    copyMarkdown: "Copiar como Markdown",
    copyServerUrl: "Copiar URL del servidor",
    edit: "Editar en GitHub",
    export: "Exportar",
    exportEpub: "Exportar a EPUB",
    exportPdf: "Exportar a PDF",
    generating: "Generando…",
    openIn: "Abrir en {name}",
    openInChat: "Abrir en el chat",
    openInChatPrompt:
      "Lee {url} para que pueda hacerte preguntas sobre esta página.",
    scrollToTop: "Volver arriba",
  },
  assistant: {
    ai: "IA",
    clear: "Borrar la conversación",
    close: "Cerrar",
    copy: "Copiar la conversación",
    empty: "Haz una pregunta sobre la documentación.",
    error: "Lo sentimos, algo salió mal.",
    explainCode: "Explica este código.",
    label: "Haz una pregunta",
    open: "Abrir asistente",
    placeholder: "Haz una pregunta…",
    rateLimited:
      "Has hecho muchas preguntas. Vuelve a intentarlo en unos minutos.",
    removeCode: "Quitar código",
    send: "Enviar",
    support: "Contactar con soporte",
    supportSubject: "Pregunta desde la documentación",
    tip: "Consejo: puedes abrir y cerrar el chat con",
    title: "Asistente",
    verifyFailed:
      "No pudimos comprobar que eres una persona. Vuelve a intentarlo.",
    you: "Tú",
  },
  banner: { dismiss: "Cerrar el anuncio" },
  changelog: {
    description: "Novedades del producto y notas de la versión.",
    title: "Registro de cambios",
  },
  consent: {
    accept: "Aceptar",
    decline: "Rechazar",
    label: "Consentimiento de cookies",
    message:
      "Nos gustaría usar cookies para entender cómo se usa esta documentación.",
    policy: "Política de privacidad",
    settings: "Configuración de cookies",
  },
  content: {
    code: "Código",
    copyColor: "Copiar el color {name} {value}",
    copyPrompt: "Copiar prompt",
    default: "Predeterminado",
    diagramError: "No se pudo mostrar este diagrama.",
    forks: "Forks",
    preview: "Vista previa",
    prop: "Propiedad",
    selectTab: "Seleccionar pestaña",
    selectView: "Seleccionar vista",
    showLess: "Mostrar menos",
    showMore: "Mostrar más",
    stars: "Estrellas",
    tab: "Pestaña {n}",
    type: "Tipo",
    update: "Actualización",
  },
  feedback: {
    comment: "Cuéntanos más (opcional)",
    no: "No",
    question: "¿Te ha resultado útil esta página?",
    send: "Enviar",
    thanks: "¡Gracias por tus comentarios!",
    yes: "Sí",
  },
  languageSwitcher: { label: "Idioma", untranslated: "Sin traducir" },
  narration: {
    cueDanger: "Peligro.",
    cueInfo: "Información.",
    cueNote: "Nota.",
    cueSection: "Sección desplegable.",
    cueStep: "Paso {n}.",
    cueSuccess: "Éxito.",
    cueTab: "Pestaña {title}.",
    cueTip: "Consejo.",
    cueWarning: "Advertencia.",
    error: "No se pudo cargar el audio.",
    follow: "Seguir la lectura",
    label: "Escuchar esta página",
    minutes: "{n} min",
    next: "Frase siguiente",
    pause: "Pausar",
    play: "Reproducir",
    previous: "Frase anterior",
    progress: "Progreso de la narración",
    speed: "Velocidad de reproducción",
    stop: "Dejar de escuchar",
  },
  nav: {
    back: "Atrás",
    breadcrumb: "Ruta de navegación",
    closeNavigation: "Cerrar la navegación",
    deprecated: "obsoleto",
    featured: "Destacado",
    githubRepository: "Repositorio de GitHub",
    navigation: "Navegación",
    opensInNewTab: "Se abre en una pestaña nueva",
    primary: "Principal",
    sections: "Secciones",
    toggleNavigation: "Mostrar u ocultar la navegación",
    toggleTheme: "Cambiar el tema de color",
  },
  notFound: {
    description: "No hemos podido encontrar la página que buscas.",
    home: "Volver al inicio",
    title: "Página no encontrada",
  },
  page: {
    lastUpdated: "Última actualización el",
    next: "Siguiente",
    pagination: "Paginación",
    previous: "Anterior",
    related: "Páginas relacionadas",
    skipToContent: "Saltar al contenido",
  },
  search: {
    all: "Todos",
    allLanguages: "Todos los idiomas",
    assistant: "Asistente",
    assistantHint: "Obtén una respuesta instantánea de la IA",
    button: "Buscar",
    devOnly: "La búsqueda está disponible en la compilación de producción.",
    docs: "Documentación",
    error: "Algo salió mal. Inténtalo de nuevo.",
    label: "Buscar en la documentación",
    latest: "más reciente",
    navigate: "navegar",
    noResults: "No se encontraron resultados.",
    open: "abrir",
    placeholder: "Buscar en la documentación…",
    popular: "Populares",
    preview: "vista previa",
    results: "Resultados",
  },
  toc: { title: "En esta página" },
};
