import type { UIStringsOverride } from "../i18n-ui.ts";

/** Persian (fa) UI strings. */
export const fa: UIStringsOverride = {
  actions: {
    addToCursor: "افزودن به Cursor",
    addToVscode: "افزودن به VS Code",
    askAboutCode: "درباره این کد بپرسید",
    connectMcp: "اتصال به MCP",
    copied: "کپی شد!",
    copyClaudeCode: "کپی دستور Claude Code",
    copyCode: "کپی کد",
    copyCodex: "کپی دستور Codex",
    copyFailed: "کپی ناموفق بود",
    copyMarkdown: "کپی به‌صورت Markdown",
    copyServerUrl: "کپی نشانی سرور",
    edit: "ویرایش در GitHub",
    export: "برون‌بری",
    exportEpub: "برون‌بری به EPUB",
    exportPdf: "برون‌بری به PDF",
    generating: "در حال تولید…",
    openIn: "باز کردن در {name}",
    openInChat: "باز کردن در گفتگو",
    openInChatPrompt: "{url} را بخوانید تا بتوانم درباره این صفحه سؤال بپرسم.",
    scrollToTop: "بازگشت به بالا",
  },
  assistant: {
    ai: "هوش مصنوعی",
    clear: "پاک کردن گفتگو",
    close: "بستن",
    copy: "کپی گفتگو",
    empty: "سؤالی درباره مستندات بپرسید.",
    error: "متأسفیم، مشکلی پیش آمد.",
    explainCode: "این کد را توضیح بده.",
    label: "یک سؤال بپرسید",
    open: "باز کردن دستیار",
    placeholder: "یک سؤال بپرسید…",
    rateLimited: "سؤال‌های زیادی پرسیده‌اید. چند دقیقه دیگر دوباره امتحان کنید.",
    removeCode: "حذف کد",
    send: "ارسال",
    support: "تماس با پشتیبانی",
    supportSubject: "پرسشی از مستندات",
    tip: "نکته: باز و بسته کردن گفتگو با",
    title: "دستیار",
    verifyFailed:
      "نتوانستیم تأیید کنیم که شما انسان هستید. دوباره امتحان کنید.",
    you: "شما",
  },
  banner: { dismiss: "بستن اطلاعیه" },
  changelog: {
    description: "به‌روزرسانی‌های محصول و یادداشت‌های انتشار.",
    title: "گزارش تغییرات",
  },
  consent: {
    accept: "پذیرفتن",
    decline: "رد کردن",
    label: "رضایت کوکی",
    message:
      "مایلیم از کوکی‌ها استفاده کنیم تا بفهمیم این مستندات چگونه استفاده می‌شود.",
    policy: "سیاست حریم خصوصی",
    settings: "تنظیمات کوکی",
  },
  content: {
    code: "کد",
    copyColor: "کپی رنگ {name} {value}",
    copyPrompt: "کپی پرامپت",
    default: "پیش‌فرض",
    diagramError: "نمایش این نمودار ممکن نشد.",
    forks: "فورک‌ها",
    preview: "پیش‌نمایش",
    prop: "ویژگی",
    selectTab: "انتخاب زبانه",
    selectView: "انتخاب نما",
    showLess: "نمایش کمتر",
    showMore: "نمایش بیشتر",
    stars: "ستاره‌ها",
    tab: "زبانه {n}",
    type: "نوع",
    update: "به‌روزرسانی",
  },
  feedback: {
    comment: "بیشتر بگویید (اختیاری)",
    no: "خیر",
    question: "آیا این صفحه مفید بود؟",
    send: "ارسال",
    thanks: "از بازخورد شما سپاسگزاریم!",
    yes: "بله",
  },
  languageSwitcher: { label: "زبان", untranslated: "ترجمه‌نشده" },
  narration: {
    cueDanger: "خطر.",
    cueInfo: "اطلاعات.",
    cueNote: "یادداشت.",
    cueSection: "بخش بازشونده.",
    cueStep: "گام {n}.",
    cueSuccess: "موفقیت.",
    cueTab: "زبانه {title}.",
    cueTip: "نکته.",
    cueWarning: "هشدار.",
    error: "بارگیری نسخه صوتی ممکن نشد.",
    follow: "دنبال کردن خوانش",
    label: "به این صفحه گوش دهید",
    minutes: "{n} دقیقه",
    next: "جمله بعدی",
    pause: "مکث",
    play: "پخش",
    previous: "جمله قبلی",
    progress: "پیشرفت خوانش",
    speed: "سرعت پخش",
    stop: "توقف گوش دادن",
  },
  nav: {
    back: "بازگشت",
    breadcrumb: "مسیر ناوبری",
    closeNavigation: "بستن ناوبری",
    deprecated: "منسوخ",
    featured: "ویژه",
    githubRepository: "مخزن GitHub",
    navigation: "ناوبری",
    opensInNewTab: "در زبانه‌ای جدید باز می‌شود",
    primary: "اصلی",
    sections: "بخش‌ها",
    toggleNavigation: "تغییر وضعیت ناوبری",
    toggleTheme: "تغییر پوسته رنگی",
  },
  notFound: {
    description: "صفحه‌ای که به دنبال آن هستید پیدا نشد.",
    home: "بازگشت به صفحه اصلی",
    title: "صفحه پیدا نشد",
  },
  page: {
    lastUpdated: "آخرین به‌روزرسانی",
    next: "بعدی",
    pagination: "صفحه‌بندی",
    previous: "قبلی",
    related: "صفحه‌های مرتبط",
    skipToContent: "پرش به محتوا",
  },
  search: {
    all: "همه",
    allLanguages: "همه زبان‌ها",
    assistant: "دستیار",
    assistantHint: "پاسخی فوری از هوش مصنوعی دریافت کنید",
    button: "جستجو",
    devOnly: "جستجو در نسخه تولید در دسترس است.",
    docs: "مستندات",
    error: "مشکلی پیش آمد. لطفاً دوباره تلاش کنید.",
    label: "جستجو در مستندات",
    latest: "جدیدترین",
    navigate: "پیمایش",
    noResults: "نتیجه‌ای یافت نشد.",
    open: "باز کردن",
    placeholder: "جستجو در مستندات…",
    popular: "محبوب",
    preview: "پیش‌نمایش",
    results: "نتایج",
  },
  toc: { title: "در این صفحه" },
};
