import type { UIStringsOverride } from "../i18n-ui.ts";

/** Finnish (fi) UI strings. */
export const fi: UIStringsOverride = {
  actions: {
    addToCursor: "Lisää Cursoriin",
    addToVscode: "Lisää VS Codeen",
    askAboutCode: "Kysy tästä koodista",
    connectMcp: "Yhdistä MCP:hen",
    copied: "Kopioitu!",
    copyClaudeCode: "Kopioi Claude Code -komento",
    copyCode: "Kopioi koodi",
    copyCodex: "Kopioi Codex-komento",
    copyFailed: "Kopiointi epäonnistui",
    copyMarkdown: "Kopioi Markdownina",
    copyServerUrl: "Kopioi palvelimen URL",
    edit: "Muokkaa GitHubissa",
    export: "Vie",
    exportEpub: "Vie EPUB-muotoon",
    exportPdf: "Vie PDF-muotoon",
    generating: "Luodaan…",
    openIn: "Avaa sovelluksessa {name}",
    openInChat: "Avaa keskustelussa",
    openInChatPrompt: "Lue {url}, jotta voin kysyä kysymyksiä tästä sivusta.",
    scrollToTop: "Takaisin ylös",
  },
  assistant: {
    ai: "Tekoäly",
    clear: "Tyhjennä keskustelu",
    close: "Sulje",
    copy: "Kopioi keskustelu",
    empty: "Kysy kysymys dokumentaatiosta.",
    error: "Pahoittelut, jokin meni pieleen.",
    explainCode: "Selitä tämä koodi.",
    label: "Kysy kysymys",
    open: "Avaa avustaja",
    placeholder: "Kysy kysymys…",
    rateLimited:
      "Olet esittänyt paljon kysymyksiä. Yritä uudelleen muutaman minuutin kuluttua.",
    removeCode: "Poista koodi",
    send: "Lähetä",
    support: "Ota yhteyttä tukeen",
    supportSubject: "Kysymys dokumentaatiosta",
    tip: "Vinkki: Voit avata ja sulkea keskustelun näppäimillä",
    title: "Avustaja",
    verifyFailed: "Emme voineet varmistaa, että olet ihminen. Yritä uudelleen.",
    you: "Sinä",
  },
  banner: { dismiss: "Sulje ilmoitus" },
  changelog: {
    description: "Tuotepäivitykset ja julkaisutiedot.",
    title: "Muutosloki",
  },
  consent: {
    accept: "Hyväksy",
    decline: "Hylkää",
    label: "Evästeiden hyväksyntä",
    message:
      "Haluaisimme käyttää evästeitä ymmärtääksemme, miten tätä dokumentaatiota käytetään.",
    policy: "Tietosuojakäytäntö",
    settings: "Evästeasetukset",
  },
  content: {
    code: "Koodi",
    copyColor: "Kopioi väri {name} {value}",
    copyPrompt: "Kopioi kehote",
    default: "Oletus",
    diagramError: "Tätä kaaviota ei voitu näyttää.",
    forks: "Haarat",
    preview: "Esikatselu",
    prop: "Ominaisuus",
    selectTab: "Valitse välilehti",
    selectView: "Valitse näkymä",
    showLess: "Näytä vähemmän",
    showMore: "Näytä lisää",
    stars: "Tähdet",
    tab: "Välilehti {n}",
    type: "Tyyppi",
    update: "Päivitys",
  },
  feedback: {
    comment: "Kerro lisää (valinnainen)",
    no: "Ei",
    question: "Oliko tästä sivusta apua?",
    send: "Lähetä",
    thanks: "Kiitos palautteestasi!",
    yes: "Kyllä",
  },
  languageSwitcher: { label: "Kieli", untranslated: "Ei käännetty" },
  narration: {
    cueDanger: "Vaara.",
    cueInfo: "Tietoa.",
    cueNote: "Huomautus.",
    cueSection: "Laajennettava osio.",
    cueStep: "Vaihe {n}.",
    cueSuccess: "Onnistui.",
    cueTab: "Välilehti {title}.",
    cueTip: "Vinkki.",
    cueWarning: "Varoitus.",
    error: "Ääniversiota ei voitu ladata.",
    follow: "Seuraa tekstiä",
    label: "Kuuntele tämä sivu",
    minutes: "{n} min",
    next: "Seuraava virke",
    pause: "Tauko",
    play: "Toista",
    previous: "Edellinen virke",
    progress: "Toiston edistyminen",
    speed: "Toistonopeus",
    stop: "Lopeta kuuntelu",
  },
  nav: {
    back: "Takaisin",
    breadcrumb: "Murupolku",
    closeNavigation: "Sulje navigaatio",
    deprecated: "vanhentunut",
    featured: "Suositellut",
    githubRepository: "GitHub-repositorio",
    navigation: "Navigaatio",
    opensInNewTab: "Avautuu uudelle välilehdelle",
    primary: "Ensisijainen",
    sections: "Osiot",
    toggleNavigation: "Näytä tai piilota navigaatio",
    toggleTheme: "Vaihda väriteemaa",
  },
  notFound: {
    description: "Etsimääsi sivua ei löytynyt.",
    home: "Takaisin etusivulle",
    title: "Sivua ei löytynyt",
  },
  page: {
    lastUpdated: "Viimeksi päivitetty",
    next: "Seuraava",
    pagination: "Sivutus",
    previous: "Edellinen",
    related: "Aiheeseen liittyvät sivut",
    skipToContent: "Siirry sisältöön",
  },
  search: {
    all: "Kaikki",
    allLanguages: "Kaikki kielet",
    assistant: "Avustaja",
    assistantHint: "Saat välittömän vastauksen tekoälyltä",
    button: "Hae",
    devOnly: "Haku on käytettävissä tuotantokäännöksessä.",
    docs: "Dokumentaatio",
    error: "Jokin meni pieleen. Yritä uudelleen.",
    label: "Hae dokumentaatiosta",
    latest: "uusin",
    navigate: "siirry",
    noResults: "Ei tuloksia.",
    open: "avaa",
    placeholder: "Hae dokumentaatiosta…",
    popular: "Suositut",
    preview: "esikatselu",
    results: "Tulokset",
  },
  toc: { title: "Tällä sivulla" },
};
