import type { UIStringsOverride } from "../i18n-ui.ts";

/** French (fr) UI strings. */
export const fr: UIStringsOverride = {
  actions: {
    addToCursor: "Ajouter à Cursor",
    addToVscode: "Ajouter à VS Code",
    askAboutCode: "Poser une question sur ce code",
    connectMcp: "Se connecter à MCP",
    copied: "Copié !",
    copyClaudeCode: "Copier la commande Claude Code",
    copyCode: "Copier le code",
    copyCodex: "Copier la commande Codex",
    copyFailed: "Échec de la copie",
    copyMarkdown: "Copier en Markdown",
    copyServerUrl: "Copier l'URL du serveur",
    edit: "Modifier sur GitHub",
    export: "Exporter",
    exportEpub: "Exporter en EPUB",
    exportPdf: "Exporter en PDF",
    generating: "Génération…",
    openIn: "Ouvrir dans {name}",
    openInChat: "Ouvrir dans le chat",
    openInChatPrompt:
      "Lisez {url} pour que je puisse vous poser des questions sur cette page.",
    scrollToTop: "Revenir en haut",
  },
  assistant: {
    ai: "IA",
    clear: "Effacer la conversation",
    close: "Fermer",
    copy: "Copier la conversation",
    empty: "Posez une question sur la documentation.",
    error: "Désolé, une erreur s'est produite.",
    explainCode: "Explique ce code.",
    label: "Poser une question",
    open: "Ouvrir l'assistant",
    placeholder: "Posez une question…",
    rateLimited:
      "Vous avez posé beaucoup de questions. Réessayez dans quelques minutes.",
    removeCode: "Retirer le code",
    send: "Envoyer",
    support: "Contacter le support",
    supportSubject: "Question depuis la documentation",
    tip: "Astuce : vous pouvez ouvrir et fermer le chat avec",
    title: "Assistant",
    verifyFailed:
      "Nous n'avons pas pu vérifier que vous êtes humain. Réessayez.",
    you: "Vous",
  },
  banner: { dismiss: "Fermer l'annonce" },
  changelog: {
    description: "Nouveautés du produit et notes de version.",
    title: "Journal des modifications",
  },
  consent: {
    accept: "Accepter",
    decline: "Refuser",
    label: "Consentement aux cookies",
    message:
      "Nous aimerions utiliser des cookies pour comprendre comment cette documentation est utilisée.",
    policy: "Politique de confidentialité",
    settings: "Paramètres des cookies",
  },
  content: {
    code: "Code",
    copyColor: "Copier la couleur {name} {value}",
    copyPrompt: "Copier le prompt",
    default: "Par défaut",
    diagramError: "Impossible d'afficher ce diagramme.",
    forks: "Forks",
    preview: "Aperçu",
    prop: "Propriété",
    selectTab: "Sélectionner un onglet",
    selectView: "Sélectionner une vue",
    showLess: "Afficher moins",
    showMore: "Afficher plus",
    stars: "Étoiles",
    tab: "Onglet {n}",
    type: "Type",
    update: "Mise à jour",
  },
  feedback: {
    comment: "Dites-nous-en plus (facultatif)",
    no: "Non",
    question: "Cette page vous a-t-elle été utile ?",
    send: "Envoyer",
    thanks: "Merci pour votre retour !",
    yes: "Oui",
  },
  languageSwitcher: { label: "Langue", untranslated: "Non traduit" },
  narration: {
    cueDanger: "Danger.",
    cueInfo: "Info.",
    cueNote: "Remarque.",
    cueSection: "Section repliable.",
    cueStep: "Étape {n}.",
    cueSuccess: "Succès.",
    cueTab: "Onglet {title}.",
    cueTip: "Astuce.",
    cueWarning: "Avertissement.",
    error: "Impossible de charger la lecture audio.",
    follow: "Suivre la lecture",
    label: "Écouter cette page",
    minutes: "{n} min",
    next: "Phrase suivante",
    pause: "Pause",
    play: "Lecture",
    previous: "Phrase précédente",
    progress: "Progression de la lecture",
    speed: "Vitesse de lecture",
    stop: "Arrêter la lecture",
  },
  nav: {
    back: "Retour",
    breadcrumb: "Fil d'Ariane",
    closeNavigation: "Fermer la navigation",
    deprecated: "obsolète",
    featured: "En vedette",
    githubRepository: "Dépôt GitHub",
    navigation: "Navigation",
    opensInNewTab: "S'ouvre dans un nouvel onglet",
    primary: "Principal",
    sections: "Sections",
    toggleNavigation: "Afficher ou masquer la navigation",
    toggleTheme: "Changer de thème de couleur",
  },
  notFound: {
    description: "Nous n'avons pas trouvé la page que vous recherchez.",
    home: "Retour à l'accueil",
    title: "Page introuvable",
  },
  page: {
    lastUpdated: "Dernière mise à jour le",
    next: "Suivant",
    pagination: "Pagination",
    previous: "Précédent",
    related: "Pages associées",
    skipToContent: "Aller au contenu",
  },
  search: {
    all: "Tous",
    allLanguages: "Toutes les langues",
    assistant: "Assistant",
    assistantHint: "Obtenez une réponse instantanée de l'IA",
    button: "Rechercher",
    devOnly: "La recherche est disponible dans la version de production.",
    docs: "Documentation",
    error: "Une erreur s'est produite. Veuillez réessayer.",
    label: "Rechercher dans la doc",
    latest: "dernière",
    navigate: "naviguer",
    noResults: "Aucun résultat.",
    open: "ouvrir",
    placeholder: "Rechercher dans la documentation…",
    popular: "Populaires",
    preview: "aperçu",
    results: "Résultats",
  },
  toc: { title: "Sur cette page" },
};
