import type { UIStringsOverride } from "../i18n-ui.ts";

/** Hebrew (he) UI strings. */
export const he: UIStringsOverride = {
  actions: {
    addToCursor: "הוסף ל-Cursor",
    addToVscode: "הוסף ל-VS Code",
    askAboutCode: "שאלו על הקוד הזה",
    connectMcp: "התחבר ל-MCP",
    copied: "הועתק!",
    copyClaudeCode: "העתק פקודת Claude Code",
    copyCode: "העתק קוד",
    copyCodex: "העתק פקודת Codex",
    copyFailed: "ההעתקה נכשלה",
    copyMarkdown: "העתק כ-Markdown",
    copyServerUrl: "העתק כתובת URL של השרת",
    edit: "ערוך ב-GitHub",
    export: "ייצוא",
    exportEpub: "ייצוא ל-EPUB",
    exportPdf: "ייצוא ל-PDF",
    generating: "מייצר…",
    openIn: "פתח ב-{name}",
    openInChat: "פתח בצ'אט",
    openInChatPrompt: "קרא את {url} כדי שאוכל לשאול שאלות על העמוד הזה.",
    scrollToTop: "חזרה למעלה",
  },
  assistant: {
    ai: "AI",
    clear: "נקה שיחה",
    close: "סגור",
    copy: "העתק שיחה",
    empty: "שאל שאלה על התיעוד.",
    error: "מצטערים, משהו השתבש.",
    explainCode: "הסבר את הקוד הזה.",
    label: "שאל שאלה",
    placeholder: "שאל שאלה…",
    rateLimited: "שאלתם הרבה שאלות. נסו שוב בעוד כמה דקות.",
    removeCode: "הסרת הקוד",
    send: "שלח",
    support: "פנייה לתמיכה",
    supportSubject: "שאלה מהתיעוד",
    tip: "טיפ: אפשר לפתוח ולסגור את הצ'אט באמצעות",
    title: "עוזר",
    verifyFailed: "לא הצלחנו לוודא שאתם בני אדם. נסו שוב.",
    you: "אתה",
  },
  banner: { dismiss: "סגירת ההודעה" },
  changelog: {
    description: "עדכוני מוצר והערות גרסה.",
    title: "יומן שינויים",
  },
  consent: {
    accept: "אישור",
    decline: "דחייה",
    label: "הסכמה לעוגיות",
    message: "נשמח להשתמש בעוגיות כדי להבין כיצד נעשה שימוש בתיעוד הזה.",
    policy: "מדיניות פרטיות",
    settings: "הגדרות עוגיות",
  },
  content: {
    code: "קוד",
    copyColor: "העתק את הצבע {name} {value}",
    copyPrompt: "העתק הנחיה",
    default: "ברירת מחדל",
    diagramError: "לא ניתן להציג את התרשים הזה.",
    forks: "הסתעפויות",
    preview: "תצוגה מקדימה",
    prop: "מאפיין",
    selectTab: "בחר כרטיסייה",
    selectView: "בחר תצוגה",
    showLess: "הצג פחות",
    showMore: "הצג עוד",
    stars: "כוכבים",
    tab: "כרטיסייה {n}",
    type: "סוג",
    update: "עדכון",
  },
  feedback: {
    comment: "ספרו לנו עוד (אופציונלי)",
    no: "לא",
    question: "האם העמוד הזה היה מועיל?",
    send: "שליחה",
    thanks: "תודה על המשוב שלך!",
    yes: "כן",
  },
  languageSwitcher: { label: "שפה", untranslated: "לא מתורגם" },
  narration: {
    cueDanger: "סכנה.",
    cueInfo: "מידע.",
    cueNote: "הערה.",
    cueSection: "מקטע מתקפל.",
    cueStep: "שלב {n}.",
    cueSuccess: "הצלחה.",
    cueTab: "כרטיסייה {title}.",
    cueTip: "טיפ.",
    cueWarning: "אזהרה.",
    error: "לא ניתן לטעון את ההקראה.",
    follow: "מעקב אחר ההקראה",
    label: "האזנה לעמוד הזה",
    minutes: "{n} דק׳",
    next: "המשפט הבא",
    pause: "השהה",
    play: "הפעל",
    previous: "המשפט הקודם",
    progress: "התקדמות ההקראה",
    speed: "מהירות ההשמעה",
    stop: "הפסק האזנה",
  },
  nav: {
    back: "חזרה",
    breadcrumb: "פירורי לחם",
    closeNavigation: "סגור ניווט",
    deprecated: "הוצא משימוש",
    featured: "מומלץ",
    githubRepository: "מאגר GitHub",
    navigation: "ניווט",
    opensInNewTab: "נפתח בכרטיסייה חדשה",
    primary: "ראשי",
    sections: "מקטעים",
    toggleNavigation: "החלף מצב ניווט",
    toggleTheme: "החלף ערכת צבעים",
  },
  notFound: {
    description: "לא הצלחנו למצוא את העמוד שחיפשת.",
    home: "חזרה לעמוד הבית",
    title: "העמוד לא נמצא",
  },
  page: {
    lastUpdated: "עודכן לאחרונה",
    next: "הבא",
    pagination: "עימוד",
    previous: "הקודם",
    related: "דפים קשורים",
    skipToContent: "דלג לתוכן",
  },
  search: {
    all: "הכל",
    allLanguages: "כל השפות",
    assistant: "עוזר",
    assistantHint: "קבל תשובה מיידית מה-AI",
    button: "חיפוש",
    devOnly: "החיפוש זמין בבנייה לייצור.",
    docs: "תיעוד",
    error: "משהו השתבש. נסה שוב.",
    label: "חפש בתיעוד",
    latest: "האחרונה",
    navigate: "ניווט",
    noResults: "לא נמצאו תוצאות.",
    open: "פתיחה",
    placeholder: "חפש בתיעוד…",
    popular: "פופולרי",
    preview: "תצוגה מקדימה",
    results: "תוצאות",
  },
  toc: { title: "בעמוד זה" },
};
