import type { UIStringsOverride } from "../i18n-ui.ts";

/** Hindi (hi) UI strings. */
export const hi: UIStringsOverride = {
  actions: {
    addToCursor: "Cursor में जोड़ें",
    addToVscode: "VS Code में जोड़ें",
    askAboutCode: "इस कोड के बारे में पूछें",
    connectMcp: "MCP से कनेक्ट करें",
    copied: "कॉपी किया गया!",
    copyClaudeCode: "Claude Code कमांड कॉपी करें",
    copyCode: "कोड कॉपी करें",
    copyCodex: "Codex कमांड कॉपी करें",
    copyFailed: "कॉपी विफल रहा",
    copyMarkdown: "Markdown के रूप में कॉपी करें",
    copyServerUrl: "सर्वर URL कॉपी करें",
    edit: "GitHub पर संपादित करें",
    export: "एक्सपोर्ट करें",
    exportEpub: "EPUB में एक्सपोर्ट करें",
    exportPdf: "PDF में एक्सपोर्ट करें",
    generating: "जनरेट हो रहा है…",
    openIn: "{name} में खोलें",
    openInChat: "चैट में खोलें",
    openInChatPrompt: "{url} पढ़ें ताकि मैं इस पेज के बारे में प्रश्न पूछ सकूँ।",
    scrollToTop: "ऊपर जाएँ",
  },
  assistant: {
    ai: "AI",
    clear: "बातचीत साफ़ करें",
    close: "बंद करें",
    copy: "बातचीत कॉपी करें",
    empty: "दस्तावेज़ के बारे में एक प्रश्न पूछें।",
    error: "क्षमा करें, कुछ गलत हो गया।",
    explainCode: "इस कोड को समझाइए।",
    label: "एक प्रश्न पूछें",
    placeholder: "एक प्रश्न पूछें…",
    rateLimited: "आपने बहुत सारे प्रश्न पूछे हैं। कुछ मिनट बाद फिर से प्रयास करें।",
    removeCode: "कोड हटाएँ",
    send: "भेजें",
    support: "सहायता से संपर्क करें",
    supportSubject: "दस्तावेज़ से प्रश्न",
    tip: "सुझाव: चैट खोलने और बंद करने के लिए दबाएँ",
    title: "सहायक",
    verifyFailed: "हम पुष्टि नहीं कर सके कि आप इंसान हैं। फिर से प्रयास करें।",
    you: "आप",
  },
  banner: { dismiss: "घोषणा बंद करें" },
  changelog: {
    description: "उत्पाद अपडेट और रिलीज़ नोट्स।",
    title: "परिवर्तन लॉग",
  },
  consent: {
    accept: "स्वीकार करें",
    decline: "अस्वीकार करें",
    label: "कुकी सहमति",
    message:
      "हम यह समझने के लिए कुकीज़ का उपयोग करना चाहेंगे कि यह दस्तावेज़ कैसे उपयोग किया जाता है।",
    policy: "गोपनीयता नीति",
    settings: "कुकी सेटिंग्स",
  },
  content: {
    code: "कोड",
    copyColor: "{name} रंग {value} कॉपी करें",
    copyPrompt: "प्रॉम्प्ट कॉपी करें",
    default: "डिफ़ॉल्ट",
    diagramError: "यह डायग्राम रेंडर नहीं हो सका।",
    forks: "फ़ोर्क",
    preview: "पूर्वावलोकन",
    prop: "प्रॉप",
    selectTab: "टैब चुनें",
    selectView: "व्यू चुनें",
    showLess: "कम दिखाएँ",
    showMore: "और दिखाएँ",
    stars: "स्टार",
    tab: "टैब {n}",
    type: "टाइप",
    update: "अपडेट",
  },
  feedback: {
    comment: "हमें और बताएँ (वैकल्पिक)",
    no: "नहीं",
    question: "क्या यह पेज सहायक था?",
    send: "भेजें",
    thanks: "आपकी प्रतिक्रिया के लिए धन्यवाद!",
    yes: "हाँ",
  },
  languageSwitcher: { label: "भाषा", untranslated: "अनुवादित नहीं" },
  narration: {
    cueDanger: "खतरा।",
    cueInfo: "जानकारी।",
    cueNote: "नोट।",
    cueSection: "विस्तार योग्य अनुभाग।",
    cueStep: "चरण {n}।",
    cueSuccess: "सफलता।",
    cueTab: "{title} टैब।",
    cueTip: "सुझाव।",
    cueWarning: "चेतावनी।",
    error: "ऑडियो लोड नहीं हो सका।",
    follow: "साथ-साथ पढ़ें",
    label: "यह पेज सुनें",
    minutes: "{n} मिनट",
    next: "अगला वाक्य",
    pause: "रोकें",
    play: "चलाएँ",
    previous: "पिछला वाक्य",
    progress: "वाचन की प्रगति",
    speed: "प्लेबैक गति",
    stop: "सुनना बंद करें",
  },
  nav: {
    back: "वापस",
    breadcrumb: "ब्रेडक्रम",
    closeNavigation: "नेविगेशन बंद करें",
    deprecated: "अप्रचलित",
    featured: "फ़ीचर्ड",
    githubRepository: "GitHub रिपॉज़िटरी",
    navigation: "नेविगेशन",
    opensInNewTab: "नए टैब में खुलता है",
    primary: "प्राथमिक",
    sections: "अनुभाग",
    toggleNavigation: "नेविगेशन टॉगल करें",
    toggleTheme: "रंग थीम टॉगल करें",
  },
  notFound: {
    description: "आप जिस पेज को खोज रहे हैं वह हमें नहीं मिला।",
    home: "होम पर वापस जाएँ",
    title: "पेज नहीं मिला",
  },
  page: {
    lastUpdated: "अंतिम अपडेट",
    next: "अगला",
    pagination: "पृष्ठांकन",
    previous: "पिछला",
    related: "संबंधित पृष्ठ",
    skipToContent: "सामग्री पर जाएँ",
  },
  search: {
    all: "सभी",
    allLanguages: "सभी भाषाएँ",
    assistant: "सहायक",
    assistantHint: "AI से तुरंत जवाब पाएँ",
    button: "खोजें",
    devOnly: "खोज प्रोडक्शन बिल्ड में उपलब्ध है।",
    docs: "दस्तावेज़",
    error: "कुछ गलत हो गया। कृपया फिर से कोशिश करें।",
    label: "दस्तावेज़ खोजें",
    latest: "नवीनतम",
    navigate: "नेविगेट",
    noResults: "कोई परिणाम नहीं मिला।",
    open: "खोलें",
    placeholder: "दस्तावेज़ खोजें…",
    popular: "लोकप्रिय",
    preview: "प्रीव्यू",
    results: "परिणाम",
  },
  toc: { title: "इस पेज पर" },
};
