import type { UIStringsOverride } from "../i18n-ui.ts";

/** Croatian (hr) UI strings. */
export const hr: UIStringsOverride = {
  actions: {
    addToCursor: "Dodaj u Cursor",
    addToVscode: "Dodaj u VS Code",
    askAboutCode: "Pitaj o ovom kodu",
    connectMcp: "Poveži se s MCP-om",
    copied: "Kopirano!",
    copyClaudeCode: "Kopiraj naredbu Claude Code",
    copyCode: "Kopiraj kôd",
    copyCodex: "Kopiraj naredbu Codex",
    copyFailed: "Kopiranje nije uspjelo",
    copyMarkdown: "Kopiraj kao Markdown",
    copyServerUrl: "Kopiraj URL poslužitelja",
    edit: "Uredi na GitHubu",
    export: "Izvezi",
    exportEpub: "Izvezi u EPUB",
    exportPdf: "Izvezi u PDF",
    generating: "Generiranje…",
    openIn: "Otvori u {name}",
    openInChat: "Otvori u chatu",
    openInChatPrompt:
      "Pročitajte {url} — postavljat ću pitanja o ovoj stranici.",
    scrollToTop: "Natrag na vrh",
  },
  assistant: {
    ai: "AI",
    clear: "Očisti razgovor",
    close: "Zatvori",
    copy: "Kopiraj razgovor",
    empty: "Postavite pitanje o dokumentaciji.",
    error: "Žao nam je, nešto je pošlo po zlu.",
    explainCode: "Objasni ovaj kod.",
    label: "Postavi pitanje",
    placeholder: "Postavite pitanje…",
    rateLimited:
      "Postavili ste mnogo pitanja. Pokušajte ponovno za nekoliko minuta.",
    removeCode: "Ukloni kod",
    send: "Pošalji",
    support: "Kontaktiraj podršku",
    supportSubject: "Pitanje iz dokumentacije",
    tip: "Savjet: Chat možete otvoriti i zatvoriti pomoću",
    title: "Asistent",
    verifyFailed: "Nismo mogli potvrditi da ste čovjek. Pokušajte ponovno.",
    you: "Vi",
  },
  banner: { dismiss: "Zatvori obavijest" },
  changelog: {
    description: "Ažuriranja proizvoda i napomene o izdanjima.",
    title: "Popis promjena",
  },
  consent: {
    accept: "Prihvati",
    decline: "Odbij",
    label: "Pristanak na kolačiće",
    message:
      "Željeli bismo koristiti kolačiće kako bismo razumjeli kako se ova dokumentacija koristi.",
    policy: "Pravila privatnosti",
    settings: "Postavke kolačića",
  },
  content: {
    code: "Kôd",
    copyColor: "Kopiraj boju {name} {value}",
    copyPrompt: "Kopiraj upit",
    default: "Zadano",
    diagramError: "Ovaj dijagram nije moguće prikazati.",
    forks: "Forkovi",
    preview: "Pregled",
    prop: "Svojstvo",
    selectTab: "Odaberi karticu",
    selectView: "Odaberi prikaz",
    showLess: "Prikaži manje",
    showMore: "Prikaži više",
    stars: "Zvjezdice",
    tab: "Kartica {n}",
    type: "Vrsta",
    update: "Ažuriranje",
  },
  feedback: {
    comment: "Recite nam više (neobavezno)",
    no: "Ne",
    question: "Je li vam ova stranica bila korisna?",
    send: "Pošalji",
    thanks: "Hvala na povratnoj informaciji!",
    yes: "Da",
  },
  languageSwitcher: { label: "Jezik", untranslated: "Nije prevedeno" },
  narration: {
    cueDanger: "Opasnost.",
    cueInfo: "Informacija.",
    cueNote: "Napomena.",
    cueSection: "Proširivi odjeljak.",
    cueStep: "Korak {n}.",
    cueSuccess: "Uspjeh.",
    cueTab: "Kartica {title}.",
    cueTip: "Savjet.",
    cueWarning: "Upozorenje.",
    error: "Nije moguće učitati zvučnu verziju.",
    follow: "Prati čitanje",
    label: "Poslušaj ovu stranicu",
    minutes: "{n} min",
    next: "Sljedeća rečenica",
    pause: "Pauziraj",
    play: "Reproduciraj",
    previous: "Prethodna rečenica",
    progress: "Napredak čitanja",
    speed: "Brzina reprodukcije",
    stop: "Zaustavi slušanje",
  },
  nav: {
    back: "Natrag",
    breadcrumb: "Navigacijski put",
    closeNavigation: "Zatvori navigaciju",
    deprecated: "zastarjelo",
    featured: "Istaknuto",
    githubRepository: "GitHub repozitorij",
    navigation: "Navigacija",
    opensInNewTab: "Otvara se u novoj kartici",
    primary: "Glavna",
    sections: "Odjeljci",
    toggleNavigation: "Otvori ili zatvori navigaciju",
    toggleTheme: "Promijeni temu boja",
  },
  notFound: {
    description: "Nismo mogli pronaći stranicu koju tražite.",
    home: "Natrag na početnu",
    title: "Stranica nije pronađena",
  },
  page: {
    lastUpdated: "Posljednje ažuriranje",
    next: "Sljedeće",
    pagination: "Straničenje",
    previous: "Prethodno",
    related: "Povezane stranice",
    skipToContent: "Prijeđi na sadržaj",
  },
  search: {
    all: "Sve",
    allLanguages: "Svi jezici",
    assistant: "Asistent",
    assistantHint: "Dobijte trenutačni odgovor od AI-ja",
    button: "Pretraži",
    devOnly: "Pretraživanje je dostupno u produkcijskoj verziji.",
    docs: "Dokumentacija",
    error: "Nešto je pošlo po zlu. Pokušajte ponovno.",
    label: "Pretraži dokumentaciju",
    latest: "najnovija",
    navigate: "navigacija",
    noResults: "Nema rezultata.",
    open: "otvori",
    placeholder: "Pretraži dokumentaciju…",
    popular: "Popularno",
    preview: "pregled",
    results: "Rezultati",
  },
  toc: { title: "Na ovoj stranici" },
};
