import type { UIStringsOverride } from "../i18n-ui.ts";

/** Hungarian (hu) UI strings. */
export const hu: UIStringsOverride = {
  actions: {
    addToCursor: "Hozzáadás a Cursorhoz",
    addToVscode: "Hozzáadás a VS Code-hoz",
    askAboutCode: "Kérdezzen erről a kódról",
    connectMcp: "Kapcsolódás az MCP-hez",
    copied: "Másolva!",
    copyClaudeCode: "Claude Code parancs másolása",
    copyCode: "Kód másolása",
    copyCodex: "Codex parancs másolása",
    copyFailed: "A másolás nem sikerült",
    copyMarkdown: "Másolás Markdownként",
    copyServerUrl: "Szerver URL másolása",
    edit: "Szerkesztés a GitHubon",
    export: "Exportálás",
    exportEpub: "Exportálás EPUB-ba",
    exportPdf: "Exportálás PDF-be",
    generating: "Generálás…",
    openIn: "Megnyitás itt: {name}",
    openInChat: "Megnyitás a csevegésben",
    openInChatPrompt:
      "Olvasd el a következőt: {url}, hogy kérdéseket tehessek fel erről az oldalról.",
    scrollToTop: "Vissza a tetejére",
  },
  assistant: {
    ai: "AI",
    clear: "Beszélgetés törlése",
    close: "Bezárás",
    copy: "Beszélgetés másolása",
    empty: "Tegyél fel kérdést a dokumentációval kapcsolatban.",
    error: "Sajnáljuk, valami hiba történt.",
    explainCode: "Magyarázd el ezt a kódot.",
    label: "Tegyél fel egy kérdést",
    placeholder: "Tegyél fel egy kérdést…",
    rateLimited: "Sok kérdést tett fel. Próbálja újra néhány perc múlva.",
    removeCode: "Kód eltávolítása",
    send: "Küldés",
    support: "Kapcsolatfelvétel az ügyfélszolgálattal",
    supportSubject: "Kérdés a dokumentációból",
    tip: "Tipp: A csevegést ezzel nyithatod meg és zárhatod be:",
    title: "Asszisztens",
    verifyFailed: "Nem sikerült ellenőrizni, hogy Ön ember. Próbálja újra.",
    you: "Te",
  },
  banner: { dismiss: "Közlemény bezárása" },
  changelog: {
    description: "Termékfrissítések és kiadási megjegyzések.",
    title: "Változásnapló",
  },
  consent: {
    accept: "Elfogadom",
    decline: "Elutasítom",
    label: "Sütik elfogadása",
    message:
      "Sütiket szeretnénk használni, hogy megértsük, hogyan használják ezt a dokumentációt.",
    policy: "Adatvédelmi irányelvek",
    settings: "Sütibeállítások",
  },
  content: {
    code: "Kód",
    copyColor: "{name} szín másolása: {value}",
    copyPrompt: "Prompt másolása",
    default: "Alapértelmezett",
    diagramError: "Ezt a diagramot nem sikerült megjeleníteni.",
    forks: "Forkok",
    preview: "Előnézet",
    prop: "Tulajdonság",
    selectTab: "Lap kiválasztása",
    selectView: "Nézet kiválasztása",
    showLess: "Kevesebb megjelenítése",
    showMore: "Több megjelenítése",
    stars: "Csillagok",
    tab: "{n}. lap",
    type: "Típus",
    update: "Frissítés",
  },
  feedback: {
    comment: "Mondjon többet (nem kötelező)",
    no: "Nem",
    question: "Hasznos volt ez az oldal?",
    send: "Küldés",
    thanks: "Köszönjük a visszajelzésed!",
    yes: "Igen",
  },
  languageSwitcher: { label: "Nyelv", untranslated: "Nincs lefordítva" },
  narration: {
    cueDanger: "Veszély.",
    cueInfo: "Információ.",
    cueNote: "Megjegyzés.",
    cueSection: "Kibontható szakasz.",
    cueStep: "{n}. lépés.",
    cueSuccess: "Siker.",
    cueTab: "{title} lap.",
    cueTip: "Tipp.",
    cueWarning: "Figyelmeztetés.",
    error: "Nem sikerült betölteni a felolvasást.",
    follow: "Felolvasás követése",
    label: "Oldal meghallgatása",
    minutes: "{n} perc",
    next: "Következő mondat",
    pause: "Szünet",
    play: "Lejátszás",
    previous: "Előző mondat",
    progress: "Felolvasás előrehaladása",
    speed: "Lejátszási sebesség",
    stop: "Felolvasás leállítása",
  },
  nav: {
    back: "Vissza",
    breadcrumb: "Morzsamenü",
    closeNavigation: "Navigáció bezárása",
    deprecated: "elavult",
    featured: "Kiemelt",
    githubRepository: "GitHub-tároló",
    navigation: "Navigáció",
    opensInNewTab: "Új lapon nyílik meg",
    primary: "Elsődleges",
    sections: "Szakaszok",
    toggleNavigation: "Navigáció ki-/bekapcsolása",
    toggleTheme: "Színtéma váltása",
  },
  notFound: {
    description: "Nem találtuk a keresett oldalt.",
    home: "Vissza a kezdőlapra",
    title: "Az oldal nem található",
  },
  page: {
    lastUpdated: "Utoljára frissítve",
    next: "Következő",
    pagination: "Lapozás",
    previous: "Előző",
    related: "Kapcsolódó oldalak",
    skipToContent: "Ugrás a tartalomra",
  },
  search: {
    all: "Összes",
    allLanguages: "Összes nyelv",
    assistant: "Asszisztens",
    assistantHint: "Kapj azonnali választ az AI-tól",
    button: "Keresés",
    devOnly: "A keresés az éles buildben érhető el.",
    docs: "Dokumentáció",
    error: "Hiba történt. Próbáld újra.",
    label: "Keresés a dokumentációban",
    latest: "legújabb",
    navigate: "navigálás",
    noResults: "Nincs találat.",
    open: "megnyitás",
    placeholder: "Keresés a dokumentációban…",
    popular: "Népszerű",
    preview: "előnézet",
    results: "Találatok",
  },
  toc: { title: "Ezen az oldalon" },
};
