import type { UIStringsOverride } from "../i18n-ui.ts";

/** Indonesian (id) UI strings. */
export const id: UIStringsOverride = {
  actions: {
    addToCursor: "Tambahkan ke Cursor",
    addToVscode: "Tambahkan ke VS Code",
    askAboutCode: "Tanyakan tentang kode ini",
    connectMcp: "Hubungkan ke MCP",
    copied: "Disalin!",
    copyClaudeCode: "Salin perintah Claude Code",
    copyCode: "Salin kode",
    copyCodex: "Salin perintah Codex",
    copyFailed: "Gagal menyalin",
    copyMarkdown: "Salin sebagai Markdown",
    copyServerUrl: "Salin URL server",
    edit: "Edit di GitHub",
    export: "Ekspor",
    exportEpub: "Ekspor ke EPUB",
    exportPdf: "Ekspor ke PDF",
    generating: "Menghasilkan…",
    openIn: "Buka di {name}",
    openInChat: "Buka di obrolan",
    openInChatPrompt:
      "Baca {url} agar saya bisa mengajukan pertanyaan tentang halaman ini.",
    scrollToTop: "Kembali ke atas",
  },
  assistant: {
    ai: "AI",
    clear: "Hapus percakapan",
    close: "Tutup",
    copy: "Salin percakapan",
    empty: "Ajukan pertanyaan tentang dokumentasi.",
    error: "Maaf, terjadi kesalahan.",
    explainCode: "Jelaskan kode ini.",
    label: "Ajukan pertanyaan",
    open: "Buka asisten",
    placeholder: "Ajukan pertanyaan…",
    rateLimited:
      "Anda sudah mengajukan banyak pertanyaan. Coba lagi dalam beberapa menit.",
    removeCode: "Hapus kode",
    send: "Kirim",
    support: "Hubungi dukungan",
    supportSubject: "Pertanyaan dari dokumentasi",
    tip: "Tips: Anda dapat membuka dan menutup obrolan dengan",
    title: "Asisten",
    verifyFailed: "Kami tidak dapat memastikan bahwa Anda manusia. Coba lagi.",
    you: "Anda",
  },
  banner: { dismiss: "Tutup pengumuman" },
  changelog: {
    description: "Pembaruan produk dan catatan rilis.",
    title: "Log perubahan",
  },
  consent: {
    accept: "Terima",
    decline: "Tolak",
    label: "Persetujuan cookie",
    message:
      "Kami ingin menggunakan cookie untuk memahami cara dokumentasi ini digunakan.",
    policy: "Kebijakan privasi",
    settings: "Pengaturan cookie",
  },
  content: {
    code: "Kode",
    copyColor: "Salin warna {name} {value}",
    copyPrompt: "Salin prompt",
    default: "Bawaan",
    diagramError: "Tidak dapat menampilkan diagram ini.",
    forks: "Fork",
    preview: "Pratinjau",
    prop: "Properti",
    selectTab: "Pilih tab",
    selectView: "Pilih tampilan",
    showLess: "Tampilkan lebih sedikit",
    showMore: "Tampilkan lebih banyak",
    stars: "Bintang",
    tab: "Tab {n}",
    type: "Tipe",
    update: "Pembaruan",
  },
  feedback: {
    comment: "Ceritakan lebih lanjut (opsional)",
    no: "Tidak",
    question: "Apakah halaman ini membantu?",
    send: "Kirim",
    thanks: "Terima kasih atas masukan Anda!",
    yes: "Ya",
  },
  languageSwitcher: { label: "Bahasa", untranslated: "Belum diterjemahkan" },
  narration: {
    cueDanger: "Bahaya.",
    cueInfo: "Info.",
    cueNote: "Catatan.",
    cueSection: "Bagian yang dapat diperluas.",
    cueStep: "Langkah {n}.",
    cueSuccess: "Berhasil.",
    cueTab: "Tab {title}.",
    cueTip: "Tips.",
    cueWarning: "Peringatan.",
    error: "Audio tidak dapat dimuat.",
    follow: "Ikuti bacaan",
    label: "Dengarkan halaman ini",
    minutes: "{n} mnt",
    next: "Kalimat berikutnya",
    pause: "Jeda",
    play: "Putar",
    previous: "Kalimat sebelumnya",
    progress: "Progres narasi",
    speed: "Kecepatan pemutaran",
    stop: "Berhenti mendengarkan",
  },
  nav: {
    back: "Kembali",
    breadcrumb: "Remah roti",
    closeNavigation: "Tutup navigasi",
    deprecated: "usang",
    featured: "Unggulan",
    githubRepository: "Repositori GitHub",
    navigation: "Navigasi",
    opensInNewTab: "Terbuka di tab baru",
    primary: "Utama",
    sections: "Bagian",
    toggleNavigation: "Buka/tutup navigasi",
    toggleTheme: "Ganti tema warna",
  },
  notFound: {
    description: "Kami tidak dapat menemukan halaman yang Anda cari.",
    home: "Kembali ke beranda",
    title: "Halaman tidak ditemukan",
  },
  page: {
    lastUpdated: "Terakhir diperbarui",
    next: "Berikutnya",
    pagination: "Penomoran halaman",
    previous: "Sebelumnya",
    related: "Halaman terkait",
    skipToContent: "Lewati ke konten",
  },
  search: {
    all: "Semua",
    allLanguages: "Semua bahasa",
    assistant: "Asisten",
    assistantHint: "Dapatkan jawaban instan dari AI",
    button: "Cari",
    devOnly: "Pencarian tersedia di build produksi.",
    docs: "Dokumentasi",
    error: "Terjadi kesalahan. Silakan coba lagi.",
    label: "Cari dokumentasi",
    latest: "terbaru",
    navigate: "navigasi",
    noResults: "Tidak ada hasil ditemukan.",
    open: "buka",
    placeholder: "Cari dokumentasi…",
    popular: "Populer",
    preview: "pratinjau",
    results: "Hasil",
  },
  toc: { title: "Di halaman ini" },
};
