import type { UIStringsOverride } from "../i18n-ui.ts";

/** Italian (it) UI strings. */
export const it: UIStringsOverride = {
  actions: {
    addToCursor: "Aggiungi a Cursor",
    addToVscode: "Aggiungi a VS Code",
    askAboutCode: "Chiedi informazioni su questo codice",
    connectMcp: "Connetti a MCP",
    copied: "Copiato!",
    copyClaudeCode: "Copia comando di Claude Code",
    copyCode: "Copia codice",
    copyCodex: "Copia comando di Codex",
    copyFailed: "Copia non riuscita",
    copyMarkdown: "Copia come Markdown",
    copyServerUrl: "Copia URL del server",
    edit: "Modifica su GitHub",
    export: "Esporta",
    exportEpub: "Esporta in EPUB",
    exportPdf: "Esporta in PDF",
    generating: "Generazione in corso…",
    openIn: "Apri in {name}",
    openInChat: "Apri nella chat",
    openInChatPrompt: "Leggi {url} così posso farti domande su questa pagina.",
    scrollToTop: "Torna su",
  },
  assistant: {
    ai: "IA",
    clear: "Cancella la conversazione",
    close: "Chiudi",
    copy: "Copia la conversazione",
    empty: "Fai una domanda sulla documentazione.",
    error: "Spiacenti, qualcosa è andato storto.",
    explainCode: "Spiega questo codice.",
    label: "Fai una domanda",
    placeholder: "Fai una domanda…",
    rateLimited: "Hai fatto molte domande. Riprova tra qualche minuto.",
    removeCode: "Rimuovi codice",
    send: "Invia",
    support: "Contatta l'assistenza",
    supportSubject: "Domanda dalla documentazione",
    tip: "Suggerimento: puoi aprire e chiudere la chat con",
    title: "Assistente",
    verifyFailed:
      "Non siamo riusciti a verificare che sei una persona. Riprova.",
    you: "Tu",
  },
  banner: { dismiss: "Chiudi l'annuncio" },
  changelog: {
    description: "Aggiornamenti del prodotto e note di rilascio.",
    title: "Registro delle modifiche",
  },
  consent: {
    accept: "Accetta",
    decline: "Rifiuta",
    label: "Consenso ai cookie",
    message:
      "Vorremmo usare i cookie per capire come viene usata questa documentazione.",
    policy: "Informativa sulla privacy",
    settings: "Impostazioni dei cookie",
  },
  content: {
    code: "Codice",
    copyColor: "Copia il colore {name} {value}",
    copyPrompt: "Copia prompt",
    default: "Predefinito",
    diagramError: "Impossibile visualizzare questo diagramma.",
    forks: "Fork",
    preview: "Anteprima",
    prop: "Proprietà",
    selectTab: "Seleziona una scheda",
    selectView: "Seleziona una vista",
    showLess: "Mostra di meno",
    showMore: "Mostra di più",
    stars: "Stelle",
    tab: "Scheda {n}",
    type: "Tipo",
    update: "Aggiornamento",
  },
  feedback: {
    comment: "Raccontaci di più (facoltativo)",
    no: "No",
    question: "Questa pagina ti è stata utile?",
    send: "Invia",
    thanks: "Grazie per il tuo feedback!",
    yes: "Sì",
  },
  languageSwitcher: { label: "Lingua", untranslated: "Non tradotto" },
  narration: {
    cueDanger: "Pericolo.",
    cueInfo: "Info.",
    cueNote: "Nota.",
    cueSection: "Sezione espandibile.",
    cueStep: "Passaggio {n}.",
    cueSuccess: "Successo.",
    cueTab: "Scheda {title}.",
    cueTip: "Suggerimento.",
    cueWarning: "Attenzione.",
    error: "Impossibile caricare l'audio.",
    follow: "Segui la lettura",
    label: "Ascolta questa pagina",
    minutes: "{n} min",
    next: "Frase successiva",
    pause: "Pausa",
    play: "Riproduci",
    previous: "Frase precedente",
    progress: "Avanzamento della lettura",
    speed: "Velocità di riproduzione",
    stop: "Interrompi l'ascolto",
  },
  nav: {
    back: "Indietro",
    breadcrumb: "Percorso di navigazione",
    closeNavigation: "Chiudi la navigazione",
    deprecated: "deprecato",
    featured: "In evidenza",
    githubRepository: "Repository GitHub",
    navigation: "Navigazione",
    opensInNewTab: "Si apre in una nuova scheda",
    primary: "Principale",
    sections: "Sezioni",
    toggleNavigation: "Mostra o nascondi la navigazione",
    toggleTheme: "Cambia il tema colore",
  },
  notFound: {
    description: "Non siamo riusciti a trovare la pagina che cerchi.",
    home: "Torna alla home",
    title: "Pagina non trovata",
  },
  page: {
    lastUpdated: "Ultimo aggiornamento il",
    next: "Successivo",
    pagination: "Paginazione",
    previous: "Precedente",
    related: "Pagine correlate",
    skipToContent: "Vai al contenuto",
  },
  search: {
    all: "Tutti",
    allLanguages: "Tutte le lingue",
    assistant: "Assistente",
    assistantHint: "Ottieni una risposta immediata dall'IA",
    button: "Cerca",
    devOnly: "La ricerca è disponibile nella build di produzione.",
    docs: "Documentazione",
    error: "Qualcosa è andato storto. Riprova.",
    label: "Cerca nella documentazione",
    latest: "più recente",
    navigate: "naviga",
    noResults: "Nessun risultato trovato.",
    open: "apri",
    placeholder: "Cerca nella documentazione…",
    popular: "Popolari",
    preview: "anteprima",
    results: "Risultati",
  },
  toc: { title: "In questa pagina" },
};
