import type { UIStringsOverride } from "../i18n-ui.ts";

/** Japanese (ja) UI strings. */
export const ja: UIStringsOverride = {
  actions: {
    addToCursor: "Cursor に追加",
    addToVscode: "VS Code に追加",
    askAboutCode: "このコードについて質問",
    connectMcp: "MCP に接続",
    copied: "コピーしました！",
    copyClaudeCode: "Claude Code コマンドをコピー",
    copyCode: "コードをコピー",
    copyCodex: "Codex コマンドをコピー",
    copyFailed: "コピーに失敗しました",
    copyMarkdown: "Markdown としてコピー",
    copyServerUrl: "サーバー URL をコピー",
    edit: "GitHub で編集",
    export: "エクスポート",
    exportEpub: "EPUB にエクスポート",
    exportPdf: "PDF にエクスポート",
    generating: "生成中…",
    openIn: "{name} で開く",
    openInChat: "チャットで開く",
    openInChatPrompt:
      "{url} を読んで、このページについての質問に答えられるようにしてください。",
    scrollToTop: "トップに戻る",
  },
  assistant: {
    ai: "AI",
    clear: "会話をクリア",
    close: "閉じる",
    copy: "会話をコピー",
    empty: "ドキュメントについて質問してください。",
    error: "申し訳ありません。問題が発生しました。",
    explainCode: "このコードを説明してください。",
    label: "質問する",
    open: "アシスタントを開く",
    placeholder: "質問を入力…",
    rateLimited: "質問の回数が多すぎます。数分後にもう一度お試しください。",
    removeCode: "コードを削除",
    send: "送信",
    support: "サポートに問い合わせる",
    supportSubject: "ドキュメントからの質問",
    tip: "ヒント: 次のキーでチャットを開閉できます",
    title: "アシスタント",
    verifyFailed:
      "人間であることを確認できませんでした。もう一度お試しください。",
    you: "あなた",
  },
  banner: { dismiss: "お知らせを閉じる" },
  changelog: {
    description: "製品のアップデートとリリースノート。",
    title: "変更履歴",
  },
  consent: {
    accept: "同意する",
    decline: "拒否する",
    label: "Cookie の同意",
    message:
      "このドキュメントの利用状況を把握するために Cookie を使用したいと考えています。",
    policy: "プライバシーポリシー",
    settings: "Cookie 設定",
  },
  content: {
    code: "コード",
    copyColor: "カラー {name}（{value}）をコピー",
    copyPrompt: "プロンプトをコピー",
    default: "デフォルト",
    diagramError: "この図を表示できませんでした。",
    forks: "フォーク",
    preview: "プレビュー",
    prop: "プロパティ",
    selectTab: "タブを選択",
    selectView: "表示を選択",
    showLess: "表示を減らす",
    showMore: "もっと見る",
    stars: "スター",
    tab: "タブ {n}",
    type: "型",
    update: "アップデート",
  },
  feedback: {
    comment: "詳しく教えてください（任意）",
    no: "いいえ",
    question: "このページは役に立ちましたか？",
    send: "送信",
    thanks: "フィードバックありがとうございます！",
    yes: "はい",
  },
  languageSwitcher: { label: "言語", untranslated: "未翻訳" },
  narration: {
    cueDanger: "危険。",
    cueInfo: "情報。",
    cueNote: "注記。",
    cueSection: "折りたたみセクション。",
    cueStep: "ステップ {n}。",
    cueSuccess: "成功。",
    cueTab: "{title} タブ。",
    cueTip: "ヒント。",
    cueWarning: "警告。",
    error: "読み上げを読み込めませんでした。",
    follow: "読み上げ位置に追従",
    label: "このページを聞く",
    minutes: "{n} 分",
    next: "次の文",
    pause: "一時停止",
    play: "再生",
    previous: "前の文",
    progress: "読み上げの進行状況",
    speed: "再生速度",
    stop: "読み上げを停止",
  },
  nav: {
    back: "戻る",
    breadcrumb: "パンくずリスト",
    closeNavigation: "ナビゲーションを閉じる",
    deprecated: "非推奨",
    featured: "注目",
    githubRepository: "GitHub リポジトリ",
    navigation: "ナビゲーション",
    opensInNewTab: "新しいタブで開きます",
    primary: "メイン",
    sections: "セクション",
    toggleNavigation: "ナビゲーションを切り替え",
    toggleTheme: "カラーテーマを切り替え",
  },
  notFound: {
    description: "お探しのページが見つかりませんでした。",
    home: "ホームに戻る",
    title: "ページが見つかりません",
  },
  page: {
    lastUpdated: "最終更新",
    next: "次へ",
    pagination: "ページネーション",
    previous: "前へ",
    related: "関連ページ",
    skipToContent: "コンテンツにスキップ",
  },
  search: {
    all: "すべて",
    allLanguages: "すべての言語",
    assistant: "アシスタント",
    assistantHint: "AI からすぐに回答を得る",
    button: "検索",
    devOnly: "検索は本番ビルドで利用できます。",
    docs: "ドキュメント",
    error: "問題が発生しました。もう一度お試しください。",
    label: "ドキュメントを検索",
    latest: "最新",
    navigate: "移動",
    noResults: "結果が見つかりませんでした。",
    open: "開く",
    placeholder: "ドキュメントを検索…",
    popular: "人気",
    preview: "プレビュー",
    results: "結果",
  },
  toc: { title: "このページの内容" },
};
