import type { UIStringsOverride } from "../i18n-ui.ts";

/** Korean (ko) UI strings. */
export const ko: UIStringsOverride = {
  actions: {
    addToCursor: "Cursor에 추가",
    addToVscode: "VS Code에 추가",
    askAboutCode: "이 코드에 대해 질문하기",
    connectMcp: "MCP에 연결",
    copied: "복사됨!",
    copyClaudeCode: "Claude Code 명령 복사",
    copyCode: "코드 복사",
    copyCodex: "Codex 명령 복사",
    copyFailed: "복사 실패",
    copyMarkdown: "Markdown으로 복사",
    copyServerUrl: "서버 URL 복사",
    edit: "GitHub에서 편집",
    export: "내보내기",
    exportEpub: "EPUB으로 내보내기",
    exportPdf: "PDF로 내보내기",
    generating: "생성 중…",
    openIn: "{name}에서 열기",
    openInChat: "채팅에서 열기",
    openInChatPrompt:
      "{url} 페이지를 읽어 주세요. 이 페이지에 대해 질문하겠습니다.",
    scrollToTop: "맨 위로",
  },
  assistant: {
    ai: "AI",
    clear: "대화 지우기",
    close: "닫기",
    copy: "대화 복사",
    empty: "문서에 대해 질문하세요.",
    error: "죄송합니다. 문제가 발생했습니다.",
    explainCode: "이 코드를 설명해 주세요.",
    label: "질문하기",
    placeholder: "질문하기…",
    rateLimited: "질문을 너무 많이 하셨습니다. 몇 분 후에 다시 시도해 주세요.",
    removeCode: "코드 제거",
    send: "보내기",
    support: "지원팀에 문의",
    supportSubject: "문서에서 보낸 질문",
    tip: "팁: 다음 키로 채팅을 열고 닫을 수 있습니다",
    title: "어시스턴트",
    verifyFailed: "사람인지 확인하지 못했습니다. 다시 시도해 주세요.",
    you: "나",
  },
  banner: { dismiss: "공지 닫기" },
  changelog: {
    description: "제품 업데이트 및 릴리스 노트.",
    title: "변경 로그",
  },
  consent: {
    accept: "수락",
    decline: "거부",
    label: "쿠키 동의",
    message:
      "이 문서가 어떻게 사용되는지 파악하기 위해 쿠키를 사용하고자 합니다.",
    policy: "개인정보 처리방침",
    settings: "쿠키 설정",
  },
  content: {
    code: "코드",
    copyColor: "{name} 색상 {value} 복사",
    copyPrompt: "프롬프트 복사",
    default: "기본값",
    diagramError: "이 다이어그램을 표시할 수 없습니다.",
    forks: "포크",
    preview: "미리보기",
    prop: "속성",
    selectTab: "탭 선택",
    selectView: "보기 선택",
    showLess: "간략히 보기",
    showMore: "더 보기",
    stars: "스타",
    tab: "탭 {n}",
    type: "타입",
    update: "업데이트",
  },
  feedback: {
    comment: "자세히 알려 주세요 (선택 사항)",
    no: "아니요",
    question: "이 페이지가 도움이 되었나요?",
    send: "보내기",
    thanks: "의견 주셔서 감사합니다!",
    yes: "예",
  },
  languageSwitcher: { label: "언어", untranslated: "번역되지 않음" },
  narration: {
    cueDanger: "위험.",
    cueInfo: "정보.",
    cueNote: "참고.",
    cueSection: "펼칠 수 있는 섹션.",
    cueStep: "{n}단계.",
    cueSuccess: "성공.",
    cueTab: "{title} 탭.",
    cueTip: "팁.",
    cueWarning: "경고.",
    error: "음성 낭독을 불러오지 못했습니다.",
    follow: "읽는 위치 따라가기",
    label: "이 페이지 듣기",
    minutes: "{n}분",
    next: "다음 문장",
    pause: "일시정지",
    play: "재생",
    previous: "이전 문장",
    progress: "낭독 진행률",
    speed: "재생 속도",
    stop: "듣기 중지",
  },
  nav: {
    back: "뒤로",
    breadcrumb: "탐색 경로",
    closeNavigation: "탐색 닫기",
    deprecated: "지원 중단",
    featured: "추천",
    githubRepository: "GitHub 저장소",
    navigation: "탐색",
    opensInNewTab: "새 탭에서 열림",
    primary: "기본",
    sections: "섹션",
    toggleNavigation: "탐색 전환",
    toggleTheme: "색상 테마 전환",
  },
  notFound: {
    description: "찾으시는 페이지를 찾을 수 없습니다.",
    home: "홈으로 돌아가기",
    title: "페이지를 찾을 수 없습니다",
  },
  page: {
    lastUpdated: "마지막 업데이트",
    next: "다음",
    pagination: "페이지네이션",
    previous: "이전",
    related: "관련 페이지",
    skipToContent: "본문으로 건너뛰기",
  },
  search: {
    all: "전체",
    allLanguages: "모든 언어",
    assistant: "어시스턴트",
    assistantHint: "AI에게 즉시 답변 받기",
    button: "검색",
    devOnly: "검색은 프로덕션 빌드에서 사용할 수 있습니다.",
    docs: "문서",
    error: "문제가 발생했습니다. 다시 시도해 주세요.",
    label: "문서 검색",
    latest: "최신",
    navigate: "이동",
    noResults: "결과를 찾을 수 없습니다.",
    open: "열기",
    placeholder: "문서 검색…",
    popular: "인기",
    preview: "미리보기",
    results: "결과",
  },
  toc: { title: "이 페이지에서" },
};
