import type { UIStringsOverride } from "../i18n-ui.ts";

/** Dutch (nl) UI strings. */
export const nl: UIStringsOverride = {
  actions: {
    addToCursor: "Toevoegen aan Cursor",
    addToVscode: "Toevoegen aan VS Code",
    askAboutCode: "Vraag over deze code",
    connectMcp: "Verbinden met MCP",
    copied: "Gekopieerd!",
    copyClaudeCode: "Claude Code-opdracht kopiëren",
    copyCode: "Code kopiëren",
    copyCodex: "Codex-opdracht kopiëren",
    copyFailed: "Kopiëren mislukt",
    copyMarkdown: "Kopiëren als Markdown",
    copyServerUrl: "Server-URL kopiëren",
    edit: "Bewerken op GitHub",
    export: "Exporteren",
    exportEpub: "Exporteren naar EPUB",
    exportPdf: "Exporteren naar PDF",
    generating: "Genereren…",
    openIn: "Openen in {name}",
    openInChat: "Openen in chat",
    openInChatPrompt:
      "Lees {url}, zodat ik je vragen kan stellen over deze pagina.",
    scrollToTop: "Naar boven scrollen",
  },
  assistant: {
    ai: "AI",
    clear: "Gesprek wissen",
    close: "Sluiten",
    copy: "Gesprek kopiëren",
    empty: "Stel een vraag over de documentatie.",
    error: "Sorry, er is iets misgegaan.",
    explainCode: "Leg deze code uit.",
    label: "Stel een vraag",
    open: "Assistent openen",
    placeholder: "Stel een vraag…",
    rateLimited:
      "Je hebt veel vragen gesteld. Probeer het over een paar minuten opnieuw.",
    removeCode: "Code verwijderen",
    send: "Verzenden",
    support: "Contact met support",
    supportSubject: "Vraag vanuit de documentatie",
    tip: "Tip: Je kunt de chat openen en sluiten met",
    title: "Assistent",
    verifyFailed:
      "We konden niet controleren of je een mens bent. Probeer het opnieuw.",
    you: "Jij",
  },
  banner: { dismiss: "Aankondiging sluiten" },
  changelog: {
    description: "Productupdates en releaseopmerkingen.",
    title: "Wijzigingslogboek",
  },
  consent: {
    accept: "Accepteren",
    decline: "Weigeren",
    label: "Cookietoestemming",
    message:
      "We willen graag cookies gebruiken om te begrijpen hoe deze documentatie wordt gebruikt.",
    policy: "Privacybeleid",
    settings: "Cookie-instellingen",
  },
  content: {
    code: "Code",
    copyColor: "Kleur {name} {value} kopiëren",
    copyPrompt: "Prompt kopiëren",
    default: "Standaard",
    diagramError: "Dit diagram kon niet worden weergegeven.",
    forks: "Forks",
    preview: "Voorbeeld",
    prop: "Eigenschap",
    selectTab: "Tabblad kiezen",
    selectView: "Weergave kiezen",
    showLess: "Minder weergeven",
    showMore: "Meer weergeven",
    stars: "Sterren",
    tab: "Tabblad {n}",
    type: "Type",
    update: "Update",
  },
  feedback: {
    comment: "Vertel ons meer (optioneel)",
    no: "Nee",
    question: "Was deze pagina nuttig?",
    send: "Versturen",
    thanks: "Bedankt voor je feedback!",
    yes: "Ja",
  },
  languageSwitcher: { label: "Taal", untranslated: "Niet vertaald" },
  narration: {
    cueDanger: "Gevaar.",
    cueInfo: "Info.",
    cueNote: "Opmerking.",
    cueSection: "Uitklapbare sectie.",
    cueStep: "Stap {n}.",
    cueSuccess: "Gelukt.",
    cueTab: "Tabblad {title}.",
    cueTip: "Tip.",
    cueWarning: "Waarschuwing.",
    error: "De audio kon niet worden geladen.",
    follow: "Meelezen",
    label: "Deze pagina beluisteren",
    minutes: "{n} min",
    next: "Volgende zin",
    pause: "Pauzeren",
    play: "Afspelen",
    previous: "Vorige zin",
    progress: "Voortgang van het voorlezen",
    speed: "Afspeelsnelheid",
    stop: "Stoppen met luisteren",
  },
  nav: {
    back: "Terug",
    breadcrumb: "Kruimelpad",
    closeNavigation: "Navigatie sluiten",
    deprecated: "verouderd",
    featured: "Uitgelicht",
    githubRepository: "GitHub-repository",
    navigation: "Navigatie",
    opensInNewTab: "Opent in een nieuw tabblad",
    primary: "Primair",
    sections: "Secties",
    toggleNavigation: "Navigatie tonen of verbergen",
    toggleTheme: "Kleurthema wisselen",
  },
  notFound: {
    description: "We konden de pagina die je zoekt niet vinden.",
    home: "Terug naar de startpagina",
    title: "Pagina niet gevonden",
  },
  page: {
    lastUpdated: "Laatst bijgewerkt op",
    next: "Volgende",
    pagination: "Paginering",
    previous: "Vorige",
    related: "Gerelateerde pagina's",
    skipToContent: "Naar inhoud springen",
  },
  search: {
    all: "Alle",
    allLanguages: "Alle talen",
    assistant: "Assistent",
    assistantHint: "Krijg direct antwoord van AI",
    button: "Zoeken",
    devOnly: "Zoeken is beschikbaar in de productiebuild.",
    docs: "Documentatie",
    error: "Er is iets misgegaan. Probeer het opnieuw.",
    label: "Documentatie doorzoeken",
    latest: "nieuwste",
    navigate: "navigeren",
    noResults: "Geen resultaten gevonden.",
    open: "openen",
    placeholder: "Documentatie doorzoeken…",
    popular: "Populair",
    preview: "voorbeeld",
    results: "Resultaten",
  },
  toc: { title: "Op deze pagina" },
};
