import type { UIStringsOverride } from "../i18n-ui.ts";

/** Norwegian Bokmål (no) UI strings. */
export const no: UIStringsOverride = {
  actions: {
    addToCursor: "Legg til i Cursor",
    addToVscode: "Legg til i VS Code",
    askAboutCode: "Spør om denne koden",
    connectMcp: "Koble til MCP",
    copied: "Kopiert!",
    copyClaudeCode: "Kopier Claude Code-kommando",
    copyCode: "Kopier kode",
    copyCodex: "Kopier Codex-kommando",
    copyFailed: "Kopiering mislyktes",
    copyMarkdown: "Kopier som Markdown",
    copyServerUrl: "Kopier server-URL",
    edit: "Rediger på GitHub",
    export: "Eksporter",
    exportEpub: "Eksporter til EPUB",
    exportPdf: "Eksporter til PDF",
    generating: "Genererer…",
    openIn: "Åpne i {name}",
    openInChat: "Åpne i chat",
    openInChatPrompt:
      "Les {url}, slik at jeg kan stille spørsmål om denne siden.",
    scrollToTop: "Til toppen",
  },
  assistant: {
    ai: "AI",
    clear: "Tøm samtalen",
    close: "Lukk",
    copy: "Kopier samtalen",
    empty: "Still et spørsmål om dokumentasjonen.",
    error: "Beklager, noe gikk galt.",
    explainCode: "Forklar denne koden.",
    label: "Still et spørsmål",
    open: "Åpne assistenten",
    placeholder: "Still et spørsmål…",
    rateLimited: "Du har stilt mange spørsmål. Prøv igjen om noen minutter.",
    removeCode: "Fjern koden",
    send: "Send",
    support: "Kontakt kundestøtte",
    supportSubject: "Spørsmål fra dokumentasjonen",
    tip: "Tips: Du kan åpne og lukke chatten med",
    title: "Assistent",
    verifyFailed: "Vi kunne ikke bekrefte at du er et menneske. Prøv igjen.",
    you: "Du",
  },
  banner: { dismiss: "Lukk kunngjøringen" },
  changelog: {
    description: "Produktoppdateringer og utgivelsesnotater.",
    title: "Endringslogg",
  },
  consent: {
    accept: "Godta",
    decline: "Avslå",
    label: "Samtykke til informasjonskapsler",
    message:
      "Vi vil gjerne bruke informasjonskapsler for å forstå hvordan denne dokumentasjonen brukes.",
    policy: "Personvernerklæring",
    settings: "Innstillinger for informasjonskapsler",
  },
  content: {
    code: "Kode",
    copyColor: "Kopier fargen {name} {value}",
    copyPrompt: "Kopier prompt",
    default: "Standard",
    diagramError: "Kunne ikke vise dette diagrammet.",
    forks: "Forks",
    preview: "Forhåndsvisning",
    prop: "Egenskap",
    selectTab: "Velg fane",
    selectView: "Velg visning",
    showLess: "Vis mindre",
    showMore: "Vis mer",
    stars: "Stjerner",
    tab: "Fane {n}",
    type: "Type",
    update: "Oppdatering",
  },
  feedback: {
    comment: "Fortell oss mer (valgfritt)",
    no: "Nei",
    question: "Var denne siden nyttig?",
    send: "Send",
    thanks: "Takk for tilbakemeldingen!",
    yes: "Ja",
  },
  languageSwitcher: { label: "Språk", untranslated: "Ikke oversatt" },
  narration: {
    cueDanger: "Fare.",
    cueInfo: "Info.",
    cueNote: "Merk.",
    cueSection: "Utvidbar seksjon.",
    cueStep: "Trinn {n}.",
    cueSuccess: "Fullført.",
    cueTab: "Fanen {title}.",
    cueTip: "Tips.",
    cueWarning: "Advarsel.",
    error: "Opplesningen kunne ikke lastes inn.",
    follow: "Følg med",
    label: "Lytt til denne siden",
    minutes: "{n} min",
    next: "Neste setning",
    pause: "Pause",
    play: "Spill av",
    previous: "Forrige setning",
    progress: "Fremdrift i opplesningen",
    speed: "Avspillingshastighet",
    stop: "Stopp opplesningen",
  },
  nav: {
    back: "Tilbake",
    breadcrumb: "Brødsmulesti",
    closeNavigation: "Lukk navigasjonen",
    deprecated: "foreldet",
    featured: "Utvalgt",
    githubRepository: "GitHub-repositorium",
    navigation: "Navigasjon",
    opensInNewTab: "Åpnes i en ny fane",
    primary: "Primær",
    sections: "Seksjoner",
    toggleNavigation: "Vis eller skjul navigasjonen",
    toggleTheme: "Bytt fargetema",
  },
  notFound: {
    description: "Vi fant ikke siden du leter etter.",
    home: "Tilbake til forsiden",
    title: "Siden ble ikke funnet",
  },
  page: {
    lastUpdated: "Sist oppdatert",
    next: "Neste",
    pagination: "Paginering",
    previous: "Forrige",
    related: "Relaterte sider",
    skipToContent: "Hopp til innhold",
  },
  search: {
    all: "Alle",
    allLanguages: "Alle språk",
    assistant: "Assistent",
    assistantHint: "Få et umiddelbart svar fra AI",
    button: "Søk",
    devOnly: "Søk er tilgjengelig i produksjonsbygget.",
    docs: "Dokumentasjon",
    error: "Noe gikk galt. Prøv igjen.",
    label: "Søk i dokumentasjonen",
    latest: "nyeste",
    navigate: "naviger",
    noResults: "Ingen resultater funnet.",
    open: "åpne",
    placeholder: "Søk i dokumentasjonen…",
    popular: "Populært",
    preview: "forhåndsvis",
    results: "Resultater",
  },
  toc: { title: "På denne siden" },
};
