import type { UIStringsOverride } from "../i18n-ui.ts";

/** Polish (pl) UI strings. */
export const pl: UIStringsOverride = {
  actions: {
    addToCursor: "Dodaj do Cursor",
    addToVscode: "Dodaj do VS Code",
    askAboutCode: "Zapytaj o ten kod",
    connectMcp: "Połącz z MCP",
    copied: "Skopiowano!",
    copyClaudeCode: "Kopiuj polecenie Claude Code",
    copyCode: "Kopiuj kod",
    copyCodex: "Kopiuj polecenie Codex",
    copyFailed: "Kopiowanie nie powiodło się",
    copyMarkdown: "Kopiuj jako Markdown",
    copyServerUrl: "Kopiuj adres URL serwera",
    edit: "Edytuj na GitHubie",
    export: "Eksportuj",
    exportEpub: "Eksportuj do EPUB",
    exportPdf: "Eksportuj do PDF",
    generating: "Generowanie…",
    openIn: "Otwórz w {name}",
    openInChat: "Otwórz w czacie",
    openInChatPrompt:
      "Przeczytaj {url}, aby móc odpowiadać na pytania dotyczące tej strony.",
    scrollToTop: "Wróć na górę",
  },
  assistant: {
    ai: "AI",
    clear: "Wyczyść rozmowę",
    close: "Zamknij",
    copy: "Kopiuj rozmowę",
    empty: "Zadaj pytanie dotyczące dokumentacji.",
    error: "Przepraszamy, coś poszło nie tak.",
    explainCode: "Wyjaśnij ten kod.",
    label: "Zadaj pytanie",
    placeholder: "Zadaj pytanie…",
    rateLimited: "Zadano wiele pytań. Spróbuj ponownie za kilka minut.",
    removeCode: "Usuń kod",
    send: "Wyślij",
    support: "Skontaktuj się z pomocą",
    supportSubject: "Pytanie z dokumentacji",
    tip: "Wskazówka: czat możesz otwierać i zamykać za pomocą",
    title: "Asystent",
    verifyFailed:
      "Nie udało się potwierdzić, że jesteś człowiekiem. Spróbuj ponownie.",
    you: "Ty",
  },
  banner: { dismiss: "Zamknij ogłoszenie" },
  changelog: {
    description: "Aktualizacje produktu i informacje o wydaniach.",
    title: "Dziennik zmian",
  },
  consent: {
    accept: "Akceptuj",
    decline: "Odrzuć",
    label: "Zgoda na pliki cookie",
    message:
      "Chcielibyśmy używać plików cookie, aby zrozumieć, jak używana jest ta dokumentacja.",
    policy: "Polityka prywatności",
    settings: "Ustawienia plików cookie",
  },
  content: {
    code: "Kod",
    copyColor: "Kopiuj kolor {name} {value}",
    copyPrompt: "Kopiuj prompt",
    default: "Domyślnie",
    diagramError: "Nie udało się wyświetlić tego diagramu.",
    forks: "Forki",
    preview: "Podgląd",
    prop: "Właściwość",
    selectTab: "Wybierz kartę",
    selectView: "Wybierz widok",
    showLess: "Pokaż mniej",
    showMore: "Pokaż więcej",
    stars: "Gwiazdki",
    tab: "Karta {n}",
    type: "Typ",
    update: "Aktualizacja",
  },
  feedback: {
    comment: "Powiedz nam więcej (opcjonalnie)",
    no: "Nie",
    question: "Czy ta strona była pomocna?",
    send: "Wyślij",
    thanks: "Dziękujemy za opinię!",
    yes: "Tak",
  },
  languageSwitcher: { label: "Język", untranslated: "Nieprzetłumaczone" },
  narration: {
    cueDanger: "Niebezpieczeństwo.",
    cueInfo: "Informacja.",
    cueNote: "Notatka.",
    cueSection: "Sekcja rozwijana.",
    cueStep: "Krok {n}.",
    cueSuccess: "Sukces.",
    cueTab: "Karta {title}.",
    cueTip: "Wskazówka.",
    cueWarning: "Ostrzeżenie.",
    error: "Nie udało się wczytać nagrania.",
    follow: "Śledź czytanie",
    label: "Posłuchaj tej strony",
    minutes: "{n} min",
    next: "Następne zdanie",
    pause: "Wstrzymaj",
    play: "Odtwórz",
    previous: "Poprzednie zdanie",
    progress: "Postęp odtwarzania",
    speed: "Szybkość odtwarzania",
    stop: "Zakończ słuchanie",
  },
  nav: {
    back: "Wstecz",
    breadcrumb: "Ścieżka nawigacyjna",
    closeNavigation: "Zamknij nawigację",
    deprecated: "przestarzałe",
    featured: "Polecane",
    githubRepository: "Repozytorium GitHub",
    navigation: "Nawigacja",
    opensInNewTab: "Otwiera się w nowej karcie",
    primary: "Główne",
    sections: "Sekcje",
    toggleNavigation: "Przełącz nawigację",
    toggleTheme: "Przełącz motyw kolorystyczny",
  },
  notFound: {
    description: "Nie znaleźliśmy strony, której szukasz.",
    home: "Wróć na stronę główną",
    title: "Nie znaleziono strony",
  },
  page: {
    lastUpdated: "Ostatnia aktualizacja",
    next: "Następny",
    pagination: "Paginacja",
    previous: "Poprzedni",
    related: "Powiązane strony",
    skipToContent: "Przejdź do treści",
  },
  search: {
    all: "Wszystkie",
    allLanguages: "Wszystkie języki",
    assistant: "Asystent",
    assistantHint: "Uzyskaj natychmiastową odpowiedź od AI",
    button: "Szukaj",
    devOnly: "Wyszukiwanie jest dostępne w kompilacji produkcyjnej.",
    docs: "Dokumentacja",
    error: "Coś poszło nie tak. Spróbuj ponownie.",
    label: "Przeszukaj dokumentację",
    latest: "najnowsza",
    navigate: "nawigacja",
    noResults: "Nie znaleziono wyników.",
    open: "otwórz",
    placeholder: "Przeszukaj dokumentację…",
    popular: "Popularne",
    preview: "podgląd",
    results: "Wyniki",
  },
  toc: { title: "Na tej stronie" },
};
