import type { UIStringsOverride } from "../i18n-ui.ts";

/** Romanian (ro) UI strings. */
export const ro: UIStringsOverride = {
  actions: {
    addToCursor: "Adaugă în Cursor",
    addToVscode: "Adaugă în VS Code",
    askAboutCode: "Întreabă despre acest cod",
    connectMcp: "Conectează-te la MCP",
    copied: "Copiat!",
    copyClaudeCode: "Copiază comanda Claude Code",
    copyCode: "Copiază codul",
    copyCodex: "Copiază comanda Codex",
    copyFailed: "Copierea a eșuat",
    copyMarkdown: "Copiază ca Markdown",
    copyServerUrl: "Copiază URL-ul serverului",
    edit: "Editează pe GitHub",
    export: "Exportă",
    exportEpub: "Exportă ca EPUB",
    exportPdf: "Exportă ca PDF",
    generating: "Se generează…",
    openIn: "Deschide în {name}",
    openInChat: "Deschide în chat",
    openInChatPrompt:
      "Citește {url} ca să îți pot pune întrebări despre această pagină.",
    scrollToTop: "Sus de tot",
  },
  assistant: {
    ai: "AI",
    clear: "Șterge conversația",
    close: "Închide",
    copy: "Copiază conversația",
    empty: "Pune o întrebare despre documentație.",
    error: "Ne pare rău, ceva nu a mers bine.",
    explainCode: "Explică acest cod.",
    label: "Pune o întrebare",
    open: "Deschide asistentul",
    placeholder: "Pune o întrebare…",
    rateLimited:
      "Ai pus multe întrebări. Încearcă din nou peste câteva minute.",
    removeCode: "Elimină codul",
    send: "Trimite",
    support: "Contactează asistența",
    supportSubject: "Întrebare din documentație",
    tip: "Sfat: Poți deschide și închide chatul cu",
    title: "Asistent",
    verifyFailed: "Nu am putut verifica faptul că ești om. Încearcă din nou.",
    you: "Tu",
  },
  banner: { dismiss: "Închide anunțul" },
  changelog: {
    description: "Actualizări ale produsului și note de lansare.",
    title: "Jurnal de modificări",
  },
  consent: {
    accept: "Accept",
    decline: "Refuz",
    label: "Consimțământ pentru cookie-uri",
    message:
      "Am dori să folosim cookie-uri pentru a înțelege cum este folosită această documentație.",
    policy: "Politica de confidențialitate",
    settings: "Setări cookie-uri",
  },
  content: {
    code: "Cod",
    copyColor: "Copiază culoarea {name} {value}",
    copyPrompt: "Copiază promptul",
    default: "Implicit",
    diagramError: "Nu s-a putut reda această diagramă.",
    forks: "Fork-uri",
    preview: "Previzualizare",
    prop: "Proprietate",
    selectTab: "Selectează fila",
    selectView: "Selectează vizualizarea",
    showLess: "Afișează mai puțin",
    showMore: "Afișează mai mult",
    stars: "Stele",
    tab: "Fila {n}",
    type: "Tip",
    update: "Actualizare",
  },
  feedback: {
    comment: "Spune-ne mai multe (opțional)",
    no: "Nu",
    question: "Ți-a fost utilă această pagină?",
    send: "Trimite",
    thanks: "Mulțumim pentru feedback!",
    yes: "Da",
  },
  languageSwitcher: { label: "Limbă", untranslated: "Netradus" },
  narration: {
    cueDanger: "Pericol.",
    cueInfo: "Informație.",
    cueNote: "Notă.",
    cueSection: "Secțiune extensibilă.",
    cueStep: "Pasul {n}.",
    cueSuccess: "Succes.",
    cueTab: "Fila {title}.",
    cueTip: "Sfat.",
    cueWarning: "Avertisment.",
    error: "Nu s-a putut încărca lectura audio.",
    follow: "Urmărește lectura",
    label: "Ascultă această pagină",
    minutes: "{n} min",
    next: "Propoziția următoare",
    pause: "Pauză",
    play: "Redă",
    previous: "Propoziția anterioară",
    progress: "Progresul lecturii",
    speed: "Viteza de redare",
    stop: "Oprește ascultarea",
  },
  nav: {
    back: "Înapoi",
    breadcrumb: "Cale de navigare",
    closeNavigation: "Închide navigarea",
    deprecated: "învechit",
    featured: "Recomandate",
    githubRepository: "Depozit GitHub",
    navigation: "Navigare",
    opensInNewTab: "Se deschide într-o filă nouă",
    primary: "Principal",
    sections: "Secțiuni",
    toggleNavigation: "Comută navigarea",
    toggleTheme: "Comută tema de culoare",
  },
  notFound: {
    description: "Nu am găsit pagina pe care o cauți.",
    home: "Înapoi la pagina principală",
    title: "Pagina nu a fost găsită",
  },
  page: {
    lastUpdated: "Ultima actualizare",
    next: "Următorul",
    pagination: "Paginare",
    previous: "Anteriorul",
    related: "Pagini conexe",
    skipToContent: "Sari la conținut",
  },
  search: {
    all: "Toate",
    allLanguages: "Toate limbile",
    assistant: "Asistent",
    assistantHint: "Primește un răspuns instantaneu de la AI",
    button: "Caută",
    devOnly: "Căutarea este disponibilă în versiunea de producție.",
    docs: "Documentație",
    error: "Ceva nu a mers bine. Încearcă din nou.",
    label: "Caută în documentație",
    latest: "cea mai recentă",
    navigate: "navighează",
    noResults: "Niciun rezultat găsit.",
    open: "deschide",
    placeholder: "Caută în documentație…",
    popular: "Populare",
    preview: "previzualizează",
    results: "Rezultate",
  },
  toc: { title: "Pe această pagină" },
};
