import type { UIStringsOverride } from "../i18n-ui.ts";

/** Russian (ru) UI strings. */
export const ru: UIStringsOverride = {
  actions: {
    addToCursor: "Добавить в Cursor",
    addToVscode: "Добавить в VS Code",
    askAboutCode: "Спросить об этом коде",
    connectMcp: "Подключиться к MCP",
    copied: "Скопировано!",
    copyClaudeCode: "Скопировать команду Claude Code",
    copyCode: "Скопировать код",
    copyCodex: "Скопировать команду Codex",
    copyFailed: "Не удалось скопировать",
    copyMarkdown: "Скопировать как Markdown",
    copyServerUrl: "Скопировать URL сервера",
    edit: "Редактировать на GitHub",
    export: "Экспорт",
    exportEpub: "Экспорт в EPUB",
    exportPdf: "Экспорт в PDF",
    generating: "Генерация…",
    openIn: "Открыть в {name}",
    openInChat: "Открыть в чате",
    openInChatPrompt:
      "Прочитайте {url} — я буду задавать вопросы об этой странице.",
    scrollToTop: "Наверх",
  },
  assistant: {
    ai: "ИИ",
    clear: "Очистить беседу",
    close: "Закрыть",
    copy: "Скопировать беседу",
    empty: "Задайте вопрос по документации.",
    error: "Извините, что-то пошло не так.",
    explainCode: "Объясни этот код.",
    label: "Задать вопрос",
    placeholder: "Задайте вопрос…",
    rateLimited:
      "Вы задали много вопросов. Попробуйте снова через несколько минут.",
    removeCode: "Убрать код",
    send: "Отправить",
    support: "Связаться с поддержкой",
    supportSubject: "Вопрос из документации",
    tip: "Совет: чат можно открыть и закрыть с помощью",
    title: "Ассистент",
    verifyFailed: "Не удалось подтвердить, что вы человек. Попробуйте снова.",
    you: "Вы",
  },
  banner: { dismiss: "Закрыть объявление" },
  changelog: {
    description: "Обновления продукта и примечания к выпускам.",
    title: "Журнал изменений",
  },
  consent: {
    accept: "Принять",
    decline: "Отклонить",
    label: "Согласие на cookie",
    message:
      "Мы хотели бы использовать файлы cookie, чтобы понимать, как используется эта документация.",
    policy: "Политика конфиденциальности",
    settings: "Настройки cookie",
  },
  content: {
    code: "Код",
    copyColor: "Скопировать цвет {name} {value}",
    copyPrompt: "Скопировать промпт",
    default: "По умолчанию",
    diagramError: "Не удалось отобразить эту диаграмму.",
    forks: "Форки",
    preview: "Предпросмотр",
    prop: "Свойство",
    selectTab: "Выбрать вкладку",
    selectView: "Выбрать представление",
    showLess: "Показать меньше",
    showMore: "Показать ещё",
    stars: "Звёзды",
    tab: "Вкладка {n}",
    type: "Тип",
    update: "Обновление",
  },
  feedback: {
    comment: "Расскажите подробнее (необязательно)",
    no: "Нет",
    question: "Эта страница была полезной?",
    send: "Отправить",
    thanks: "Спасибо за ваш отзыв!",
    yes: "Да",
  },
  languageSwitcher: { label: "Язык", untranslated: "Не переведено" },
  narration: {
    cueDanger: "Опасность.",
    cueInfo: "Информация.",
    cueNote: "Примечание.",
    cueSection: "Раскрывающийся раздел.",
    cueStep: "Шаг {n}.",
    cueSuccess: "Успех.",
    cueTab: "Вкладка {title}.",
    cueTip: "Совет.",
    cueWarning: "Предупреждение.",
    error: "Не удалось загрузить озвучку.",
    follow: "Следить за чтением",
    label: "Прослушать страницу",
    minutes: "{n} мин",
    next: "Следующее предложение",
    pause: "Пауза",
    play: "Воспроизвести",
    previous: "Предыдущее предложение",
    progress: "Ход воспроизведения",
    speed: "Скорость воспроизведения",
    stop: "Остановить прослушивание",
  },
  nav: {
    back: "Назад",
    breadcrumb: "Навигационная цепочка",
    closeNavigation: "Закрыть навигацию",
    deprecated: "устарело",
    featured: "Рекомендуемое",
    githubRepository: "Репозиторий GitHub",
    navigation: "Навигация",
    opensInNewTab: "Открывается в новой вкладке",
    primary: "Основное",
    sections: "Разделы",
    toggleNavigation: "Переключить навигацию",
    toggleTheme: "Переключить цветовую тему",
  },
  notFound: {
    description: "Не удалось найти страницу, которую вы ищете.",
    home: "Вернуться на главную",
    title: "Страница не найдена",
  },
  page: {
    lastUpdated: "Последнее обновление",
    next: "Далее",
    pagination: "Пагинация",
    previous: "Назад",
    related: "Связанные страницы",
    skipToContent: "Перейти к содержимому",
  },
  search: {
    all: "Все",
    allLanguages: "Все языки",
    assistant: "Ассистент",
    assistantHint: "Получите мгновенный ответ от ИИ",
    button: "Поиск",
    devOnly: "Поиск доступен в production-сборке.",
    docs: "Документация",
    error: "Что-то пошло не так. Попробуйте ещё раз.",
    label: "Поиск по документации",
    latest: "последняя",
    navigate: "навигация",
    noResults: "Ничего не найдено.",
    open: "открыть",
    placeholder: "Поиск по документации…",
    popular: "Популярное",
    preview: "предпросмотр",
    results: "Результаты",
  },
  toc: { title: "На этой странице" },
};
