import type { UIStringsOverride } from "../i18n-ui.ts";

/** Slovak (sk) UI strings. */
export const sk: UIStringsOverride = {
  actions: {
    addToCursor: "Pridať do Cursoru",
    addToVscode: "Pridať do VS Code",
    askAboutCode: "Opýtať sa na tento kód",
    connectMcp: "Pripojiť k MCP",
    copied: "Skopírované!",
    copyClaudeCode: "Kopírovať príkaz Claude Code",
    copyCode: "Kopírovať kód",
    copyCodex: "Kopírovať príkaz Codex",
    copyFailed: "Kopírovanie zlyhalo",
    copyMarkdown: "Kopírovať ako Markdown",
    copyServerUrl: "Kopírovať URL servera",
    edit: "Upraviť na GitHube",
    export: "Exportovať",
    exportEpub: "Exportovať do EPUB",
    exportPdf: "Exportovať do PDF",
    generating: "Generovanie…",
    openIn: "Otvoriť v {name}",
    openInChat: "Otvoriť v chate",
    openInChatPrompt: "Prečítajte si {url} — budem sa pýtať na túto stránku.",
    scrollToTop: "Späť nahor",
  },
  assistant: {
    ai: "AI",
    clear: "Vymazať konverzáciu",
    close: "Zavrieť",
    copy: "Kopírovať konverzáciu",
    empty: "Opýtajte sa na dokumentáciu.",
    error: "Ospravedlňujeme sa, niečo sa pokazilo.",
    explainCode: "Vysvetli tento kód.",
    label: "Položiť otázku",
    placeholder: "Položiť otázku…",
    rateLimited: "Položili ste veľa otázok. Skúste to znova o pár minút.",
    removeCode: "Odstrániť kód",
    send: "Odoslať",
    support: "Kontaktovať podporu",
    supportSubject: "Otázka z dokumentácie",
    tip: "Tip: Chat môžete otvoriť a zavrieť pomocou",
    title: "Asistent",
    verifyFailed: "Nepodarilo sa overiť, že ste človek. Skúste to znova.",
    you: "Vy",
  },
  banner: { dismiss: "Zavrieť oznámenie" },
  changelog: {
    description: "Novinky produktu a poznámky k vydaniu.",
    title: "Zoznam zmien",
  },
  consent: {
    accept: "Prijať",
    decline: "Odmietnuť",
    label: "Súhlas so súbormi cookie",
    message:
      "Radi by sme používali súbory cookie, aby sme pochopili, ako sa táto dokumentácia používa.",
    policy: "Zásady ochrany osobných údajov",
    settings: "Nastavenia súborov cookie",
  },
  content: {
    code: "Kód",
    copyColor: "Kopírovať farbu {name} {value}",
    copyPrompt: "Kopírovať prompt",
    default: "Predvolené",
    diagramError: "Tento diagram sa nepodarilo vykresliť.",
    forks: "Forky",
    preview: "Náhľad",
    prop: "Vlastnosť",
    selectTab: "Vybrať kartu",
    selectView: "Vybrať zobrazenie",
    showLess: "Zobraziť menej",
    showMore: "Zobraziť viac",
    stars: "Hviezdičky",
    tab: "Karta {n}",
    type: "Typ",
    update: "Aktualizácia",
  },
  feedback: {
    comment: "Povedzte nám viac (nepovinné)",
    no: "Nie",
    question: "Bola táto stránka užitočná?",
    send: "Odoslať",
    thanks: "Ďakujeme za vašu spätnú väzbu!",
    yes: "Áno",
  },
  languageSwitcher: { label: "Jazyk", untranslated: "Nepreložené" },
  narration: {
    cueDanger: "Nebezpečenstvo.",
    cueInfo: "Informácia.",
    cueNote: "Poznámka.",
    cueSection: "Rozbaľovacia sekcia.",
    cueStep: "Krok {n}.",
    cueSuccess: "Úspech.",
    cueTab: "Karta {title}.",
    cueTip: "Tip.",
    cueWarning: "Upozornenie.",
    error: "Nahovorenú verziu sa nepodarilo načítať.",
    follow: "Sledovať čítanie",
    label: "Vypočuť si túto stránku",
    minutes: "{n} min",
    next: "Ďalšia veta",
    pause: "Pozastaviť",
    play: "Prehrať",
    previous: "Predchádzajúca veta",
    progress: "Priebeh prehrávania",
    speed: "Rýchlosť prehrávania",
    stop: "Ukončiť počúvanie",
  },
  nav: {
    back: "Späť",
    breadcrumb: "Omrvinková navigácia",
    closeNavigation: "Zavrieť navigáciu",
    deprecated: "zastarané",
    featured: "Odporúčané",
    githubRepository: "Repozitár na GitHube",
    navigation: "Navigácia",
    opensInNewTab: "Otvorí sa na novej karte",
    primary: "Hlavné",
    sections: "Sekcie",
    toggleNavigation: "Prepnúť navigáciu",
    toggleTheme: "Prepnúť farebný motív",
  },
  notFound: {
    description: "Stránku, ktorú hľadáte, sa nepodarilo nájsť.",
    home: "Späť na úvodnú stránku",
    title: "Stránka sa nenašla",
  },
  page: {
    lastUpdated: "Naposledy aktualizované",
    next: "Ďalej",
    pagination: "Stránkovanie",
    previous: "Predchádzajúce",
    related: "Súvisiace stránky",
    skipToContent: "Prejsť na obsah",
  },
  search: {
    all: "Všetko",
    allLanguages: "Všetky jazyky",
    assistant: "Asistent",
    assistantHint: "Získajte okamžitú odpoveď od AI",
    button: "Hľadať",
    devOnly: "Vyhľadávanie je dostupné v produkčnom builde.",
    docs: "Dokumentácia",
    error: "Niečo sa pokazilo. Skúste to znova.",
    label: "Prehľadať dokumentáciu",
    latest: "najnovšia",
    navigate: "navigácia",
    noResults: "Nenašli sa žiadne výsledky.",
    open: "otvoriť",
    placeholder: "Prehľadať dokumentáciu…",
    popular: "Populárne",
    preview: "náhľad",
    results: "Výsledky",
  },
  toc: { title: "Na tejto stránke" },
};
