import type { UIStringsOverride } from "../i18n-ui.ts";

/** Serbian (sr) UI strings. */
export const sr: UIStringsOverride = {
  actions: {
    addToCursor: "Додај у Cursor",
    addToVscode: "Додај у VS Code",
    askAboutCode: "Питај о овом коду",
    connectMcp: "Повежи се са MCP-ом",
    copied: "Копирано!",
    copyClaudeCode: "Копирај Claude Code команду",
    copyCode: "Копирај код",
    copyCodex: "Копирај Codex команду",
    copyFailed: "Копирање није успело",
    copyMarkdown: "Копирај као Markdown",
    copyServerUrl: "Копирај URL сервера",
    edit: "Уреди на GitHub-у",
    export: "Извези",
    exportEpub: "Извези у EPUB",
    exportPdf: "Извези у PDF",
    generating: "Генерисање…",
    openIn: "Отвори у {name}",
    openInChat: "Отвори у ћаскању",
    openInChatPrompt: "Прочитајте {url} — постављаћу питања о овој страници.",
    scrollToTop: "Назад на врх",
  },
  assistant: {
    ai: "AI",
    clear: "Обриши разговор",
    close: "Затвори",
    copy: "Копирај разговор",
    empty: "Поставите питање о документацији.",
    error: "Жао нам је, нешто је пошло наопако.",
    explainCode: "Објасни овај код.",
    label: "Постави питање",
    placeholder: "Поставите питање…",
    rateLimited:
      "Поставили сте много питања. Покушајте поново за неколико минута.",
    removeCode: "Уклони код",
    send: "Пошаљи",
    support: "Контактирај подршку",
    supportSubject: "Питање из документације",
    tip: "Савет: Ћаскање можете отворити и затворити помоћу",
    title: "Асистент",
    verifyFailed: "Нисмо могли да потврдимо да сте човек. Покушајте поново.",
    you: "Ви",
  },
  banner: { dismiss: "Затвори обавештење" },
  changelog: {
    description: "Ажурирања производа и белешке о издањима.",
    title: "Дневник измена",
  },
  consent: {
    accept: "Прихвати",
    decline: "Одбиј",
    label: "Сагласност за колачиће",
    message:
      "Желели бисмо да користимо колачиће како бисмо разумели како се ова документација користи.",
    policy: "Политика приватности",
    settings: "Подешавања колачића",
  },
  content: {
    code: "Код",
    copyColor: "Копирај боју {name} {value}",
    copyPrompt: "Копирај упит",
    default: "Подразумевано",
    diagramError: "Није могуће приказати овај дијаграм.",
    forks: "Форкови",
    preview: "Преглед",
    prop: "Својство",
    selectTab: "Изабери картицу",
    selectView: "Изабери приказ",
    showLess: "Прикажи мање",
    showMore: "Прикажи више",
    stars: "Звездице",
    tab: "Картица {n}",
    type: "Тип",
    update: "Ажурирање",
  },
  feedback: {
    comment: "Реците нам више (опционо)",
    no: "Не",
    question: "Да ли вам је ова страница помогла?",
    send: "Пошаљи",
    thanks: "Хвала на вашој повратној информацији!",
    yes: "Да",
  },
  languageSwitcher: { label: "Језик", untranslated: "Није преведено" },
  narration: {
    cueDanger: "Опасност.",
    cueInfo: "Информација.",
    cueNote: "Напомена.",
    cueSection: "Проширив одељак.",
    cueStep: "Корак {n}.",
    cueSuccess: "Успех.",
    cueTab: "Картица {title}.",
    cueTip: "Савет.",
    cueWarning: "Упозорење.",
    error: "Није могуће учитати звучну верзију.",
    follow: "Прати читање",
    label: "Послушај ову страницу",
    minutes: "{n} мин",
    next: "Следећа реченица",
    pause: "Паузирај",
    play: "Пусти",
    previous: "Претходна реченица",
    progress: "Напредак читања",
    speed: "Брзина репродукције",
    stop: "Заустави слушање",
  },
  nav: {
    back: "Назад",
    breadcrumb: "Путања навигације",
    closeNavigation: "Затвори навигацију",
    deprecated: "застарело",
    featured: "Истакнуто",
    githubRepository: "GitHub репозиторијум",
    navigation: "Навигација",
    opensInNewTab: "Отвара се у новој картици",
    primary: "Главна",
    sections: "Одељци",
    toggleNavigation: "Отвори или затвори навигацију",
    toggleTheme: "Промени тему боја",
  },
  notFound: {
    description: "Нисмо могли да пронађемо страницу коју тражите.",
    home: "Назад на почетну",
    title: "Страница није пронађена",
  },
  page: {
    lastUpdated: "Последње ажурирање",
    next: "Следеће",
    pagination: "Пагинација",
    previous: "Претходно",
    related: "Сродне странице",
    skipToContent: "Пређи на садржај",
  },
  search: {
    all: "Све",
    allLanguages: "Сви језици",
    assistant: "Асистент",
    assistantHint: "Добијте тренутан одговор од AI-ја",
    button: "Претражи",
    devOnly: "Претрага је доступна у продукцијској верзији.",
    docs: "Документација",
    error: "Нешто је пошло наопако. Покушајте поново.",
    label: "Претражи документацију",
    latest: "најновија",
    navigate: "навигација",
    noResults: "Нема резултата.",
    open: "отвори",
    placeholder: "Претражи документацију…",
    popular: "Популарно",
    preview: "преглед",
    results: "Резултати",
  },
  toc: { title: "На овој страници" },
};
