import type { UIStringsOverride } from "../i18n-ui.ts";

/** Swedish (sv) UI strings. */
export const sv: UIStringsOverride = {
  actions: {
    addToCursor: "Lägg till i Cursor",
    addToVscode: "Lägg till i VS Code",
    askAboutCode: "Fråga om den här koden",
    connectMcp: "Anslut till MCP",
    copied: "Kopierat!",
    copyClaudeCode: "Kopiera Claude Code-kommando",
    copyCode: "Kopiera kod",
    copyCodex: "Kopiera Codex-kommando",
    copyFailed: "Kopiering misslyckades",
    copyMarkdown: "Kopiera som Markdown",
    copyServerUrl: "Kopiera server-URL",
    edit: "Redigera på GitHub",
    export: "Exportera",
    exportEpub: "Exportera till EPUB",
    exportPdf: "Exportera till PDF",
    generating: "Genererar…",
    openIn: "Öppna i {name}",
    openInChat: "Öppna i chatt",
    openInChatPrompt:
      "Läs {url} så att jag kan ställa frågor om den här sidan.",
    scrollToTop: "Till toppen",
  },
  assistant: {
    ai: "AI",
    clear: "Rensa konversationen",
    close: "Stäng",
    copy: "Kopiera konversationen",
    empty: "Ställ en fråga om dokumentationen.",
    error: "Tyvärr, något gick fel.",
    explainCode: "Förklara den här koden.",
    label: "Ställ en fråga",
    placeholder: "Ställ en fråga…",
    rateLimited: "Du har ställt många frågor. Försök igen om några minuter.",
    removeCode: "Ta bort koden",
    send: "Skicka",
    support: "Kontakta support",
    supportSubject: "Fråga från dokumentationen",
    tip: "Tips: Du kan öppna och stänga chatten med",
    title: "Assistent",
    verifyFailed: "Vi kunde inte bekräfta att du är en människa. Försök igen.",
    you: "Du",
  },
  banner: { dismiss: "Stäng meddelandet" },
  changelog: {
    description: "Produktuppdateringar och versionsinformation.",
    title: "Ändringslogg",
  },
  consent: {
    accept: "Godkänn",
    decline: "Avvisa",
    label: "Samtycke till cookies",
    message:
      "Vi vill gärna använda cookies för att förstå hur den här dokumentationen används.",
    policy: "Integritetspolicy",
    settings: "Cookieinställningar",
  },
  content: {
    code: "Kod",
    copyColor: "Kopiera färgen {name} {value}",
    copyPrompt: "Kopiera prompt",
    default: "Standard",
    diagramError: "Det här diagrammet kunde inte visas.",
    forks: "Forkar",
    preview: "Förhandsgranskning",
    prop: "Egenskap",
    selectTab: "Välj flik",
    selectView: "Välj vy",
    showLess: "Visa mindre",
    showMore: "Visa mer",
    stars: "Stjärnor",
    tab: "Flik {n}",
    type: "Typ",
    update: "Uppdatering",
  },
  feedback: {
    comment: "Berätta mer (valfritt)",
    no: "Nej",
    question: "Var den här sidan till hjälp?",
    send: "Skicka",
    thanks: "Tack för din feedback!",
    yes: "Ja",
  },
  languageSwitcher: { label: "Språk", untranslated: "Inte översatt" },
  narration: {
    cueDanger: "Fara.",
    cueInfo: "Info.",
    cueNote: "Observera.",
    cueSection: "Expanderbart avsnitt.",
    cueStep: "Steg {n}.",
    cueSuccess: "Klart.",
    cueTab: "Fliken {title}.",
    cueTip: "Tips.",
    cueWarning: "Varning.",
    error: "Uppläsningen kunde inte läsas in.",
    follow: "Följ med",
    label: "Lyssna på den här sidan",
    minutes: "{n} min",
    next: "Nästa mening",
    pause: "Pausa",
    play: "Spela upp",
    previous: "Föregående mening",
    progress: "Uppläsningens förlopp",
    speed: "Uppspelningshastighet",
    stop: "Sluta lyssna",
  },
  nav: {
    back: "Tillbaka",
    breadcrumb: "Brödsmulor",
    closeNavigation: "Stäng navigeringen",
    deprecated: "utfasad",
    featured: "Utvalda",
    githubRepository: "GitHub-repository",
    navigation: "Navigering",
    opensInNewTab: "Öppnas i en ny flik",
    primary: "Primär",
    sections: "Avsnitt",
    toggleNavigation: "Växla navigering",
    toggleTheme: "Växla färgtema",
  },
  notFound: {
    description: "Vi kunde inte hitta sidan du letar efter.",
    home: "Tillbaka till startsidan",
    title: "Sidan hittades inte",
  },
  page: {
    lastUpdated: "Senast uppdaterad",
    next: "Nästa",
    pagination: "Paginering",
    previous: "Föregående",
    related: "Relaterade sidor",
    skipToContent: "Hoppa till innehåll",
  },
  search: {
    all: "Alla",
    allLanguages: "Alla språk",
    assistant: "Assistent",
    assistantHint: "Få ett omedelbart svar från AI",
    button: "Sök",
    devOnly: "Sökning är tillgänglig i produktionsbygget.",
    docs: "Dokumentation",
    error: "Något gick fel. Försök igen.",
    label: "Sök i dokumentationen",
    latest: "senaste",
    navigate: "navigera",
    noResults: "Inga resultat hittades.",
    open: "öppna",
    placeholder: "Sök i dokumentationen…",
    popular: "Populärt",
    preview: "förhandsvisa",
    results: "Resultat",
  },
  toc: { title: "På den här sidan" },
};
