import type { UIStringsOverride } from "../i18n-ui.ts";

/** Thai (th) UI strings. */
export const th: UIStringsOverride = {
  actions: {
    addToCursor: "เพิ่มไปยัง Cursor",
    addToVscode: "เพิ่มไปยัง VS Code",
    askAboutCode: "ถามเกี่ยวกับโค้ดนี้",
    connectMcp: "เชื่อมต่อกับ MCP",
    copied: "คัดลอกแล้ว!",
    copyClaudeCode: "คัดลอกคำสั่ง Claude Code",
    copyCode: "คัดลอกโค้ด",
    copyCodex: "คัดลอกคำสั่ง Codex",
    copyFailed: "คัดลอกไม่สำเร็จ",
    copyMarkdown: "คัดลอกเป็น Markdown",
    copyServerUrl: "คัดลอก URL ของเซิร์ฟเวอร์",
    edit: "แก้ไขบน GitHub",
    export: "ส่งออก",
    exportEpub: "ส่งออกเป็น EPUB",
    exportPdf: "ส่งออกเป็น PDF",
    generating: "กำลังสร้าง…",
    openIn: "เปิดใน {name}",
    openInChat: "เปิดในแชท",
    openInChatPrompt: "อ่าน {url} เพื่อให้ฉันถามคำถามเกี่ยวกับหน้านี้ได้",
    scrollToTop: "กลับไปด้านบน",
  },
  assistant: {
    ai: "AI",
    clear: "ล้างการสนทนา",
    close: "ปิด",
    copy: "คัดลอกการสนทนา",
    empty: "ถามคำถามเกี่ยวกับเอกสาร",
    error: "ขออภัย เกิดข้อผิดพลาดบางอย่าง",
    explainCode: "อธิบายโค้ดนี้",
    label: "ถามคำถาม",
    placeholder: "ถามคำถาม…",
    rateLimited: "คุณถามคำถามจำนวนมากแล้ว โปรดลองอีกครั้งในอีกไม่กี่นาที",
    removeCode: "นำโค้ดออก",
    send: "ส่ง",
    support: "ติดต่อฝ่ายสนับสนุน",
    supportSubject: "คำถามจากเอกสาร",
    tip: "เคล็ดลับ: คุณสามารถเปิดและปิดแชทได้ด้วย",
    title: "ผู้ช่วย",
    verifyFailed: "เราไม่สามารถยืนยันได้ว่าคุณเป็นมนุษย์ โปรดลองอีกครั้ง",
    you: "คุณ",
  },
  banner: { dismiss: "ปิดประกาศ" },
  changelog: {
    description: "อัปเดตผลิตภัณฑ์และบันทึกประจำรุ่น",
    title: "บันทึกการเปลี่ยนแปลง",
  },
  consent: {
    accept: "ยอมรับ",
    decline: "ปฏิเสธ",
    label: "ความยินยอมคุกกี้",
    message: "เราต้องการใช้คุกกี้เพื่อทำความเข้าใจว่าเอกสารนี้ถูกใช้งานอย่างไร",
    policy: "นโยบายความเป็นส่วนตัว",
    settings: "การตั้งค่าคุกกี้",
  },
  content: {
    code: "โค้ด",
    copyColor: "คัดลอกสี {name} {value}",
    copyPrompt: "คัดลอกพรอมต์",
    default: "ค่าเริ่มต้น",
    diagramError: "ไม่สามารถแสดงไดอะแกรมนี้ได้",
    forks: "ฟอร์ก",
    preview: "ตัวอย่าง",
    prop: "คุณสมบัติ",
    selectTab: "เลือกแท็บ",
    selectView: "เลือกมุมมอง",
    showLess: "แสดงน้อยลง",
    showMore: "แสดงเพิ่มเติม",
    stars: "ดาว",
    tab: "แท็บ {n}",
    type: "ชนิด",
    update: "อัปเดต",
  },
  feedback: {
    comment: "บอกเราเพิ่มเติม (ไม่บังคับ)",
    no: "ไม่",
    question: "หน้านี้มีประโยชน์หรือไม่?",
    send: "ส่ง",
    thanks: "ขอบคุณสำหรับความคิดเห็นของคุณ!",
    yes: "ใช่",
  },
  languageSwitcher: { label: "ภาษา", untranslated: "ยังไม่ได้แปล" },
  narration: {
    cueDanger: "อันตราย",
    cueInfo: "ข้อมูล",
    cueNote: "หมายเหตุ",
    cueSection: "ส่วนที่ขยายได้",
    cueStep: "ขั้นตอนที่ {n}",
    cueSuccess: "สำเร็จ",
    cueTab: "แท็บ {title}",
    cueTip: "เคล็ดลับ",
    cueWarning: "คำเตือน",
    error: "ไม่สามารถโหลดเสียงบรรยายได้",
    follow: "ติดตามการอ่าน",
    label: "ฟังหน้านี้",
    minutes: "{n} นาที",
    next: "ประโยคถัดไป",
    pause: "หยุดชั่วคราว",
    play: "เล่น",
    previous: "ประโยคก่อนหน้า",
    progress: "ความคืบหน้าการบรรยาย",
    speed: "ความเร็วในการเล่น",
    stop: "หยุดฟัง",
  },
  nav: {
    back: "ย้อนกลับ",
    breadcrumb: "เส้นทางนำทาง",
    closeNavigation: "ปิดการนำทาง",
    deprecated: "เลิกใช้แล้ว",
    featured: "แนะนำ",
    githubRepository: "ที่เก็บ GitHub",
    navigation: "การนำทาง",
    opensInNewTab: "เปิดในแท็บใหม่",
    primary: "หลัก",
    sections: "หมวด",
    toggleNavigation: "สลับการนำทาง",
    toggleTheme: "สลับธีมสี",
  },
  notFound: {
    description: "เราไม่พบหน้าที่คุณกำลังมองหา",
    home: "กลับไปหน้าแรก",
    title: "ไม่พบหน้า",
  },
  page: {
    lastUpdated: "อัปเดตล่าสุดเมื่อ",
    next: "ถัดไป",
    pagination: "การแบ่งหน้า",
    previous: "ก่อนหน้า",
    related: "หน้าที่เกี่ยวข้อง",
    skipToContent: "ข้ามไปยังเนื้อหา",
  },
  search: {
    all: "ทั้งหมด",
    allLanguages: "ทุกภาษา",
    assistant: "ผู้ช่วย",
    assistantHint: "รับคำตอบทันทีจาก AI",
    button: "ค้นหา",
    devOnly: "การค้นหาพร้อมใช้งานในบิลด์โปรดักชัน",
    docs: "เอกสาร",
    error: "เกิดข้อผิดพลาดบางอย่าง โปรดลองอีกครั้ง",
    label: "ค้นหาเอกสาร",
    latest: "ล่าสุด",
    navigate: "นำทาง",
    noResults: "ไม่พบผลลัพธ์",
    open: "เปิด",
    placeholder: "ค้นหาเอกสาร…",
    popular: "ยอดนิยม",
    preview: "ดูตัวอย่าง",
    results: "ผลลัพธ์",
  },
  toc: { title: "ในหน้านี้" },
};
