import type { UIStringsOverride } from "../i18n-ui.ts";

/** Turkish (tr) UI strings. */
export const tr: UIStringsOverride = {
  actions: {
    addToCursor: "Cursor'a ekle",
    addToVscode: "VS Code'a ekle",
    askAboutCode: "Bu kod hakkında sor",
    connectMcp: "MCP'ye bağlan",
    copied: "Kopyalandı!",
    copyClaudeCode: "Claude Code komutunu kopyala",
    copyCode: "Kodu kopyala",
    copyCodex: "Codex komutunu kopyala",
    copyFailed: "Kopyalama başarısız oldu",
    copyMarkdown: "Markdown olarak kopyala",
    copyServerUrl: "Sunucu URL'sini kopyala",
    edit: "GitHub'da düzenle",
    export: "Dışa aktar",
    exportEpub: "EPUB olarak dışa aktar",
    exportPdf: "PDF olarak dışa aktar",
    generating: "Oluşturuluyor…",
    openIn: "{name} içinde aç",
    openInChat: "Sohbette aç",
    openInChatPrompt:
      "Bu sayfa hakkında sorular sorabilmem için {url} adresini okuyun.",
    scrollToTop: "Başa dön",
  },
  assistant: {
    ai: "Yapay zekâ",
    clear: "Konuşmayı temizle",
    close: "Kapat",
    copy: "Konuşmayı kopyala",
    empty: "Belgeler hakkında bir soru sorun.",
    error: "Üzgünüz, bir şeyler ters gitti.",
    explainCode: "Bu kodu açıkla.",
    label: "Bir soru sorun",
    open: "Asistanı aç",
    placeholder: "Bir soru sorun…",
    rateLimited:
      "Çok sayıda soru sordunuz. Birkaç dakika sonra yeniden deneyin.",
    removeCode: "Kodu kaldır",
    send: "Gönder",
    support: "Destekle iletişime geç",
    supportSubject: "Belgelerden soru",
    tip: "İpucu: Sohbeti şu tuşla açıp kapatabilirsiniz:",
    title: "Asistan",
    verifyFailed: "İnsan olduğunuzu doğrulayamadık. Yeniden deneyin.",
    you: "Siz",
  },
  banner: { dismiss: "Duyuruyu kapat" },
  changelog: {
    description: "Ürün güncellemeleri ve sürüm notları.",
    title: "Değişiklik günlüğü",
  },
  consent: {
    accept: "Kabul et",
    decline: "Reddet",
    label: "Çerez onayı",
    message:
      "Bu belgelerin nasıl kullanıldığını anlamak için çerez kullanmak istiyoruz.",
    policy: "Gizlilik politikası",
    settings: "Çerez ayarları",
  },
  content: {
    code: "Kod",
    copyColor: "Rengi kopyala: {name} {value}",
    copyPrompt: "İstemi kopyala",
    default: "Varsayılan",
    diagramError: "Bu diyagram görüntülenemedi.",
    forks: "Çatallar",
    preview: "Önizleme",
    prop: "Özellik",
    selectTab: "Sekme seç",
    selectView: "Görünüm seç",
    showLess: "Daha az göster",
    showMore: "Daha fazla göster",
    stars: "Yıldızlar",
    tab: "Sekme {n}",
    type: "Tür",
    update: "Güncelleme",
  },
  feedback: {
    comment: "Bize daha fazlasını anlatın (isteğe bağlı)",
    no: "Hayır",
    question: "Bu sayfa yardımcı oldu mu?",
    send: "Gönder",
    thanks: "Geri bildiriminiz için teşekkürler!",
    yes: "Evet",
  },
  languageSwitcher: { label: "Dil", untranslated: "Çevrilmemiş" },
  narration: {
    cueDanger: "Tehlike.",
    cueInfo: "Bilgi.",
    cueNote: "Not.",
    cueSection: "Genişletilebilir bölüm.",
    cueStep: "Adım {n}.",
    cueSuccess: "Başarılı.",
    cueTab: "{title} sekmesi.",
    cueTip: "İpucu.",
    cueWarning: "Uyarı.",
    error: "Seslendirme yüklenemedi.",
    follow: "Okumayı takip et",
    label: "Bu sayfayı dinle",
    minutes: "{n} dk",
    next: "Sonraki cümle",
    pause: "Duraklat",
    play: "Oynat",
    previous: "Önceki cümle",
    progress: "Seslendirme ilerlemesi",
    speed: "Oynatma hızı",
    stop: "Dinlemeyi durdur",
  },
  nav: {
    back: "Geri",
    breadcrumb: "Gezinme yolu",
    closeNavigation: "Gezinmeyi kapat",
    deprecated: "kullanımdan kaldırıldı",
    featured: "Öne çıkan",
    githubRepository: "GitHub deposu",
    navigation: "Gezinme",
    opensInNewTab: "Yeni sekmede açılır",
    primary: "Birincil",
    sections: "Bölümler",
    toggleNavigation: "Gezinmeyi aç/kapat",
    toggleTheme: "Renk temasını değiştir",
  },
  notFound: {
    description: "Aradığınız sayfayı bulamadık.",
    home: "Ana sayfaya dön",
    title: "Sayfa bulunamadı",
  },
  page: {
    lastUpdated: "Son güncelleme",
    next: "Sonraki",
    pagination: "Sayfalama",
    previous: "Önceki",
    related: "İlgili sayfalar",
    skipToContent: "İçeriğe geç",
  },
  search: {
    all: "Tümü",
    allLanguages: "Tüm diller",
    assistant: "Asistan",
    assistantHint: "Yapay zekâdan anında yanıt alın",
    button: "Ara",
    devOnly: "Arama, üretim derlemesinde kullanılabilir.",
    docs: "Belgeler",
    error: "Bir şeyler ters gitti. Lütfen tekrar deneyin.",
    label: "Belgelerde ara",
    latest: "en son",
    navigate: "gezin",
    noResults: "Sonuç bulunamadı.",
    open: "aç",
    placeholder: "Belgelerde ara…",
    popular: "Popüler",
    preview: "önizle",
    results: "Sonuçlar",
  },
  toc: { title: "Bu sayfada" },
};
