import type { UIStringsOverride } from "../i18n-ui.ts";

/** Ukrainian (uk) UI strings. */
export const uk: UIStringsOverride = {
  actions: {
    addToCursor: "Додати до Cursor",
    addToVscode: "Додати до VS Code",
    askAboutCode: "Запитати про цей код",
    connectMcp: "Підключитися до MCP",
    copied: "Скопійовано!",
    copyClaudeCode: "Скопіювати команду Claude Code",
    copyCode: "Скопіювати код",
    copyCodex: "Скопіювати команду Codex",
    copyFailed: "Не вдалося скопіювати",
    copyMarkdown: "Скопіювати як Markdown",
    copyServerUrl: "Скопіювати URL сервера",
    edit: "Редагувати на GitHub",
    export: "Експорт",
    exportEpub: "Експорт в EPUB",
    exportPdf: "Експорт у PDF",
    generating: "Генерація…",
    openIn: "Відкрити в {name}",
    openInChat: "Відкрити в чаті",
    openInChatPrompt:
      "Прочитайте {url} — я ставитиму запитання щодо цієї сторінки.",
    scrollToTop: "Нагору",
  },
  assistant: {
    ai: "ШІ",
    clear: "Очистити бесіду",
    close: "Закрити",
    copy: "Скопіювати бесіду",
    empty: "Поставте запитання щодо документації.",
    error: "Вибачте, щось пішло не так.",
    explainCode: "Поясни цей код.",
    label: "Поставити запитання",
    placeholder: "Поставте запитання…",
    rateLimited:
      "Ви поставили багато запитань. Спробуйте знову за кілька хвилин.",
    removeCode: "Прибрати код",
    send: "Надіслати",
    support: "Зв'язатися з підтримкою",
    supportSubject: "Питання з документації",
    tip: "Порада: чат можна відкрити й закрити за допомогою",
    title: "Асистент",
    verifyFailed: "Не вдалося підтвердити, що ви людина. Спробуйте знову.",
    you: "Ви",
  },
  banner: { dismiss: "Закрити оголошення" },
  changelog: {
    description: "Оновлення продукту та примітки до випусків.",
    title: "Журнал змін",
  },
  consent: {
    accept: "Прийняти",
    decline: "Відхилити",
    label: "Згода на cookie",
    message:
      "Ми хотіли б використовувати файли cookie, щоб розуміти, як використовується ця документація.",
    policy: "Політика конфіденційності",
    settings: "Налаштування cookie",
  },
  content: {
    code: "Код",
    copyColor: "Скопіювати колір {name} {value}",
    copyPrompt: "Скопіювати промпт",
    default: "За замовчуванням",
    diagramError: "Не вдалося відобразити цю діаграму.",
    forks: "Форки",
    preview: "Попередній перегляд",
    prop: "Властивість",
    selectTab: "Вибрати вкладку",
    selectView: "Вибрати подання",
    showLess: "Показати менше",
    showMore: "Показати більше",
    stars: "Зірки",
    tab: "Вкладка {n}",
    type: "Тип",
    update: "Оновлення",
  },
  feedback: {
    comment: "Розкажіть докладніше (необов'язково)",
    no: "Ні",
    question: "Чи була ця сторінка корисною?",
    send: "Надіслати",
    thanks: "Дякуємо за ваш відгук!",
    yes: "Так",
  },
  languageSwitcher: { label: "Мова", untranslated: "Не перекладено" },
  narration: {
    cueDanger: "Небезпека.",
    cueInfo: "Інформація.",
    cueNote: "Примітка.",
    cueSection: "Розгортуваний розділ.",
    cueStep: "Крок {n}.",
    cueSuccess: "Успіх.",
    cueTab: "Вкладка {title}.",
    cueTip: "Порада.",
    cueWarning: "Попередження.",
    error: "Не вдалося завантажити озвучення.",
    follow: "Стежити за читанням",
    label: "Прослухати сторінку",
    minutes: "{n} хв",
    next: "Наступне речення",
    pause: "Пауза",
    play: "Відтворити",
    previous: "Попереднє речення",
    progress: "Хід відтворення",
    speed: "Швидкість відтворення",
    stop: "Зупинити прослуховування",
  },
  nav: {
    back: "Назад",
    breadcrumb: "Навігаційний ланцюжок",
    closeNavigation: "Закрити навігацію",
    deprecated: "застаріле",
    featured: "Рекомендоване",
    githubRepository: "Репозиторій GitHub",
    navigation: "Навігація",
    opensInNewTab: "Відкривається в новій вкладці",
    primary: "Основне",
    sections: "Розділи",
    toggleNavigation: "Перемкнути навігацію",
    toggleTheme: "Перемкнути колірну тему",
  },
  notFound: {
    description: "Не вдалося знайти сторінку, яку ви шукаєте.",
    home: "Повернутися на головну",
    title: "Сторінку не знайдено",
  },
  page: {
    lastUpdated: "Останнє оновлення",
    next: "Далі",
    pagination: "Пагінація",
    previous: "Назад",
    related: "Пов'язані сторінки",
    skipToContent: "Перейти до вмісту",
  },
  search: {
    all: "Усі",
    allLanguages: "Усі мови",
    assistant: "Асистент",
    assistantHint: "Отримайте миттєву відповідь від ШІ",
    button: "Пошук",
    devOnly: "Пошук доступний у production-збірці.",
    docs: "Документація",
    error: "Щось пішло не так. Спробуйте ще раз.",
    label: "Пошук у документації",
    latest: "остання",
    navigate: "навігація",
    noResults: "Нічого не знайдено.",
    open: "відкрити",
    placeholder: "Пошук у документації…",
    popular: "Популярне",
    preview: "перегляд",
    results: "Результати",
  },
  toc: { title: "На цій сторінці" },
};
