import type { UIStringsOverride } from "../i18n-ui.ts";

/** Vietnamese (vi) UI strings. */
export const vi: UIStringsOverride = {
  actions: {
    addToCursor: "Thêm vào Cursor",
    addToVscode: "Thêm vào VS Code",
    askAboutCode: "Hỏi về đoạn mã này",
    connectMcp: "Kết nối với MCP",
    copied: "Đã sao chép!",
    copyClaudeCode: "Sao chép lệnh Claude Code",
    copyCode: "Sao chép mã",
    copyCodex: "Sao chép lệnh Codex",
    copyFailed: "Sao chép thất bại",
    copyMarkdown: "Sao chép dưới dạng Markdown",
    copyServerUrl: "Sao chép URL máy chủ",
    edit: "Chỉnh sửa trên GitHub",
    export: "Xuất",
    exportEpub: "Xuất ra EPUB",
    exportPdf: "Xuất ra PDF",
    generating: "Đang tạo…",
    openIn: "Mở trong {name}",
    openInChat: "Mở trong trò chuyện",
    openInChatPrompt: "Hãy đọc {url} để tôi có thể đặt câu hỏi về trang này.",
    scrollToTop: "Lên đầu trang",
  },
  assistant: {
    ai: "AI",
    clear: "Xóa cuộc trò chuyện",
    close: "Đóng",
    copy: "Sao chép cuộc trò chuyện",
    empty: "Đặt câu hỏi về tài liệu.",
    error: "Xin lỗi, đã xảy ra sự cố.",
    explainCode: "Giải thích đoạn mã này.",
    label: "Đặt câu hỏi",
    placeholder: "Đặt câu hỏi…",
    rateLimited: "Bạn đã hỏi rất nhiều câu hỏi. Hãy thử lại sau vài phút.",
    removeCode: "Xóa mã",
    send: "Gửi",
    support: "Liên hệ hỗ trợ",
    supportSubject: "Câu hỏi từ tài liệu",
    tip: "Mẹo: Bạn có thể mở và đóng trò chuyện bằng",
    title: "Trợ lý",
    verifyFailed:
      "Chúng tôi không thể xác minh bạn là người thật. Hãy thử lại.",
    you: "Bạn",
  },
  banner: { dismiss: "Đóng thông báo" },
  changelog: {
    description: "Cập nhật sản phẩm và ghi chú phát hành.",
    title: "Nhật ký thay đổi",
  },
  consent: {
    accept: "Chấp nhận",
    decline: "Từ chối",
    label: "Đồng ý cookie",
    message:
      "Chúng tôi muốn sử dụng cookie để hiểu cách tài liệu này được sử dụng.",
    policy: "Chính sách quyền riêng tư",
    settings: "Cài đặt cookie",
  },
  content: {
    code: "Mã",
    copyColor: "Sao chép màu {name} {value}",
    copyPrompt: "Sao chép prompt",
    default: "Mặc định",
    diagramError: "Không thể hiển thị sơ đồ này.",
    forks: "Fork",
    preview: "Xem trước",
    prop: "Thuộc tính",
    selectTab: "Chọn tab",
    selectView: "Chọn chế độ xem",
    showLess: "Ẩn bớt",
    showMore: "Hiển thị thêm",
    stars: "Sao",
    tab: "Tab {n}",
    type: "Kiểu",
    update: "Cập nhật",
  },
  feedback: {
    comment: "Cho chúng tôi biết thêm (không bắt buộc)",
    no: "Không",
    question: "Trang này có hữu ích không?",
    send: "Gửi",
    thanks: "Cảm ơn phản hồi của bạn!",
    yes: "Có",
  },
  languageSwitcher: { label: "Ngôn ngữ", untranslated: "Chưa dịch" },
  narration: {
    cueDanger: "Nguy hiểm.",
    cueInfo: "Thông tin.",
    cueNote: "Ghi chú.",
    cueSection: "Mục có thể mở rộng.",
    cueStep: "Bước {n}.",
    cueSuccess: "Thành công.",
    cueTab: "Tab {title}.",
    cueTip: "Mẹo.",
    cueWarning: "Cảnh báo.",
    error: "Không thể tải âm thanh.",
    follow: "Theo dõi lời đọc",
    label: "Nghe trang này",
    minutes: "{n} phút",
    next: "Câu tiếp theo",
    pause: "Tạm dừng",
    play: "Phát",
    previous: "Câu trước",
    progress: "Tiến độ đọc",
    speed: "Tốc độ phát",
    stop: "Dừng nghe",
  },
  nav: {
    back: "Quay lại",
    breadcrumb: "Đường dẫn điều hướng",
    closeNavigation: "Đóng điều hướng",
    deprecated: "lỗi thời",
    featured: "Nổi bật",
    githubRepository: "Kho lưu trữ GitHub",
    navigation: "Điều hướng",
    opensInNewTab: "Mở trong thẻ mới",
    primary: "Chính",
    sections: "Chuyên mục",
    toggleNavigation: "Chuyển đổi điều hướng",
    toggleTheme: "Chuyển đổi chủ đề màu",
  },
  notFound: {
    description: "Chúng tôi không tìm thấy trang bạn đang tìm.",
    home: "Về trang chủ",
    title: "Không tìm thấy trang",
  },
  page: {
    lastUpdated: "Cập nhật lần cuối",
    next: "Tiếp theo",
    pagination: "Phân trang",
    previous: "Trước",
    related: "Trang liên quan",
    skipToContent: "Chuyển đến nội dung",
  },
  search: {
    all: "Tất cả",
    allLanguages: "Tất cả ngôn ngữ",
    assistant: "Trợ lý",
    assistantHint: "Nhận câu trả lời tức thì từ AI",
    button: "Tìm kiếm",
    devOnly: "Tìm kiếm có sẵn trong bản dựng production.",
    docs: "Tài liệu",
    error: "Đã xảy ra sự cố. Vui lòng thử lại.",
    label: "Tìm kiếm tài liệu",
    latest: "mới nhất",
    navigate: "di chuyển",
    noResults: "Không tìm thấy kết quả.",
    open: "mở",
    placeholder: "Tìm kiếm tài liệu…",
    popular: "Phổ biến",
    preview: "xem trước",
    results: "Kết quả",
  },
  toc: { title: "Trên trang này" },
};
