import type { UIStringsOverride } from "../i18n-ui.ts";

/** Chinese — Traditional (zh-TW) UI strings. */
export const zhTW: UIStringsOverride = {
  actions: {
    addToCursor: "新增至 Cursor",
    addToVscode: "新增至 VS Code",
    askAboutCode: "詢問這段程式碼",
    connectMcp: "連線至 MCP",
    copied: "已複製！",
    copyClaudeCode: "複製 Claude Code 指令",
    copyCode: "複製程式碼",
    copyCodex: "複製 Codex 指令",
    copyFailed: "複製失敗",
    copyMarkdown: "複製為 Markdown",
    copyServerUrl: "複製伺服器 URL",
    edit: "在 GitHub 上編輯",
    export: "匯出",
    exportEpub: "匯出為 EPUB",
    exportPdf: "匯出為 PDF",
    generating: "產生中…",
    openIn: "在 {name} 中開啟",
    openInChat: "在聊天中開啟",
    openInChatPrompt: "請閱讀 {url} 以便我針對此頁面提問。",
    scrollToTop: "回到頂部",
  },
  assistant: {
    ai: "AI",
    clear: "清除對話",
    close: "關閉",
    copy: "複製對話",
    empty: "針對文件提出問題。",
    error: "抱歉，發生了一些問題。",
    explainCode: "解釋這段程式碼。",
    label: "提出問題",
    placeholder: "提出問題…",
    rateLimited: "你提出的問題太多了，請幾分鐘後再試。",
    removeCode: "移除程式碼",
    send: "傳送",
    support: "聯絡支援團隊",
    supportSubject: "來自文件的問題",
    tip: "提示：可透過以下快捷鍵開啟和關閉聊天",
    title: "助理",
    verifyFailed: "無法確認你是真人，請再試一次。",
    you: "你",
  },
  banner: { dismiss: "關閉公告" },
  changelog: {
    description: "產品更新與版本說明。",
    title: "更新日誌",
  },
  consent: {
    accept: "接受",
    decline: "拒絕",
    label: "Cookie 同意",
    message: "我們希望使用 Cookie 來了解這份文件的使用情況。",
    policy: "隱私權政策",
    settings: "Cookie 設定",
  },
  content: {
    code: "程式碼",
    copyColor: "複製顏色 {name} {value}",
    copyPrompt: "複製提示詞",
    default: "預設值",
    diagramError: "無法顯示此圖表。",
    forks: "複刻",
    preview: "預覽",
    prop: "屬性",
    selectTab: "選擇分頁",
    selectView: "選擇檢視",
    showLess: "顯示較少",
    showMore: "顯示更多",
    stars: "星標",
    tab: "分頁 {n}",
    type: "型別",
    update: "更新",
  },
  feedback: {
    comment: "告訴我們更多（選填）",
    no: "沒有幫助",
    question: "這個頁面有幫助嗎？",
    send: "送出",
    thanks: "感謝你的意見回饋！",
    yes: "有幫助",
  },
  languageSwitcher: { label: "語言", untranslated: "未翻譯" },
  narration: {
    cueDanger: "危險。",
    cueInfo: "資訊。",
    cueNote: "備註。",
    cueSection: "可展開區段。",
    cueStep: "第 {n} 步。",
    cueSuccess: "成功。",
    cueTab: "{title} 分頁。",
    cueTip: "提示。",
    cueWarning: "警告。",
    error: "無法載入朗讀音訊。",
    follow: "跟隨朗讀",
    label: "收聽此頁面",
    minutes: "{n} 分鐘",
    next: "下一句",
    pause: "暫停",
    play: "播放",
    previous: "上一句",
    progress: "朗讀進度",
    speed: "播放速度",
    stop: "停止收聽",
  },
  nav: {
    back: "返回",
    breadcrumb: "麵包屑導覽",
    closeNavigation: "關閉導覽",
    deprecated: "已棄用",
    featured: "精選",
    githubRepository: "GitHub 儲存庫",
    navigation: "導覽",
    opensInNewTab: "在新分頁中開啟",
    primary: "主要",
    sections: "章節",
    toggleNavigation: "切換導覽",
    toggleTheme: "切換色彩主題",
  },
  notFound: {
    description: "我們找不到你要瀏覽的頁面。",
    home: "返回首頁",
    title: "找不到頁面",
  },
  page: {
    lastUpdated: "最後更新於",
    next: "下一頁",
    pagination: "分頁",
    previous: "上一頁",
    related: "相關頁面",
    skipToContent: "跳至內容",
  },
  search: {
    all: "全部",
    allLanguages: "所有語言",
    assistant: "助理",
    assistantHint: "從 AI 即時取得解答",
    button: "搜尋",
    devOnly: "搜尋在正式版組建中可用。",
    docs: "文件",
    error: "發生了一些問題，請再試一次。",
    label: "搜尋文件",
    latest: "最新",
    navigate: "導覽",
    noResults: "找不到結果。",
    open: "開啟",
    placeholder: "搜尋文件…",
    popular: "熱門",
    preview: "預覽",
    results: "結果",
  },
  toc: { title: "本頁內容" },
};
