import type { UIStringsOverride } from "../i18n-ui.ts";

/** Chinese — Simplified (zh) UI strings. */
export const zh: UIStringsOverride = {
  actions: {
    addToCursor: "添加到 Cursor",
    addToVscode: "添加到 VS Code",
    askAboutCode: "询问这段代码",
    connectMcp: "连接到 MCP",
    copied: "已复制！",
    copyClaudeCode: "复制 Claude Code 命令",
    copyCode: "复制代码",
    copyCodex: "复制 Codex 命令",
    copyFailed: "复制失败",
    copyMarkdown: "复制为 Markdown",
    copyServerUrl: "复制服务器 URL",
    edit: "在 GitHub 上编辑",
    export: "导出",
    exportEpub: "导出为 EPUB",
    exportPdf: "导出为 PDF",
    generating: "生成中…",
    openIn: "在 {name} 中打开",
    openInChat: "在聊天中打开",
    openInChatPrompt: "请阅读 {url} 以便我就此页面提问。",
    scrollToTop: "回到顶部",
  },
  assistant: {
    ai: "AI",
    clear: "清空对话",
    close: "关闭",
    copy: "复制对话",
    empty: "就文档提出问题。",
    error: "抱歉，出了点问题。",
    explainCode: "解释这段代码。",
    label: "提出问题",
    placeholder: "提出问题…",
    rateLimited: "你提的问题太多了，请几分钟后再试。",
    removeCode: "移除代码",
    send: "发送",
    support: "联系支持团队",
    supportSubject: "来自文档的问题",
    tip: "提示：可通过以下快捷键打开和关闭聊天",
    title: "助手",
    verifyFailed: "无法确认你是真人，请重试。",
    you: "你",
  },
  banner: { dismiss: "关闭公告" },
  changelog: {
    description: "产品更新与版本说明。",
    title: "更新日志",
  },
  consent: {
    accept: "接受",
    decline: "拒绝",
    label: "Cookie 同意",
    message: "我们希望使用 Cookie 来了解本文档的使用情况。",
    policy: "隐私政策",
    settings: "Cookie 设置",
  },
  content: {
    code: "代码",
    copyColor: "复制颜色 {name} {value}",
    copyPrompt: "复制提示词",
    default: "默认值",
    diagramError: "无法渲染此图表。",
    forks: "复刻",
    preview: "预览",
    prop: "属性",
    selectTab: "选择标签页",
    selectView: "选择视图",
    showLess: "显示更少",
    showMore: "显示更多",
    stars: "星标",
    tab: "标签页 {n}",
    type: "类型",
    update: "更新",
  },
  feedback: {
    comment: "告诉我们更多（选填）",
    no: "没有帮助",
    question: "这个页面有帮助吗？",
    send: "发送",
    thanks: "感谢你的反馈！",
    yes: "有帮助",
  },
  languageSwitcher: { label: "语言", untranslated: "未翻译" },
  narration: {
    cueDanger: "危险。",
    cueInfo: "信息。",
    cueNote: "备注。",
    cueSection: "可展开部分。",
    cueStep: "第 {n} 步。",
    cueSuccess: "成功。",
    cueTab: "{title} 标签页。",
    cueTip: "提示。",
    cueWarning: "警告。",
    error: "无法加载朗读音频。",
    follow: "跟随朗读",
    label: "收听此页面",
    minutes: "{n} 分钟",
    next: "下一句",
    pause: "暂停",
    play: "播放",
    previous: "上一句",
    progress: "朗读进度",
    speed: "播放速度",
    stop: "停止收听",
  },
  nav: {
    back: "返回",
    breadcrumb: "面包屑导航",
    closeNavigation: "关闭导航",
    deprecated: "已弃用",
    featured: "精选",
    githubRepository: "GitHub 仓库",
    navigation: "导航",
    opensInNewTab: "在新标签页中打开",
    primary: "主要",
    sections: "章节",
    toggleNavigation: "切换导航",
    toggleTheme: "切换颜色主题",
  },
  notFound: {
    description: "我们找不到你要访问的页面。",
    home: "返回首页",
    title: "页面未找到",
  },
  page: {
    lastUpdated: "最后更新于",
    next: "下一页",
    pagination: "分页",
    previous: "上一页",
    related: "相关页面",
    skipToContent: "跳到内容",
  },
  search: {
    all: "全部",
    allLanguages: "所有语言",
    assistant: "助手",
    assistantHint: "从 AI 即时获取答案",
    button: "搜索",
    devOnly: "搜索在生产构建中可用。",
    docs: "文档",
    error: "出了点问题，请重试。",
    label: "搜索文档",
    latest: "最新",
    navigate: "导航",
    noResults: "未找到结果。",
    open: "打开",
    placeholder: "搜索文档…",
    popular: "热门",
    preview: "预览",
    results: "结果",
  },
  toc: { title: "本页内容" },
};
