// Generated by `blume translate` — edit the default locale's meta file
// and rerun the translation instead of editing this copy.
export default {
  order: 4,
  pages: [
    "theming",
    "customization",
    "search",
    "ai",
    "analytics",
    "export",
    "seo",
  ],
  title: "設定",
};
