import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import {
  copyFile,
  mkdir,
  readdir,
  readFile,
  rename,
  rm,
  writeFile,
} from "node:fs/promises";

import type * as OpenAISdk from "@ai-sdk/openai";
import type { OpenAIProvider } from "@ai-sdk/openai";
import { createGateway, generateSpeech } from "ai";
import type { SpeechModel } from "ai";
import { HTMLElement, parse, TextNode } from "node-html-parser";
import type { Node } from "node-html-parser";
import { dirname, join } from "pathe";

import { normalizeBasePath } from "../core/base-path.ts";
import { nodeRequire } from "../core/node-require.ts";
import type { BlumeProject } from "../core/project-graph.ts";
import type { ProjectContext } from "../core/types.ts";
import { hasCredentials, OPENAI_SPEECH_DEP } from "./provider.ts";
import type {
  GatewayNarrationProvider,
  NarrationProvider,
  OpenAINarrationProvider,
} from "./provider.ts";
import {
  extractNarration,
  isNarratable,
  isNarrationCues,
  segmentNarration,
} from "./script.ts";
import type {
  NarrationCues,
  NarrationManifest,
  NarrationSegment,
  NarrationTree,
} from "./script.ts";

/**
 * Generated narration: after Astro writes the HTML, read every page that
 * carries the player exactly as the browser will (same walker, same blocks),
 * split it into sentences, and give each sentence a clip from the configured
 * speech model. Clips are cached by what decides their sound (text, language,
 * model, voice, instructions, provider options, endpoint), so a rebuild only
 * pays for sentences that changed, and one sentence shared by many pages is
 * generated once. Each page gets a manifest listing its clips; the player
 * plays them in order and falls back to browser voices wherever a manifest is
 * missing.
 */

/** How the build logs: the integration's Astro logger. */
export interface NarrationLogger {
  info: (message: string) => void;
  warn: (message: string) => void;
}

/** Speak `text` in `lang`, returning MP3 bytes. */
export type Speak = (text: string, lang: string) => Promise<Uint8Array>;

/** What a narration build did, for the log line and tests. */
export interface NarrationBuildResult {
  /**
   * Clips that failed to generate, or that a missing key left ungenerated;
   * their pages get no manifest.
   */
  failed: number;
  /** Clips generated by the speech model on this build. */
  generated: number;
  /** Pages that got a manifest. */
  pages: number;
  /** Clips read back from the cache. */
  reused: number;
}

// Bump to regenerate every clip: part of every cache key.
const CLIP_FORMAT = 1;

// Where `openai()` speaks with neither a `baseUrl` nor `OPENAI_BASE_URL`.
const OPENAI_API_URL = "https://api.openai.com/v1";

// What `generateSpeech` reports for bytes it recognized as MP3. Bytes it can't
// place at all (a web page, raw PCM) default to `audio/mp3` instead.
const MP3_MEDIA_TYPE = "audio/mpeg";

// Parallel speech requests. Low enough to stay inside provider rate limits on
// a first build of a large site, where every sentence is new.
const CONCURRENCY = 4;

/**
 * The clip cache directory: `node_modules/.cache/blume/narration`, next to the
 * OG card cache and restored by the same host build caches (see `ogCacheDir`).
 */
export const narrationCacheDir = (
  context: Pick<ProjectContext, "outDir" | "root">
): string =>
  existsSync(join(context.root, "node_modules"))
    ? join(context.root, "node_modules", ".cache", "blume", "narration")
    : join(context.outDir, ".cache", "narration");

/** The walker's view of a node-html-parser tree. */
export const htmlTree: NarrationTree<Node> = {
  attr: (node, name) =>
    node instanceof HTMLElement ? (node.getAttribute(name) ?? null) : null,
  children: (node) => node.childNodes,
  tag: (node) =>
    node instanceof HTMLElement && node.tagName
      ? node.tagName.toLowerCase()
      : null,
  text: (node) => (node instanceof TextNode ? node.text : null),
};

/** The player's settings on a built page, and the article it reads. */
interface PlayerPage {
  article: HTMLElement;
  audioBase: string;
  cues: NarrationCues;
  lang: string;
  manifest: string;
}

const parseCues = (json: string | undefined): NarrationCues | null => {
  try {
    const value: unknown = JSON.parse(json ?? "");
    return isNarrationCues(value) ? value : null;
  } catch {
    return null;
  }
};

/**
 * The generated player on a built page, or `null` when the page has none (or
 * a player without generated audio, which reads with browser voices).
 */
export const readPlayerPage = (html: string): PlayerPage | null => {
  const root = parse(html);
  const player = root.querySelector("[data-blume-narration-player]");
  // node-html-parser has no `dataset`; `attributes` is its decoded map.
  const data = player?.attributes ?? {};
  const manifest = data["data-manifest"];
  const audioBase = data["data-audio-base"];
  const article = player?.parentNode;
  const cues = parseCues(data["data-cues"]);
  if (
    !(player && manifest && audioBase && cues) ||
    !(article instanceof HTMLElement)
  ) {
    return null;
  }
  return {
    article,
    audioBase,
    cues,
    lang: data["data-lang"] ?? "en",
    manifest,
  };
};

/** The language code a speech model takes (`pt-BR` -> `pt`). */
const speechLanguage = (lang: string): string =>
  lang.toLowerCase().replaceAll("_", "-").split("-")[0] ?? lang;

/**
 * The server `openai()` speaks to: its `baseUrl`, else `OPENAI_BASE_URL` as
 * OpenAI's SDKs read it, else OpenAI, without a trailing slash, which the SDK
 * drops too. Resolved here rather than left to the SDK, so the clip key names
 * the server the clips come from.
 */
const openaiEndpoint = (provider: OpenAINarrationProvider): string =>
  (
    provider.options.baseUrl ||
    process.env.OPENAI_BASE_URL ||
    OPENAI_API_URL
  ).replace(/\/+$/u, "");

/** The server a provider's clips come from: none named for `gateway()`. */
const speakerEndpoint = (provider: NarrationProvider): string | undefined =>
  provider.kind === "openai" ? openaiEndpoint(provider) : undefined;

/**
 * A clip's cache key: a digest of everything that decides how it sounds. The
 * Blume version is deliberately left out, unlike the OG card's: an upgrade
 * shouldn't pay to regenerate audio that would sound the same. A build
 * resolves `endpoint` once and passes it in, rather than reading the
 * environment for every sentence.
 */
export const clipKey = (
  provider: NarrationProvider,
  lang: string,
  text: string,
  endpoint = speakerEndpoint(provider)
): string => {
  const { instructions, model, providerOptions, voice } = provider.options;
  const gateway = provider.kind === "gateway";
  return createHash("sha256")
    .update(
      JSON.stringify({
        // Which server speaks: none for `gateway()`, which JSON drops, so its
        // clips keep the keys they had before narration took other providers.
        endpoint: gateway
          ? undefined
          : { baseUrl: endpoint, kind: provider.kind },
        format: CLIP_FORMAT,
        instructions,
        // Only the gateway is sent a language (`openaiSpeaker` sends none), so
        // an `openai()` sentence sounds the same in every locale and is
        // generated once.
        lang: gateway ? speechLanguage(lang) : undefined,
        model,
        providerOptions,
        text,
        voice,
      })
    )
    .digest("hex")
    .slice(0, 32);
};

/** Speak through the Vercel AI Gateway with the provider's model and voice. */
export const gatewaySpeaker = (provider: GatewayNarrationProvider): Speak => {
  const { apiKeyEnv, headers, instructions, model, providerOptions, voice } =
    provider.options;
  const gateway = createGateway({ apiKey: process.env[apiKeyEnv], headers });
  return async (text, lang) => {
    const { audio } = await generateSpeech({
      instructions,
      language: speechLanguage(lang),
      model: gateway.speechModel(model),
      outputFormat: "mp3",
      providerOptions,
      text,
      voice,
    });
    return audio.uint8Array;
  };
};

/**
 * `fetch` for a keyless request: `createOpenAI` always sends the key as a
 * bearer token, so an empty one would arrive as a bare `Bearer` that servers
 * and proxies checking auth can reject. An `Authorization` from `headers`
 * stays.
 */
const withoutEmptyBearer = async (
  input: Parameters<typeof fetch>[0],
  init?: RequestInit
): Promise<Response> => {
  const headers = new Headers(init?.headers);
  if (headers.get("authorization") === "Bearer") {
    headers.delete("authorization");
  }
  return await fetch(input, { ...init, headers });
};

/**
 * Speak through OpenAI's speech API, or with `baseUrl` through any server
 * that serves it (`POST /audio/speech`): Kokoro-FastAPI, Speaches, LiteLLM.
 * That API takes no language, so none is sent and the model or voice
 * decides it. Without a key, no bearer token is sent (an `Authorization` in
 * `headers` still is). A build resolves `baseURL` once and passes it in.
 */
export const openaiSpeaker = (
  provider: OpenAINarrationProvider,
  baseURL = openaiEndpoint(provider)
): Speak => {
  const { apiKeyEnv, headers, instructions, model, providerOptions, voice } =
    provider.options;
  // Made on the first clip rather than up front, so what can go wrong here
  // fails that clip and the build carries on with browser voices: an ejected
  // app's `astro build` runs no dependency preflight, and `OPENAI_BASE_URL`
  // isn't validated the way `baseUrl` is.
  const connect = (): OpenAIProvider => {
    if (hasCredentials(baseURL)) {
      throw new Error(
        "OPENAI_BASE_URL has credentials in it, which fetch won't send: name the env var holding the key in apiKeyEnv instead"
      );
    }
    // `require`, not `import()`: this runs in `astro:build:done` (see
    // `core/node-require.ts`).
    const { createOpenAI }: typeof OpenAISdk = nodeRequire(OPENAI_SPEECH_DEP);
    const apiKey = apiKeyEnv ? process.env[apiKeyEnv] : undefined;
    return createOpenAI({
      // Never undefined: the SDK would fall back to OPENAI_API_KEY and send
      // that to a custom endpoint that names no key.
      apiKey: apiKey ?? "",
      baseURL,
      // SAFETY: the SDK only calls it, so Bun's `fetch.preconnect` (which its
      // `typeof fetch` adds) is never read.
      fetch: apiKey ? undefined : (withoutEmptyBearer as typeof fetch),
      headers,
    });
  };
  let openai: OpenAIProvider | undefined;
  return async (text) => {
    openai ??= connect();
    const { audio, responses } = await generateSpeech({
      instructions,
      // SAFETY: both sides are the same `SpeechModelV4` spec. `ai` and
      // `@ai-sdk/openai` each pin their own `@ai-sdk/provider`, and the type
      // only differs between those copies, not in what `generateSpeech` calls.
      model: openai.speech(model) as SpeechModel,
      outputFormat: "mp3",
      providerOptions,
      text,
      voice,
    });
    // The SDK takes any 2xx body as audio, and the clip is cached and served
    // as an MP3 whatever it holds, so a page a redirect led to (an SSO
    // proxy's sign-in, say) or WAV from a server that ignores
    // `response_format` would be reused on every build after: fail the clip
    // unless its bytes are MP3.
    if (audio.mediaType !== MP3_MEDIA_TYPE) {
      const type = responses[0]?.headers?.["content-type"] ?? "no content type";
      throw new Error(`The speech server answered with ${type}, not MP3 audio`);
    }
    return audio.uint8Array;
  };
};

/**
 * The env var a build needs to generate with `provider` and doesn't have, or
 * `null` when it can go ahead: the key is set, Vercel's OIDC token stands in
 * for the gateway's, or the provider names no key (`openai()` with a
 * `baseUrl` and no `apiKeyEnv`).
 */
export const missingKey = (provider: NarrationProvider): string | null => {
  const env = provider.options.apiKeyEnv;
  if (env === undefined || process.env[env]) {
    return null;
  }
  return provider.kind === "gateway" && process.env.VERCEL_OIDC_TOKEN
    ? null
    : env;
};

/** Every `.html` file under `dir`. */
const listHtml = async (dir: string): Promise<string[]> => {
  const entries = await readdir(dir, { recursive: true, withFileTypes: true });
  return entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".html"))
    .map((entry) => join(entry.parentPath, entry.name))
    .toSorted();
};

/** Run `task` over `items`, at most `limit` at a time. */
const eachLimited = async <T>(
  items: readonly T[],
  limit: number,
  task: (item: T) => Promise<void>
): Promise<void> => {
  let next = 0;
  const worker = async (): Promise<void> => {
    while (next < items.length) {
      const item = items[next];
      next += 1;
      if (item !== undefined) {
        // Workers pull one item at a time on purpose: that is the limit.
        // oxlint-disable-next-line no-await-in-loop
        await task(item);
      }
    }
  };
  await Promise.all(
    Array.from({ length: Math.min(limit, items.length) }, worker)
  );
};

// Written to a sibling temp file and renamed into place, so a crashed build
// never leaves a truncated clip for the next one to reuse.
const storeClip = async (file: string, bytes: Uint8Array): Promise<void> => {
  await mkdir(dirname(file), { recursive: true });
  const tmp = `${file}.${process.pid}.${Math.random().toString(36).slice(2)}.tmp`;
  await writeFile(tmp, bytes);
  await rename(tmp, file);
};

/** Remove cached clips this build didn't use, and stray temp files. */
const pruneClips = async (dir: string, used: Set<string>): Promise<void> => {
  let entries: string[];
  try {
    entries = await readdir(dir);
  } catch {
    return;
  }
  const stale = entries.filter(
    (name) =>
      name.endsWith(".tmp") ||
      (name.endsWith(".mp3") && !used.has(name.slice(0, -".mp3".length)))
  );
  await Promise.all(stale.map((name) => rm(join(dir, name), { force: true })));
};

/** A site URL path, minus the deployment base, as a path inside `distDir`. */
const distPath = (distDir: string, base: string, url: string): string => {
  const path = decodeURI(url);
  const local =
    base && path.startsWith(`${base}/`) ? path.slice(base.length) : path;
  return join(distDir, local);
};

/** One page's plan: where its manifest goes and what it says. */
interface PagePlan {
  blocks: string[];
  keys: string[];
  manifestFile: string;
  segments: NarrationSegment[];
}

const manifestFor = (plan: PagePlan): NarrationManifest => ({
  blocks: plan.blocks,
  segments: plan.segments.map((segment, index) => {
    const audio = `${plan.keys[index] ?? ""}.mp3`;
    return segment.block === null
      ? { audio, text: segment.text }
      : { audio, block: segment.block, end: segment.end, start: segment.start };
  }),
  version: 1,
});

/** What a build narrates: each page's plan, and every clip by its key. */
interface SitePlan {
  /** Where the clips are published, or `null` with no narratable page. */
  audioDir: string | null;
  plans: PagePlan[];
  texts: Map<string, { lang: string; text: string }>;
}

/**
 * Read every built page that carries the player and plan its narration,
 * keying each sentence's clip with `keyFor`.
 */
const planSite = async (
  distDir: string,
  base: string,
  keyFor: (lang: string, text: string) => string
): Promise<SitePlan> => {
  const plans: PagePlan[] = [];
  const texts = new Map<string, { lang: string; text: string }>();
  let audioDir: string | null = null;
  for (const file of await listHtml(distDir)) {
    // oxlint-disable-next-line no-await-in-loop -- one page in memory at a time
    const html = await readFile(file, "utf-8");
    const page = html.includes("data-blume-narration-player")
      ? readPlayerPage(html)
      : null;
    if (!page) {
      continue;
    }
    const extract = extractNarration(page.article, htmlTree, page.cues);
    if (!isNarratable(extract)) {
      continue;
    }
    audioDir ??= distPath(distDir, base, page.audioBase);
    const segments = segmentNarration(extract, page.lang);
    const keys = segments.map((segment) => {
      const key = keyFor(page.lang, segment.text);
      texts.set(key, { lang: page.lang, text: segment.text });
      return key;
    });
    plans.push({
      blocks: extract.blocks.map((block) => block.text),
      keys,
      manifestFile: distPath(distDir, base, page.manifest),
      segments,
    });
  }
  return { audioDir, plans, texts };
};

/**
 * Generate the narration for a built site in `distDir`: a clip per sentence
 * and a manifest per page. Does nothing unless `narration.provider` is set.
 * When new clips are needed and the provider's key is missing, it warns and
 * generates nothing, so only pages whose clips are all cached get audio (the
 * rest read with browser voices). `speak` replaces the provider call.
 */
export const buildNarration = async (
  project: BlumeProject,
  distDir: string,
  logger: NarrationLogger,
  speak?: Speak
): Promise<NarrationBuildResult | null> => {
  const { narration } = project.config;
  const { provider } = narration;
  if (!(narration.enabled && provider)) {
    return null;
  }
  const endpoint = speakerEndpoint(provider);
  const base = normalizeBasePath(project.config.deployment.options.base);

  // Read every page first, so the log can say what generation will cost
  // before any of it is spent.
  const { audioDir, plans, texts } = await planSite(
    distDir,
    base,
    (lang, text) => clipKey(provider, lang, text, endpoint)
  );
  if (!audioDir || plans.length === 0) {
    return { failed: 0, generated: 0, pages: 0, reused: 0 };
  }

  const cacheDir = narrationCacheDir(project.context);
  const cached = (key: string) => join(cacheDir, `${key}.mp3`);
  const missing = [...texts.keys()].filter((key) => !existsSync(cached(key)));
  const reused = texts.size - missing.length;
  // Checked only once something needs generating, so a build without the key
  // (a fork's pull request, say) still ships every clip the cache restored.
  const env = speak || missing.length === 0 ? null : missingKey(provider);
  if (env) {
    logger.warn(
      `Narration audio was not generated: ${env} is not set, so pages missing clips will be read with browser voices.`
    );
  } else if (missing.length > 0) {
    const chars = missing.reduce(
      (total, key) => total + (texts.get(key)?.text.length ?? 0),
      0
    );
    logger.info(
      `Generating narration: ${missing.length} new clip(s), ${chars.toLocaleString("en-US")} characters, with ${provider.options.model}`
    );
  }
  const say =
    speak ??
    (provider.kind === "gateway"
      ? gatewaySpeaker(provider)
      : openaiSpeaker(provider, endpoint));

  // The AI SDK already retries a transient failure, so one that gets through
  // (a bad key, an unknown model, a spent quota) would fail every clip after
  // it too: stop generating at the first, and keep what's already cached.
  const failures = new Set(env ? missing : []);
  let firstError: string | null = null;
  await eachLimited(env ? [] : missing, CONCURRENCY, async (key) => {
    const entry = texts.get(key);
    if (!entry || firstError !== null) {
      failures.add(key);
      return;
    }
    try {
      await storeClip(cached(key), await say(entry.text, entry.lang));
    } catch (error) {
      failures.add(key);
      firstError ??= error instanceof Error ? error.message : String(error);
    }
  });
  if (firstError !== null) {
    logger.warn(
      `Narration stopped generating after a clip failed (${firstError}). Pages missing clips will be read with browser voices.`
    );
  }

  const target = audioDir;
  await mkdir(target, { recursive: true });
  const shipped = new Set<string>();
  let pages = 0;
  for (const plan of plans) {
    if (plan.keys.some((key) => failures.has(key))) {
      continue;
    }
    for (const key of plan.keys) {
      if (!shipped.has(key)) {
        shipped.add(key);
        // oxlint-disable-next-line no-await-in-loop -- bounded by unique clips
        await copyFile(cached(key), join(target, `${key}.mp3`));
      }
    }
    // oxlint-disable-next-line no-await-in-loop -- one manifest per page
    await mkdir(dirname(plan.manifestFile), { recursive: true });
    // oxlint-disable-next-line no-await-in-loop
    await writeFile(
      plan.manifestFile,
      `${JSON.stringify(manifestFor(plan))}\n`,
      "utf-8"
    );
    pages += 1;
  }

  // Only clips for text no longer on the site go; the current site's stay,
  // whether or not this run generated all of them.
  await pruneClips(cacheDir, new Set(texts.keys()));
  const generated = missing.length - failures.size;
  logger.info(
    `Narration: ${pages} page(s), ${generated} clip(s) generated, ${reused} reused from the cache`
  );
  return { failed: failures.size, generated, pages, reused };
};
