interface TailwindEntryOptions {
  /**
   * Globs to scan for utility classes. Typically the Blume package source and
   * the user's project (node_modules is skipped automatically).
   */
  sources: string[];
  /** Config-derived token overrides (`:root { --blume-accent: ... }`). */
  configTokens: string;
  /** Raw contents of the user's theme.css, if any. */
  userTheme: string;
}

/**
 * Build the single Tailwind v4 entry stylesheet for the generated runtime.
 *
 * Everything flows through one Tailwind-processed file so utilities are
 * generated and design tokens cascade deterministically:
 * base defaults -> config tokens -> user theme.css.
 */
export const tailwindEntryTemplate = (options: TailwindEntryOptions): string =>
  `/* Generated by Blume. Do not edit. */
@import "tailwindcss";
@plugin "@tailwindcss/typography";

/* Scan Blume's components and the user's project for utility classes. */
${options.sources.map((source) => `@source "${source}";`).join("\n")}

/* Dark mode is driven by data-theme on the <html> element. */
@custom-variant dark (&:where([data-theme="dark"], [data-theme="dark"] *));

:root {
  --blume-background: oklch(1 0 0);
  --blume-foreground: oklch(0.145 0 0);
  --blume-muted: oklch(0.965 0 0);
  --blume-muted-foreground: oklch(0.54 0 0);
  --blume-border: oklch(0.88 0.006 260 / 0.72);
  --blume-accent: oklch(0.145 0 0);
  --blume-accent-foreground: oklch(1 0 0);
  --blume-code-background: oklch(0.99 0 0);
  --blume-radius: 0.75rem;
}

:root[data-theme="dark"] {
  --blume-background: oklch(0.085 0 0);
  --blume-foreground: oklch(0.96 0 0);
  --blume-muted: oklch(0.16 0 0);
  --blume-muted-foreground: oklch(0.68 0 0);
  --blume-border: oklch(0.24 0 0 / 0.8);
  --blume-accent: oklch(0.96 0 0);
  --blume-accent-foreground: oklch(0.085 0 0);
  --blume-code-background: oklch(0.12 0 0);
}

@theme inline {
  --color-background: var(--blume-background);
  --color-foreground: var(--blume-foreground);
  --color-muted: var(--blume-muted);
  --color-muted-foreground: var(--blume-muted-foreground);
  --color-border: var(--blume-border);
  --color-accent: var(--blume-accent);
  --color-accent-foreground: var(--blume-accent-foreground);
  --color-code: var(--blume-code-background);
  --radius-blume: var(--blume-radius);
  --font-sans:
    ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, Helvetica,
    Arial, sans-serif;
  --font-mono:
    ui-monospace, "SF Mono", "Cascadia Code", "Source Code Pro", Menlo,
    Consolas, monospace;
}

@layer base {
  html {
    scroll-behavior: smooth;
    scroll-padding-top: 4.5rem;
  }
  :focus-visible {
    outline: 2px solid var(--blume-accent);
    outline-offset: 2px;
    border-radius: 2px;
  }
  @media (prefers-reduced-motion: reduce) {
    html {
      scroll-behavior: auto;
    }
  }
}

/* Theme Tailwind Typography (prose) with Blume tokens. */
.prose {
  --tw-prose-body: var(--blume-foreground);
  --tw-prose-headings: var(--blume-foreground);
  --tw-prose-lead: var(--blume-muted-foreground);
  --tw-prose-links: var(--blume-foreground);
  --tw-prose-bold: var(--blume-foreground);
  --tw-prose-counters: var(--blume-muted-foreground);
  --tw-prose-bullets: var(--blume-border);
  --tw-prose-hr: var(--blume-border);
  --tw-prose-quotes: var(--blume-muted-foreground);
  --tw-prose-quote-borders: var(--blume-border);
  --tw-prose-captions: var(--blume-muted-foreground);
  --tw-prose-code: var(--blume-foreground);
  --tw-prose-pre-code: var(--blume-foreground);
  --tw-prose-pre-bg: var(--blume-code-background);
  --tw-prose-th-borders: var(--blume-border);
  --tw-prose-td-borders: var(--blume-border);
  color: var(--blume-muted-foreground);
  font-size: 0.875rem;
  line-height: 1.7;
}

.prose :where(h1, h2, h3, h4) {
  font-weight: 500;
  letter-spacing: 0;
}

.prose :where(h1) {
  font-size: 3rem;
  line-height: 1.1;
  margin: 0 0 1rem;
}

.prose :where(h2) {
  border-top: 1px solid var(--blume-border);
  font-size: 1.875rem;
  line-height: 1.2;
  margin-top: 3rem;
  padding-top: 2rem;
}

.prose :where(h3) {
  font-size: 1.25rem;
  line-height: 1.35;
}

.prose :where(h4) {
  color: var(--blume-muted-foreground);
  font-size: 0.875rem;
  line-height: 1.4;
}

.prose :where(h1, h2, h3, h4) a {
  color: inherit;
  font-weight: inherit;
  text-decoration: none;
}

.prose :where(h2:first-child) {
  border-top: 0;
  padding-top: 0;
}

.prose :where(p, ul, ol) {
  margin-top: 1rem;
  margin-bottom: 1rem;
}

.prose :where(strong) {
  font-weight: 600;
}

.prose :where(a) {
  color: var(--blume-foreground);
  font-weight: 500;
  text-decoration-line: underline;
  text-decoration-style: dotted;
  text-decoration-thickness: 1px;
  text-underline-offset: 0.2em;
}

.prose :where(hr) {
  margin: 2.5rem 0;
}

.prose :where(pre) {
  background: var(--blume-code-background);
  border: 1px solid var(--blume-border);
  border-radius: var(--blume-radius);
  color: var(--blume-foreground);
  font-size: 0.8125rem;
  line-height: 1.55;
  margin: 1.5rem 0;
  overflow-x: auto;
  padding: 1rem 1.25rem;
  position: relative;
}

.prose :where(pre.astro-code) {
  background: var(--blume-code-background) !important;
  color: var(--shiki-light, var(--blume-foreground)) !important;
}

:root[data-theme="dark"] .prose :where(pre.astro-code) {
  color: var(--shiki-dark, var(--blume-foreground)) !important;
}

.prose :where(pre.astro-code span) {
  background: transparent !important;
  color: var(--shiki-light, inherit);
  font-style: var(--shiki-light-font-style, inherit);
  font-weight: var(--shiki-light-font-weight, inherit);
  text-decoration: var(--shiki-light-text-decoration, inherit);
}

:root[data-theme="dark"] .prose :where(pre.astro-code span) {
  color: var(--shiki-dark, inherit);
  font-style: var(--shiki-dark-font-style, inherit);
  font-weight: var(--shiki-dark-font-weight, inherit);
  text-decoration: var(--shiki-dark-text-decoration, inherit);
}

.prose :where(pre[data-language]) {
  padding-top: 3.25rem;
}

.prose :where(pre[data-language])::before {
  align-items: center;
  background: color-mix(in oklab, var(--blume-muted) 35%, transparent);
  border-bottom: 1px solid var(--blume-border);
  color: var(--blume-muted-foreground);
  content: attr(data-language);
  display: flex;
  font-family: var(--font-sans);
  font-size: 0.75rem;
  font-weight: 500;
  height: 2.25rem;
  left: 0;
  padding: 0 3.25rem 0 1rem;
  position: absolute;
  right: 0;
  top: 0;
}

.prose :where(pre code) {
  background: transparent;
  border-radius: 0;
  color: inherit;
  font-size: inherit;
  font-weight: 400;
  padding: 0;
}

.prose :where(table) {
  font-size: 0.8125rem;
}

blume-tabs pre,
.not-prose > div > pre {
  background: var(--blume-code-background);
}

/* Code blocks inside tabs sit flush; the tab container owns the frame. These
   rules are unlayered like the base \`pre\` styles, so they win over Tailwind's
   layered utilities (which a class on the panel cannot). */
blume-tabs [data-blume-tab-panel] > pre {
  border: 0;
  border-radius: 0;
  margin: 0;
}

blume-tabs pre[data-language],
.not-prose pre[data-language] {
  padding-top: 1rem;
}

blume-tabs pre[data-language]::before,
.not-prose pre[data-language]::before {
  content: none;
}

blume-tabs .blume-copy-button,
.not-prose .blume-copy-button {
  top: 0.625rem;
}

@media (max-width: 640px) {
  .prose :where(h1) {
    font-size: 2.25rem;
  }

  .prose :where(h2) {
    font-size: 1.625rem;
  }
}

.prose :not(pre) > code {
  background: var(--blume-code-background);
  padding: 0.15em 0.35em;
  border-radius: 0.3rem;
  font-weight: 500;
}

.prose :not(pre) > code::before,
.prose :not(pre) > code::after {
  content: none;
}

/* Token overrides: config first, then the user's theme.css (highest priority). */
${options.configTokens}
${options.userTheme}
`;
