interface TailwindEntryOptions {
  /**
   * Globs to scan for utility classes. Typically the Blume package source and
   * the user's project (node_modules is skipped automatically).
   */
  sources: string[];
  /** Config-derived token overrides (`:root { --blume-accent: ... }`). */
  configTokens: string;
  /** Raw contents of the user's theme.css, if any. */
  userTheme: string;
}

/**
 * Build the single Tailwind v4 entry stylesheet for the generated runtime.
 *
 * Everything flows through one Tailwind-processed file so utilities are
 * generated and design tokens cascade deterministically:
 * base defaults -> config tokens -> user theme.css.
 */
export const tailwindEntryTemplate = (options: TailwindEntryOptions): string =>
  `/* Generated by Blume. Do not edit. */
@import "tailwindcss";
@plugin "@tailwindcss/typography";

/* Scan Blume's components and the user's project for utility classes. */
${options.sources.map((source) => `@source "${source}";`).join("\n")}

/* Dark mode is driven by data-theme on the <html> element. */
@custom-variant dark (&:where([data-theme="dark"], [data-theme="dark"] *));

:root {
  --blume-background: oklch(1 0 0);
  --blume-foreground: oklch(0.2 0 0);
  --blume-muted: oklch(0.97 0 0);
  --blume-muted-foreground: oklch(0.5 0 0);
  --blume-border: oklch(0.92 0 0);
  --blume-accent: oklch(0.62 0.16 250);
  --blume-accent-foreground: oklch(1 0 0);
  --blume-code-background: oklch(0.97 0 0);
  --blume-radius: 0.5rem;
}

:root[data-theme="dark"] {
  --blume-background: oklch(0.17 0 0);
  --blume-foreground: oklch(0.96 0 0);
  --blume-muted: oklch(0.23 0 0);
  --blume-muted-foreground: oklch(0.66 0 0);
  --blume-border: oklch(0.28 0 0);
  --blume-code-background: oklch(0.21 0 0);
}

@theme inline {
  --color-background: var(--blume-background);
  --color-foreground: var(--blume-foreground);
  --color-muted: var(--blume-muted);
  --color-muted-foreground: var(--blume-muted-foreground);
  --color-border: var(--blume-border);
  --color-accent: var(--blume-accent);
  --color-accent-foreground: var(--blume-accent-foreground);
  --color-code: var(--blume-code-background);
  --radius-blume: var(--blume-radius);
  --font-sans:
    ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, Helvetica,
    Arial, sans-serif;
  --font-mono:
    ui-monospace, "SF Mono", "Cascadia Code", "Source Code Pro", Menlo,
    Consolas, monospace;
}

@layer base {
  html {
    scroll-behavior: smooth;
    scroll-padding-top: 4.5rem;
  }
  :focus-visible {
    outline: 2px solid var(--blume-accent);
    outline-offset: 2px;
    border-radius: 2px;
  }
  @media (prefers-reduced-motion: reduce) {
    html {
      scroll-behavior: auto;
    }
  }
}

/* Theme Tailwind Typography (prose) with Blume tokens. */
.prose {
  --tw-prose-body: var(--blume-foreground);
  --tw-prose-headings: var(--blume-foreground);
  --tw-prose-lead: var(--blume-muted-foreground);
  --tw-prose-links: var(--blume-accent);
  --tw-prose-bold: var(--blume-foreground);
  --tw-prose-counters: var(--blume-muted-foreground);
  --tw-prose-bullets: var(--blume-border);
  --tw-prose-hr: var(--blume-border);
  --tw-prose-quotes: var(--blume-muted-foreground);
  --tw-prose-quote-borders: var(--blume-border);
  --tw-prose-captions: var(--blume-muted-foreground);
  --tw-prose-code: var(--blume-foreground);
  --tw-prose-pre-code: var(--blume-foreground);
  --tw-prose-pre-bg: var(--blume-code-background);
  --tw-prose-th-borders: var(--blume-border);
  --tw-prose-td-borders: var(--blume-border);
}

.prose :not(pre) > code {
  background: var(--blume-code-background);
  padding: 0.15em 0.35em;
  border-radius: 0.3rem;
  font-weight: 500;
}

.prose :not(pre) > code::before,
.prose :not(pre) > code::after {
  content: none;
}

/* Token overrides: config first, then the user's theme.css (highest priority). */
${options.configTokens}
${options.userTheme}
`;
