import type { ResolvedConfig } from "../core/schema.ts";

/** Named accent presets mapped to OKLCH values. */
const ACCENTS: Record<string, string> = {
  blue: "oklch(0.62 0.16 250)",
  green: "oklch(0.6 0.16 150)",
  orange: "oklch(0.68 0.17 50)",
  pink: "oklch(0.65 0.2 350)",
  purple: "oklch(0.58 0.2 290)",
  red: "oklch(0.58 0.22 25)",
  teal: "oklch(0.6 0.12 195)",
};

const RADII: Record<ResolvedConfig["theme"]["radius"], string> = {
  lg: "0.75rem",
  md: "0.5rem",
  none: "0",
  sm: "0.25rem",
};

const cssString = (value: string): string => JSON.stringify(value);

const backgroundImageCss = (image: string): string =>
  `url(${cssString(image)})`;

const cssToken = (name: string, value?: string | null): string[] =>
  value ? [`  ${name}: ${value};`] : [];

const backgroundDecorationCss = (
  decoration: ResolvedConfig["theme"]["backgroundDecoration"]
): string => {
  if (decoration === "gradient") {
    return `  --blume-background-decoration: radial-gradient(circle at top left, color-mix(in oklab, var(--blume-accent) 18%, transparent), transparent 28rem), radial-gradient(circle at top right, color-mix(in oklab, var(--blume-action) 12%, transparent), transparent 24rem);
  --blume-background-decoration-repeat: no-repeat, no-repeat;
  --blume-background-decoration-size: auto, auto;
`;
  }
  if (decoration === "grid") {
    return `  --blume-background-decoration: linear-gradient(var(--blume-border) 1px, transparent 1px), linear-gradient(90deg, var(--blume-border) 1px, transparent 1px);
  --blume-background-decoration-repeat: repeat, repeat;
  --blume-background-decoration-size: 2rem 2rem, 2rem 2rem;
`;
  }
  if (decoration === "windows") {
    return `  --blume-background-decoration: linear-gradient(90deg, color-mix(in oklab, var(--blume-border) 70%, transparent) 1px, transparent 1px), linear-gradient(var(--blume-border) 1px, transparent 1px);
  --blume-background-decoration-repeat: repeat, repeat;
  --blume-background-decoration-size: 7rem 4.5rem, 7rem 4.5rem;
`;
  }
  return "";
};

const themeRootCss = (
  theme: ResolvedConfig["theme"],
  options: {
    accent: string;
    action: string | null;
    backgroundDecoration: string;
    radius: string;
  }
): string =>
  [
    `  --blume-accent: ${options.accent};`,
    ...cssToken("--blume-action", options.action),
    ...cssToken(
      "--blume-action-foreground",
      options.action ? "oklch(1 0 0)" : null
    ),
    ...cssToken("--blume-background", theme.background),
    ...cssToken(
      "--blume-background-image",
      theme.backgroundImage ? backgroundImageCss(theme.backgroundImage) : null
    ),
    options.backgroundDecoration.trimEnd(),
    `  --blume-radius: ${options.radius};`,
  ]
    .filter(Boolean)
    .join("\n");

const themeDarkCss = (
  theme: ResolvedConfig["theme"],
  accentDark: string | null
): string => {
  const tokens = [
    ...cssToken("--blume-accent", accentDark),
    ...cssToken("--blume-background", theme.backgroundDark),
    ...cssToken(
      "--blume-background-image",
      theme.backgroundImageDark
        ? backgroundImageCss(theme.backgroundImageDark)
        : null
    ),
  ];
  if (tokens.length === 0) {
    return "";
  }
  return `:root[data-theme="dark"] {
${tokens.join("\n")}
}
`;
};

/**
 * Resolve the configured accent to a CSS color. A named accent resolves to its
 * preset; any other value is treated as a raw CSS color so users can pass
 * arbitrary colors without a config change.
 */
export const resolveAccent = (theme: ResolvedConfig["theme"]): string =>
  ACCENTS[theme.accent] ?? theme.accent;

/** Resolve the configured radius preset to a CSS length. */
export const resolveRadius = (theme: ResolvedConfig["theme"]): string =>
  RADII[theme.radius];

/**
 * Compile theme config into CSS custom properties. A named accent resolves to
 * its preset; any other value is treated as a raw CSS color so users can pass
 * arbitrary colors without a config change.
 */
export const buildThemeCss = (theme: ResolvedConfig["theme"]): string => {
  const accent = ACCENTS[theme.accent] ?? theme.accent;
  const accentDark = theme.accentDark
    ? (ACCENTS[theme.accentDark] ?? theme.accentDark)
    : null;
  const action = theme.action ? (ACCENTS[theme.action] ?? theme.action) : null;
  const backgroundDecoration = backgroundDecorationCss(
    theme.backgroundDecoration
  );
  const radius = RADII[theme.radius];
  const root = themeRootCss(theme, {
    accent,
    action,
    backgroundDecoration,
    radius,
  });
  const dark = themeDarkCss(theme, accentDark);

  return `/* Generated by Blume from theme config. */
:root {
${root}
}
${dark}`;
};
