import type { ResolvedConfig } from "../core/schema.ts";

/** Named accent presets mapped to OKLCH values. */
const ACCENTS: Record<string, string> = {
  blue: "oklch(0.62 0.16 250)",
  green: "oklch(0.6 0.16 150)",
  orange: "oklch(0.68 0.17 50)",
  pink: "oklch(0.65 0.2 350)",
  purple: "oklch(0.58 0.2 290)",
  red: "oklch(0.58 0.22 25)",
  teal: "oklch(0.6 0.12 195)",
};

const RADII: Record<ResolvedConfig["theme"]["radius"], string> = {
  lg: "0.75rem",
  md: "0.5rem",
  none: "0",
  sm: "0.25rem",
};

/**
 * Resolve the configured accent to a CSS color. A named accent resolves to its
 * preset; any other value is treated as a raw CSS color so users can pass
 * arbitrary colors without a config change.
 */
export const resolveAccent = (theme: ResolvedConfig["theme"]): string =>
  ACCENTS[theme.accent] ?? theme.accent;

/** Resolve the configured radius preset to a CSS length. */
export const resolveRadius = (theme: ResolvedConfig["theme"]): string =>
  RADII[theme.radius];

/**
 * Compile theme config into CSS custom properties. A named accent resolves to
 * its preset; any other value is treated as a raw CSS color so users can pass
 * arbitrary colors without a config change.
 */
export const buildThemeCss = (theme: ResolvedConfig["theme"]): string =>
  `/* Generated by Blume from theme config. */
:root {
  --blume-accent: ${resolveAccent(theme)};
  --blume-radius: ${resolveRadius(theme)};
}
`;
