// Generated by `blume translate` — edit the default locale's meta file
// and rerun the translation instead of editing this copy.
export default {
  order: 3,
  pages: [
    "navigation",
    "meta",
    "syntax",
    "components",
    "islands",
    "sources",
    "i18n",
    "versioning",
  ],
  title: "Conteúdo",
};
