import { exec, query } from "jsonpath-rfc9535";
import { z } from "zod";

import type { JsonValue } from "../core/adapter.ts";

/**
 * OpenAPI Overlays: the OpenAPI Initiative's format for changing an API
 * description without editing it — an ordered list of actions, each an RFC
 * 9535 JSONPath `target` with an `update` to merge in, a `copy` of another
 * node to merge in, or `remove`. A spec generated by another tool or owned by
 * another team can then carry docs-only changes (better descriptions, hidden
 * internal operations, a public server URL) in a file of its own.
 *
 * Implements Overlay Specification 1.0 and 1.1 over `jsonpath-rfc9535`, which
 * passes the JSONPath compliance suite in full, as the spec requires. The
 * documents here are already parsed; `parse.ts` reads the files.
 */

/** An overlay document or action that doesn't follow the spec. */
export class OverlayError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "OverlayError";
  }
}

/** An object node, the only kind that holds named properties. */
interface JsonObject {
  [key: string]: JsonValue;
}

/** A node that holds other nodes: where a match's parent can be. */
type JsonContainer = JsonObject | JsonValue[];

const isObject = (value: JsonValue | undefined): value is JsonObject =>
  typeof value === "object" && value !== null && !Array.isArray(value);

/**
 * A parsed YAML or JSON mapping, as the document an overlay acts on: the
 * parser's own types say nothing of JSON, but what it parses is JSON.
 */
export const isJsonObject = <Value>(
  value: Value
): value is Value & JsonObject =>
  typeof value === "object" && value !== null && !Array.isArray(value);

const isContainer = (value: JsonValue | undefined): value is JsonContainer =>
  typeof value === "object" && value !== null;

const isIndex = (key: string | number | undefined): key is number =>
  typeof key === "number";

/** An object, an array, or anything else: what update merging keys on. */
type MergeKind = "array" | "object" | "primitive";

const mergeKindOf = (value: JsonValue): MergeKind => {
  if (Array.isArray(value)) {
    return "array";
  }
  return isObject(value) ? "object" : "primitive";
};

/** A merge kind in a sentence. */
const MERGE_KIND_PHRASE: Record<MergeKind, string> = {
  array: "an array",
  object: "an object",
  primitive: "a primitive value",
};

const actionSchema = z.looseObject({
  /** A JSONPath expression selecting one node to merge into the targets (1.1). */
  copy: z.string().optional(),
  description: z.string().optional(),
  /** Remove every target from the map or array it's in. */
  remove: z.boolean().default(false),
  /** An RFC 9535 JSONPath expression selecting the nodes to act on. */
  target: z.string().min(1),
  /** A value merged into every target. */
  update: z.json().optional(),
});

/** A validated overlay action. */
type OverlayAction = z.output<typeof actionSchema>;

const overlaySchema = z.looseObject({
  actions: z.array(actionSchema).min(1),
  extends: z.string().optional(),
  info: z.looseObject({ title: z.string(), version: z.string() }),
  overlay: z.string().regex(/^1\.[01]\.\d+$/u, {
    message: "must be an Overlay Specification version, 1.0.x or 1.1.x",
  }),
});

/** A validated overlay document. */
export type OverlayDocument = z.output<typeof overlaySchema>;

/** Validate a parsed overlay document, naming the file in any error. */
export const overlayDocument = <Value>(
  value: Value,
  name: string
): OverlayDocument => {
  const parsed = overlaySchema.safeParse(value);
  if (parsed.success) {
    return parsed.data;
  }
  const [issue] = parsed.error.issues;
  const at = issue?.path.length ? `\`${issue.path.join(".")}\` ` : "";
  throw new OverlayError(
    `${name} is not an overlay document: ${at}${issue?.message ?? "invalid"}.`
  );
};

/** A matched node, where it sits, and how to reach it. */
interface Match {
  key?: string | number;
  parent?: JsonContainer;
  value: JsonValue;
}

/** The nodes `expression` selects, each with its parent (none for the root). */
const select = (document: JsonValue, expression: string): Match[] => {
  const matches: Match[] = [];
  exec(document, expression, (value, path) => {
    let parent: JsonValue = document;
    for (const key of path.slice(0, -1)) {
      // SAFETY: the path is one the query walked, so every step is a key of
      // the container before it.
      parent = (parent as Record<string | number, JsonValue>)[key] ?? null;
    }
    const key = path.at(-1);
    matches.push(
      key === undefined || !isContainer(parent)
        ? { value }
        : { key, parent, value }
    );
  });
  return matches;
};

/**
 * Merge `patch` into `target` as the spec says: objects recursively, arrays
 * by concatenation, a primitive replaced by a primitive. Returns the merged
 * value; any other pairing throws.
 */
const merge = (target: JsonValue, patch: JsonValue, at: string): JsonValue => {
  if (isObject(target) && isObject(patch)) {
    for (const [key, value] of Object.entries(patch)) {
      const current = target[key];
      target[key] =
        current === undefined
          ? structuredClone(value)
          : merge(current, value, `${at}.${key}`);
    }
    return target;
  }
  if (Array.isArray(target) && Array.isArray(patch)) {
    target.push(...structuredClone(patch));
    return target;
  }
  if (
    mergeKindOf(target) === "primitive" &&
    mergeKindOf(patch) === "primitive"
  ) {
    return patch;
  }
  throw new OverlayError(
    `can't merge ${MERGE_KIND_PHRASE[mergeKindOf(patch)]} into ${MERGE_KIND_PHRASE[mergeKindOf(target)]} at ${at}`
  );
};

/** Remove each match from its container, later siblings first. */
const removeAll = (matches: Match[]): void => {
  for (const { key, parent } of matches.toReversed()) {
    if (Array.isArray(parent) && isIndex(key)) {
      parent.splice(key, 1);
    } else if (isObject(parent) && key !== undefined && !isIndex(key)) {
      // oxlint-disable-next-line typescript/no-dynamic-delete -- an overlay target's key is only known at run time
      delete parent[key];
    } else {
      throw new OverlayError("can't remove the document itself");
    }
  }
};

/**
 * Merge `patch` into every match, which must all be objects, all arrays, or
 * all primitives. A primitive match is replaced in its parent.
 */
const mergeAll = (matches: Match[], patch: JsonValue, target: string) => {
  const kinds = new Set(matches.map((match) => mergeKindOf(match.value)));
  if (kinds.size > 1) {
    throw new OverlayError(
      `its target selects a mix of ${[...kinds].toSorted().join(", ")} values, and an update needs all one kind`
    );
  }
  for (const { key, parent, value } of matches) {
    const merged = merge(value, patch, target);
    if (merged !== value && parent !== undefined && key !== undefined) {
      // SAFETY: `key` came from walking `parent`, so it indexes it.
      (parent as Record<string | number, JsonValue>)[key] = merged;
    }
  }
};

/** The single node a `copy` expression selects, cloned. */
const copied = (document: JsonValue, expression: string): JsonValue => {
  const values = query(document, expression);
  const [value] = values;
  if (values.length !== 1 || value === undefined) {
    throw new OverlayError(
      `its copy expression "${expression}" selects ${values.length} nodes, and copy needs exactly one`
    );
  }
  return structuredClone(value);
};

const applyAction = (document: JsonValue, action: OverlayAction): void => {
  const matches = select(document, action.target);
  if (matches.length === 0) {
    return;
  }
  if (action.remove) {
    removeAll(matches);
    return;
  }
  const patch =
    action.update ??
    (action.copy === undefined ? undefined : copied(document, action.copy));
  if (patch !== undefined) {
    mergeAll(matches, patch, action.target);
  }
};

/**
 * Apply an overlay to a parsed document, in place and in action order: each
 * action sees the result of the one before. A target that matches nothing
 * changes nothing. Throws an {@link OverlayError} naming the overlay file and
 * the action that failed.
 */
export const applyOverlay = (
  document: JsonValue,
  overlay: OverlayDocument,
  name: string
): void => {
  for (const [index, action] of overlay.actions.entries()) {
    try {
      applyAction(document, action);
    } catch (error) {
      // SAFETY: the JSONPath parser and this module throw Error instances.
      const { message } = error as Error;
      throw new OverlayError(
        `${name} action ${index + 1} (${action.target}): ${message}`
      );
    }
  }
};
